### ISSUE TITLE
Displaying Error when run this command "ng test --code-coverage"

### ISSUE THREAD

**Issue by vasu592** [MurhafSousli/ngx-sharebuttons#109]
Hi, I want to generate a test report by using above command but i got this error.
ERROR in ./src/node_modules/ng2-sharebuttons/index.js
Module build failed: SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (1:0)

**Comment by MurhafSousli** [comment]
Hi @vasu592 I have no knowledge about that I'm sorry
