### ISSUE TITLE
How to call  facebook model after some time

### ISSUE THREAD

**Issue by praveense5** [MurhafSousli/ngx-sharebuttons#113]
I want to share a image  which is rendering from server side  but image renders bit slow.When click on share button it shows shows blank popup. but after wait some time again click on share button it works.

**Comment by MurhafSousli** [comment]
The title is a bit confusing, I am not sure what you are trying to accomplish, how is image renderring has to do with blank popup, can you explain more by showing your usage code, or screenshots
