### ISSUE TITLE
Repeating errors in developer console when a popup blocker is enabled

### ISSUE THREAD

**Issue by tw3** [MurhafSousli/ngx-sharebuttons#115]
I have a popup blocker installed on my browser so naturally a popup doesn't appear when I click the Share button.  However my developer console is flooded with JavaScript errors as a result.  This is because there is an interval that checks to see if the `popUp.closed` is true is closed but `popUp` is null.

My suggestion would be the change this code in share-buttons.service.js:

    var popUp = this.window.open(Helper.shareFactory(type, args), 'newwindow', this.windowAttr());
    /** Emit clicked button */
    if (this.window) {
        var pollTimer_1 = this.window.setInterval(function () {
            if (popUp.closed) {
                _this.window.clearInterval(pollTimer_1);
                popUpClosed.emit(type);
            }
        }, 200);
    }

...to:

    var popUp = this.window.open(Helper.shareFactory(type, args), 'newwindow', this.windowAttr());
    /** Emit clicked button */
    if (this.window && popUp) {
        ...
    }

**Comment by MurhafSousli** [comment]
Hi @tw3, can you prepare a PR?

**Comment by tw3** [comment]
https://github.com/MurhafSousli/ng2-sharebuttons/pull/116

**Comment by MurhafSousli** [comment]
Thank you
