### ISSUE TITLE
Getting Failed to Load error for FaceBook

### ISSUE THREAD

**Issue by vasu592** [MurhafSousli/ngx-sharebuttons#117]
Hi,
I am getting this error in my console when i am posting google url
and count is 0 for this url 

 graph.facebook.com/?id=https%3A%2F%2Fwww.google.co.in%2F

 Failed to load resource: the server responded with a status of 403 ()

Failed to load resource: the server responded with a status of 403 ()

**Comment by MurhafSousli** [comment]
Hi @vasu592 The URL should be `https://google.co.in` !
