### ISSUE TITLE
facebook messanger share

### ISSUE THREAD

**Issue by OdaiTu** [MurhafSousli/ngx-sharebuttons#119]
hello

can you add facebook messanger share button ?

**Comment by MurhafSousli** [comment]
Hello @OdaiTu, it doesn't seem to be possible to add messenger share button without using the `appId`, but in case you find a way, let me know

**Comment by choopage** [comment]
Hi @MurhafSousli could you point me to the documentation mentioning the `appId`? So I could more research during my free time. Also I'm assuming the Facebook Messenger we are talking about  https://www.messenger.com and not the mobile app Messenger.

**Comment by MurhafSousli** [comment]
@choopage I am looking for a pure links without using an external script like facebook SDK that requires `appId`, and as far as I know, it is not possible with fb messenger
