### ISSUE TITLE
Error: e.map is not a function

### ISSUE THREAD

**Issue by kkreddymandadi** [MurhafSousli/ngx-sharebuttons#120]
Hi,

I am getting error after adding ShareButtonsModule.forRoot() to ngModule. 
Angular version: 2.0.0

![capture](https://cloud.githubusercontent.com/assets/26547003/25811781/583f5a00-33e2-11e7-9805-a59a359e3df3.JPG)

**Comment by MurhafSousli** [comment]
Hi @kkreddymandadi Are you sure this is caused by the share buttons?
Please paste your usage code if you still have the issue
