### ISSUE TITLE
Need to get Social sites Share or Post Response

### ISSUE THREAD

**Issue by vasu592** [MurhafSousli/ngx-sharebuttons#122]
Hi @MurhafSousli,  My requirement is Share or Post some Video URL's to Social media sites and need to increment a share count against that particular video in Database. 
If I get the post response then I will increment in Database. Other wise what can I do for this requirement.
Note: I can not use your social media counts, why because I should increment a share value in Database.

**Comment by MurhafSousli** [comment]
Hi @vasu592 the problem that you can not make sure if the user has proceed to share or cancelled the share dialog, so the database share record can not be accrued this way right! 
Maybe you can write a function to get the share counts for that particular URL from the social network directly and save it to your database!
