### ISSUE TITLE
Support for Latest versions of angular 

### ISSUE THREAD

**Issue by vasu592** [MurhafSousli/ngx-sharebuttons#123]
I am using 
angular/cli: 1.0.0
node: 7.6.0
os: linux x64
angular/animations: 4.1.2
angular/common: 4.1.2
angular/compiler: 4.1.2
angular/core: 4.1.2
angular/forms: 4.1.2
angular/http: 4.1.2
angular/platform-browser: 4.1.2
angular/platform-browser-dynamic: 4.1.2
angular/router: 4.1.2
angular/cli: 1.0.0
angular/compiler-cli: 4.1.2

is ngx share buttons support for this versions?
if not please explain in detail what we have to do?

**Comment by MurhafSousli** [comment]
@vasu592 Are you getting any error? or just wondering?

**Comment by vasu592** [comment]
I am getting count but not expecting, exactly what I Post or Share into social media
and I need to know which social media sites are give exact count.
for example if I post into Facebook, count of posted URL is incremented, but if I post in Google plus count is not incremented and in Twitter I can't post second time even. What I need to do

**Comment by MurhafSousli** [comment]
@vasu592 This is a different question please open a new one for it.
And keep your issue focused and related to the title, each issue should have a separated thread. this way we can avoid the spaghetti mode.

Coming to your main "question", Yes this library supports latest and future version.
