### ISSUE TITLE
In linked in, different url's count's are adding to a single url;

### ISSUE THREAD

**Issue by srikanthgudipudi** [MurhafSousli/ngx-sharebuttons#125]
we are trying to get share count for different url's  separately,but we are getting it as a single url count by adding previous other  url's.

**Comment by MurhafSousli** [comment]
Hi @srikanthgudipudi, I'm a bit confused! do you mean you want to get share count for a url in LinkedIn only, but more than once. is this your question?
Please show your code to help me understand what you are trying to accomplish.

**Comment by srikanthgudipudi** [comment]
For example I am posting 4 different URL s with the same site. I expected the count of each individual URL is "one" when I am shared in Linked In. But I am getting the count as 4 for each URL after shared all URL s in Linked in
1) http://speckyboy.com/#/video/0b9b4790-360d-11e7-8ed6-47a2bfb5691a
2) http://speckyboy.com/#/video/d89ace80-2b33-11e7-ab5c-195ccc4c402a
3) http://speckyboy.com/#/video/2915c3c0-2b5b-11e7-ab5c-195ccc4c402a
4) http://speckyboy.com/#/video/793c7820-37af-11e7-9d7a-e771421799c7

**Comment by MurhafSousli** [comment]
@srikanthgudipudi I still can not understand!

What do you mean by
 
> But I am getting the count as 4 for each URL after shared all URL s in Linked in

You see I asked you for the code but you didn't post it, and the English used is not helping me to understand your problem. I have to guess now what is in your mind!

Are you using the share-buttons in a loop for a list of links? or are you just interested in getting the count for a couple of links in linkedIn?

I will assume the second, here is what you can do :

 - Use a single share button 
```html
<share-button button="linkedin" [url]="dynamicLink"  (count)="shareCount($event)">
```
 - Or use the share directive
```html
<button shareButton="linkedin" [sbUrl]="dynamicLink" (sbCount)="shareCount($event)"
```

```ts
shareCount(count){
    console.log('here is the count for the link', count);
}
```
Now whenever you give `dynamicLink` a new URL, you will get a new count for it.

Let's ask @tinesoft, maybe he can understand the issue better than me
