### ISSUE TITLE
This is breaking Server Side rendering , did you check it with angular universal ?

### ISSUE THREAD

**Issue by ranavc32** [MurhafSousli/ngx-sharebuttons#128]
I am using it with angular universal , its breaking server side rendering, any fix or work around for that ?

**Comment by MurhafSousli** [comment]
I didn't test it on Universal, would you collaborate on this?

**Comment by niekheezemans** [comment]
I have the same problem when trying to build my application with the latest version of Angular Universal (embedded in Angular 4.1.1 platform-server). When trying to run "npm run start"

I've upgraded to the latest version of "ng2-sharebuttons": "^2.1.2"

Log: 
**> werkenbijciber-v2@0.0.0 start /Applications/XAMPP/xamppfiles/htdocs/websites/ciber-nl/V3/vacaturebank/werkenbijciber-v2
> ts-node src/server.ts

/Applications/XAMPP/xamppfiles/htdocs/websites/ciber-nl/V3/vacaturebank/werkenbijciber-v2/node_modules/ng2-sharebuttons/directives/share-button/share-button.directive.js:1
(function (exports, require, module, __filename, __dirname) { import { Directive, Input, Output, HostListener, EventEmitter } from '@angular/core';
                                                              ^^^^^^
SyntaxError: Unexpected token import**
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Applications/XAMPP/xamppfiles/htdocs/websites/ciber-nl/V3/vacaturebank/werkenbijciber-v2/dist/ngfactory/src/app/vacaturebank-components/vacancy-details/vacancy-details.component.ngfactory.ts:17:1)
    at Module._compile (module.js:570:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! werkenbijciber-v2@0.0.0 start: `ts-node src/server.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the werkenbijciber-v2@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/niekheezemans/.npm/_logs/2017-06-27T11_15_34_329Z-debug.log

**Comment by MurhafSousli** [comment]
@ranavc32 it is `ngx-sharebuttons` v3 now, not `ng2-sharebuttons`

**Comment by niekheezemans** [comment]
@ranavc32 I upgraded your module to ngx-sharebuttons but I still have issues when running it with angular universal (platform server) on angular 4.0.0 (regular ng serve & ng build --prod work as expected):

Nieks-MacBook-Pro-2:ciber niekheezemans$ npm run start

> ciber@0.0.0 prestart /Applications/XAMPP/xamppfiles/htdocs/websites/ciber-nl/V3/frontend/ciber
> ng build --prod && ngc

Hash: 48ecbda00ec3d7100088                                                      e Time: 9499ms
chunk    {0} polyfills.652ef966ac5414a711ed.bundle.js (polyfills) 160 kB {4} [initial] [rendered]
chunk    {1} main.8c03ac3b0e22834a7bca.bundle.js (main) 16.8 kB {3} [initial] [rendered]
chunk    {2} styles.d41d8cd98f00b204e980.bundle.css (styles) 69 bytes {4} [initial] [rendered]
chunk    {3} vendor.6b9da76f7adf68c3a425.bundle.js (vendor) 1.21 MB [initial] [rendered]
chunk    {4} inline.18ef6f2ca3220d40f56d.bundle.js (inline) 0 bytes [entry] [rendered]

> ciber@0.0.0 start /Applications/XAMPP/xamppfiles/htdocs/websites/ciber-nl/V3/frontend/ciber
> ts-node src/server.ts

/Applications/XAMPP/xamppfiles/htdocs/websites/ciber-nl/V3/frontend/ciber/node_modules/ngx-sharebuttons/directives/share-button/share-button.directive.js:1
(function (exports, require, module, __filename, __dirname) { import { Directive, Input, Output, HostListener, EventEmitter } from '@angular/core';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Applications/XAMPP/xamppfiles/htdocs/websites/ciber-nl/V3/frontend/ciber/dist/ngfactory/src/app/components/cookie-compliance/cookie-compliance.component.ngfactory.ts:11:1)
    at Module._compile (module.js:570:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ciber@0.0.0 start: `ts-node src/server.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ciber@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by MurhafSousli** [comment]
@niekheezemans The error is unclear, but it is not related to this library, I seems more related to `cookie-compliance`

**Comment by siloor** [comment]
@MurhafSousli At first thank you for this great library, it really saves us a lot of time by developing.

I just checked the forks of this library, and I found that @JayChase already solved the issue. https://github.com/JayChase/ngx-sharebuttons

Would it be possible to add his changes to this official repository?

Thanks!

**Comment by mfonolleda** [comment]
@siloor Did you get it to work on angular universal using @JayChase 's repo?

**Comment by siloor** [comment]
@mfonolleda yes-yes, it works just great with the latest stable angular dependencies
