### ISSUE TITLE
Add new sharelink (telegram) into ShareProvider

### ISSUE THREAD

**Issue by NgBeginner** [MurhafSousli/ngx-sharebuttons#132]
I'm just started learning  Angular and TS for few days, I'm sorry if i didn't understand well the code. 

The issue i facing is whenever i want to add new sharelink which is telegram, it keep return me this error,
just hope someone can help.

> [shareButton] must be set to one of the values (numeric or string) of ShareProvider enum: was 9.

sometimes it also suddenly will hit 
 - FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

i added the telegram stuff in the _variables, _style_color, enum, share.helper & sharelink , and inside the nGOnInit()

**Comment by MurhafSousli** [comment]
Hi @NgBeginner, welcome.
You cannot add telegram button, it is not supported yet.
You can only choose from the buttons listed here https://github.com/MurhafSousli/ngx-sharebuttons/wiki
But I will investigate about telegram when I get free time later

**Comment by MurhafSousli** [comment]
Will add Telegram in the next update, dup #142
