### ISSUE TITLE
shareButton attribute not working with innerHtml 

### ISSUE THREAD

**Issue by dhiraj-vinove** [MurhafSousli/ngx-sharebuttons#135]
`when` I am using shareButton attribute while using innerHtml , then it's not working. Please suggest.

<div [innerHtml]="responseData"></div>

where responseData contains:
"
<ul>
     <li class="wtsup"><a href="javascript:void(0)" shareButton="whatsApp" [sbUrl]="repoUrl"><i class="fa fa-whatsapp" aria-hidden="true"></i></a></li>
     <li class="fbk"><a href="javascript:void(0)" shareButton="facebook" [sbUrl]="repoUrl"><i class="fa fa-facebook-square" aria-hidden="true"></i></a></li>
</ul>
"

**Minimal usage of the plugin**

**Comment by MurhafSousli** [comment]
@dhiraj-vinove It is unclear what you are asking for! Please edit and fix your question, include the code your are using and the error if you are getting any.

**Comment by dhiraj-vinove** [comment]
when I am using shareButton attribute while using innerHtml , then it's not working. Please suggest.
for example:
`<div [innerHtml]="responseData"></div>`
where responseData contains:
`<button md-raised-button shareButton="twitter"><i class="fa fa-twitter"></i></button>`
so in this case angular not understanding this directive "shareButton"

but when I am using `<button md-raised-button shareButton="twitter"><i class="fa fa-twitter"></i></button>` this code direct in html then it's working . please suggest.Thank you.

**Comment by MurhafSousli** [comment]
@dhiraj-vinove You should not use the `[innerHtml]` of the share button, Instead set it on a child element 
```html
<button md-raised-button shareButton="twitter">
    <i class="fa fa-twitter"></i> 
    <div [innerHtml]="responseData"></div>
</button>
```
