### ISSUE TITLE
Provided stylesheet contains global rules

### ISSUE THREAD

**Issue by nassimm** [MurhafSousli/ngx-sharebuttons#136]
**I'm submitting a ...**
```
[x] bug report => search for a similar issue before submitting
[ ] feature request
[ ] question
```

The provided stylesheet contains global rules :

a:hover,button {
 cursor:pointer;
 outline:0;
 border:0;
}

Which, of course, breaks any "a" and "button" element that has either an outline or a border.

**Comment by MurhafSousli** [comment]
Will remove these global style in the next update
