### ISSUE TITLE
Single share button not working

### ISSUE THREAD

**Issue by kostenickj** [MurhafSousli/ngx-sharebuttons#137]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search for a similar issue before submitting
[ ] feature request
[ ] question
```

**Minimal usage of the plugin**

```

 <share-button button="facebook">
          </share-button>

app module:
imports: [
    ...
     ShareButtonsModule.forRoot(),
  ],
```

![image](https://user-images.githubusercontent.com/17304343/27564892-a42e10ea-5a8f-11e7-8483-e80f303e5ef9.png)

this does work:
`<share-buttons></share-buttons>`

**Comment by MurhafSousli** [comment]
Did you try `<share-button [button]="'facebook'"></share-button>` ?

Generally I recommend using the directive for a single share button
`<button shareButton="facebook"> Share on Facebook! </button>`

**Comment by kostenickj** [comment]
That way unfortunately doesnt work either. but the directive
<button shareButton="facebook"> Share on Facebook! </button>

does work. I just copied my first example straight from the docs

**Comment by MurhafSousli** [comment]
The default style only applies if you use `<share-buttons>` component, but I will make the style global in a future update.
