### ISSUE TITLE
Facebook share btn not working when variable is used in [sbTitle]

### ISSUE THREAD

**Issue by aditit-iprogrammer** [MurhafSousli/ngx-sharebuttons#138]
Hello,

Following code is not working for Facebook Share  Button.
In [sbTitle]=referralDetails.referral_sms_text_facebook -> it is showing sms text for sharing but getting message from Facebook as "Sorry, something went wrong.
We're working on getting this fixed as soon as we can. "

<button class="btn-share" shareButton="facebook" [sbUrl]="'https://mysite.com'" [sbTitle]="referralDetails.referral_sms_text_facebook"><i class="fa fa-facebook" style="background-color:#3B5998"></i></button> 

If I put plain text in [sbTitle] = "'Hey use this code for referal.'" Then it is working perfect. It needs single quotes inside double quotes. 
But how can I achieve this using variable?

Please advice.
- Aditi

**Comment by MurhafSousli** [comment]
Hi @aditit-iprogrammer,

 > it is showing sms text for sharing but getting message from Facebook as "Sorry, something went wrong.

Is this happening in development or in production?

> If I put plain text in [sbTitle] = "'Hey use this code for referal.'" Then it is working perfect. It needs single quotes inside double quotes.

this means that `referralDetails.referral_sms_text_facebook` is undefined!

**Comment by aditit-iprogrammer** [comment]
Hi @MurhafSousli ,
referralDetails.referral_sms_text_facebook is not undefined..it is showing text if I inspect button. So, var is not undefined. It works well with twitter. But, with facebook it is giving error.

**Comment by MurhafSousli** [comment]
@aditit-iprogrammer don't worry, this is because you are working locally, facebook will work when your app is online, read more  https://github.com/MurhafSousli/ngx-sharebuttons/issues/133#issuecomment-307882105

**Comment by aditit-iprogrammer** [comment]
I have checked on stage server with npm run build:prod, but there is also same error facebook, or sometimes it opens window and shuts it.

**Comment by MurhafSousli** [comment]
Give me the link to your online app
