### ISSUE TITLE
share text is not proper, showing with page url and shareText

### ISSUE THREAD

**Issue by aditit-iprogrammer** [MurhafSousli/ngx-sharebuttons#139]
Hi, 
Currently, I have ngx-sharebuttons used in one component and now I'm trying to implement it in another component also.
In second component, it gets implemented. (except facebook issue which I have mentioned in earlier issue.) But, issue is in the share window e.g. Twitter, it is showing page url and text appended to it.
example. :  http://my-url #The share text is like this.

I want only text without page url.
Meta tags are also added in index.html.
Please advice me for this.

**Comment by MurhafSousli** [comment]
You want to exclude the URL?! without the URL it is no longer sharing. it becomes a normal tweet. I don't think you can do that with `ngx-sharebuttons`

**Comment by aditit-iprogrammer** [comment]
In earlier component, we have managed to add only text without url (by adding meta tags in index.html)and it is working in that component. But, in this second component it is showing with URL.

**Comment by MurhafSousli** [comment]
Currently there is no option to remove the URL from the tweet. but it can be removed by commenting this [line](https://github.com/MurhafSousli/ngx-sharebuttons/blob/master/src/helpers/share-links.functions.ts#L30)
