### ISSUE TITLE
size of pop up

### ISSUE THREAD

**Issue by waynechaw** [MurhafSousli/ngx-sharebuttons#141]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search for a similar issue before submitting
[x ] feature request
[ ] question
```

Is  there a way to adjust the size of the popup?

**Comment by MurhafSousli** [comment]
Hi @waynechaw, Yes, you can set the size of the pop up using **ShareButtonsService**, [Wiki page](https://github.com/MurhafSousli/ngx-sharebuttons/wiki/Misc)

**Comment by waynechaw** [comment]
hi @MurhafSousli 

I believe there is a mistake in your documentation.

instead of setting `width` and `height` on the service, it should be `windowHeight` and `windowWidth`

**Comment by MurhafSousli** [comment]
@waynechaw Ops, my bad I updated the wiki
