### ISSUE TITLE
Telegram button

### ISSUE THREAD

**Issue by OdaiTu** [MurhafSousli/ngx-sharebuttons#142]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search for a similar issue before submitting
[ X] feature request
[ ] question
```

**Minimal usage of the plugin**

can you add telegram and messsnger btns ?

**Comment by MurhafSousli** [comment]
Telegram is possible but not fb messenger

**Comment by OdaiTu** [comment]
@MurhafSousli  thank for your time
how to use telegram and why cant use messenger ?

**Comment by MurhafSousli** [comment]
@OdaiTu Sorry, I didn't see your last comment until now! 
It is not up to us! it is up to facebook messenger to provide the functionality.

**Comment by OdaiTu** [comment]
no porblem bro
but i found some libs did it but its in laravel i think
see this 

![image](https://user-images.githubusercontent.com/12837840/31425131-9b145bb0-ae66-11e7-8345-53cea9f0eb5d.png)
