### ISSUE TITLE
How to get the respose after successfully shared the content in social media?

### ISSUE THREAD

**Issue by Sathishchary** [MurhafSousli/ngx-sharebuttons#143]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search for a similar issue before submitting
[ ] feature request
[ ] question
```

**Minimal usage of the plugin**

I need to get the success response message after successfully shared the article in social media. like `you are successfully shared`. I have used some options like `count` and `popUpClosed`, with this popUpClosed, I am getting the success message after shared, but if I directly close the popup also, it's calling. 
`<share-buttons (popUpClosed)="sharedSuccess()" [url]="shareUrl" title]="title"></share-buttons>`

```
sharedSuccess(){
  console.log("You have successfully shared the article");
}
```
So Is there any way to get the response after successfully shared the article on social media?

**Comment by MurhafSousli** [comment]
Hi @Sathishchary, We can't make sure if the user has shared or cancelled, otherwise we would have added this feature long time ago. The share window is out of our control, but we can detect when it is closed.
If you ever find a solution for this, let me know and I will add it as feature
