### ISSUE TITLE
[ShareButtons]: Invalid URL, fallback to Window URL

### ISSUE THREAD

**Issue by Fayde** [MurhafSousli/ngx-sharebuttons#144]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search for a similar issue before submitting
[x] feature request
[ ] question
```

I understand using the buttons without filling in [sbUrl] is intended to throw this warning, but can we suppress this somehow since it's filling up the console with stuff that looks like fatal errors.  It makes this solution appear to not be stable to clients.

**Comment by Fayde** [comment]
@MurhafSousli  please

**Comment by MurhafSousli** [comment]
@Fayde We are working on a new version for the `ngx-sharebuttons`
