### ISSUE TITLE
Share image is not showing

### ISSUE THREAD

**Issue by praveenkumarse** [MurhafSousli/ngx-sharebuttons#145]
When share a image dynamically on facebook then only link and title show. image doesn't show . I have installed ngx-share button and configure it as you are mentioned in doc. I have attached screen shot given below please check it.

does it works on localhost??? 

imageurl== https://football.innotical.com/media/share_image/1/Praveen_Tournament.jpg
link==https://peloteando.co

sharebutton==
<share-buttons [stumbleUpOn]="false" [tumblr]="false" [reddit]="false" [pinterest]="false" [linkedIn]="false" [google]="false" class="withCount" [url]="link" [whatsApp]="false" [image]="imageurl"></share-buttons>

![share](https://user-images.githubusercontent.com/20211510/28744864-49edf8bc-7488-11e7-80df-efa147a185e0.png)

**Comment by MurhafSousli** [comment]
No it does not work in localhost

**Comment by praveenkumarse** [comment]
I'm doing share on live server but same issue is occurring.

**Comment by MurhafSousli** [comment]
@praveenkumarse can you paste the URL shown in the share dialog?

**Comment by praveenkumarse** [comment]
yes,

https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Ftesting.peloteando.co%2Fdashboard%2Ftournaments%2Ftournament-profile%2F230&picture=https://football.innotical.com/media/share_image/1/Praveen.jpg
 I have 
![image](https://user-images.githubusercontent.com/20211510/28755406-cfa6465e-7577-11e7-81f9-92de82e75098.png)
attached screenshot below.

**Comment by MurhafSousli** [comment]
Try to add meta tags in the head `index.html`

`<meta property="og:image" content="https://football.innotical.com/media/share_image/1/Praveen.jpg">`

**Comment by praveenkumarse** [comment]
If we add image in meta tag , it works fine but  i'm doing share image dynamically which is generated by HTML canvas.

**Comment by MurhafSousli** [comment]
Looks like Facebook has disabled passing parameters to the sharer. check the [original answer](https://stackoverflow.com/a/23256034/1015648) I am afraid this is a wontfix

**Comment by praveenkumarse** [comment]
I have checked on this url (
https://developers.facebook.com/x/bugs/357750474364812/), there are many
users facing same problem. If you have any solution please reply me.

**Comment by mohitook** [comment]
hello,
just for some information: is it going to work.. ever? or can we find any useful workaround for still share content on facebook? thanks.

**Comment by danielGz** [comment]
@mohitook I created a filter in my web application to serve the meta tags html response when any of the common web crawlers is in the User-Agent header. Is not a pretty solution but it works, plus you can forget about pre-render problems with that and facebook actually suggests that approach, see [https://developers.facebook.com/docs/sharing/webmasters/optimizing](url)

**Comment by salisenad** [comment]
Hi, is the dynamic image working now?

**Comment by Hesham1Gomaa** [comment]
@praveenkumarse  Is this problem solved with you? , As I can not solve it till Now.
