### ISSUE TITLE
Error after npm install --save ngx-sharebuttons

### ISSUE THREAD

**Issue by vadimneta** [MurhafSousli/ngx-sharebuttons#146]
hello,
after running this command: npm install --save ngx-sharebutton
in ng build, a get a lot of errors:
ERROR in D:/Projects/VisualStudioProjects/AngularDemo/node_modules/@types/jquery/index.d.ts (2936,24): Cannot find name
'any'.

ERROR in D:/Projects/VisualStudioProjects/AngularDemo/node_modules/@types/jquery/index.d.ts (2936,30): Cannot find name
'obj'.

ERROR in D:/Projects/VisualStudioProjects/AngularDemo/node_modules/@types/jquery/index.d.ts (2936,34): Cannot find name
'is'.

ERROR in D:/Projects/VisualStudioProjects/AngularDemo/node_modules/@types/jquery/index.d.ts (2936,44): Property 'PlainOb
ject' does not exist on type 'typeof JQuery'.

ERROR in D:/Projects/VisualStudioProjects/AngularDemo/node_modules/@types/jquery/index.d.ts (2944,5): Cannot find name '
isWindow'.

ERROR in D:/Projects/VisualStudioProjects/AngularDemo/node_modules/@types/jquery/index.d.ts (2944,14): Cannot find name
'obj'.

what the problem?
thanks a lot!

**Comment by MurhafSousli** [comment]
`npm install --save ngx-sharebuttons` not `ngx-sharebutton`
