### ISSUE TITLE
Getting error after npm install --save ngx-sharebuttons

### ISSUE THREAD

**Issue by vadimneta** [MurhafSousli/ngx-sharebuttons#147]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Getting error after npm install --save ngx-sharebuttons
[ ] feature request
[ ] question
```

hello,
after running  **npm install --save ngx-sharebuttons**

i get error:

ERROR in D:/Projects/VisualStudioProjects/AngularDemo/node_modules/@types/jquery/index.d.ts (2936,24): Cannot find name
'any'.

ERROR in D:/Projects/VisualStudioProjects/AngularDemo/node_modules/@types/jquery/index.d.ts (2936,30): Cannot find name
'obj'.

ERROR in D:/Projects/VisualStudioProjects/AngularDemo/node_modules/@types/jquery/index.d.ts (2936,34): Cannot find name
'is'.

ERROR in D:/Projects/VisualStudioProjects/AngularDemo/node_modules/@types/jquery/index.d.ts (2936,44): Property 'PlainOb
ject' does not exist on type 'typeof JQuery'.

ERROR in D:/Projects/VisualStudioProjects/AngularDemo/node_modules/@types/jquery/index.d.ts (2944,5): Cannot find name '
isWindow'.

ERROR in D:/Projects/VisualStudioProjects/AngularDemo/node_modules/@types/jquery/index.d.ts (2944,14): Cannot find name
'obj'.

please help,
Thanks a lot!

**Minimal usage of the plugin**

**Comment by MurhafSousli** [comment]
dup #146
@vadimneta you won't get a better answer if open the same exact issue!
There is a problem with your app and jQury which I can't help you with. but it has nothing to do with the **ShareButtonsModule**

**Comment by vadimneta** [comment]
Hello,
Before install the "npm install --save ngx-sharebuttons"
i have not error in my app

the error that i get releted to install,
If you do not want to help or know how to help just say it.
Don't say that the error no  relate to install your plugin

**Comment by MurhafSousli** [comment]
Trust me these errors are not caused by this plugin!
I can help you with issues related to this plugin. but you need to read the errors!

If you don't want to believe me, verify it yourself by testing the plugin on a new empty app (use [Angular CLI](https://github.com/angular/angular-cli)).

Or try to reproduce the problem with this working [plnkr](https://plnkr.co/edit/BpV3UElDgdp0S9NPFRRO?p=preview).

_P.S: do your self a favor and **stop** using jQuery with Angular._

**Comment by vadimneta** [comment]
Hello,
OK,
I will check it on new fresh  empty app like you sagest me.
I did't now that i use  jQuery with Angular - i will check it too.

thanks a lot

**Comment by vadimneta** [comment]
Hello,
I checked it on new fresh empty app like you sagest,
and it's work fine,thank you for your sagest :+1:  :)

I have some issue and question:

# 1: 
 The Facebook button,create error:
**Sorry, something went wrong.
We're working on getting this fixed as soon as we can.**

how to fix it? do you have workaround for this?

# 2:
In WhatApp button:
How to change and insert **my custom text** instead of link of site that in whatsApp opened window ?

thanks a lot!

**Comment by erpardeepjain** [comment]
Getting same issue After removing 
```"@ngx-share/button": "^7.1.4",
"@ngx-share/buttons": "^7.1.4",
"@ngx-share/core": "^7.1.4",```

and installating 
```"ngx-sharebuttons": "^9.0.0",```
on Angular 11 project
