### ISSUE TITLE
Custom title/description on Facebook

### ISSUE THREAD

**Issue by brandhaug** [MurhafSousli/ngx-sharebuttons#149]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search for a similar issue before submitting
[ ] feature request
[ ] question
```

Trying to have a custom title/description for the sharing, but doesn't seem to work on Facebook.

First I tried using a custom title and description meta tag using import {Meta, Title} from '@angular/platform-browser', but that didn't seem to work.

I tried to add the properties [title] and [description] (like in the code snippet), but that did not work either. The title and description showing up is the title and description from index.html.

The description works on Twitter.

HTML
```
            <share-buttons [url]="'https://knowyourvc.com/blog/' + post.url" 
                           [whatsApp]="false" 
                           [google]="false"
                           [pinterest]="false"
                           [reddit]="false"
                           [tumblr]="false"
                           [linkedIn]="false"
                           [stumbleUpOn]="false"
                           [title]="''This is a test title"
                           [description]="'This is a test description"></share-buttons>
```

![skjermbilde 2017-08-11 kl 16 14 09](https://user-images.githubusercontent.com/15323861/29216835-27d3a0e2-7eb0-11e7-801a-26a839ae224e.png)

**Comment by MurhafSousli** [comment]
Facebook does not support it anymore dup #145 #148, [more info](https://stackoverflow.com/a/23256034/1015648).
