### ISSUE TITLE
Can ngx-sharebuttons use HttpClient instead?

### ISSUE THREAD

**Issue by bjornharvold** [MurhafSousli/ngx-sharebuttons#150]
```
[X ] feature request
```

Since HttpClient came out I've been able to remove all references to HttpModule....except for ngx-sharebuttons. Would be a nice to have.

**Comment by MurhafSousli** [comment]
Hi @bjornharvold I have a plan to add an `HttpClient` plug in the next update (version 4).

**Comment by raDiesle** [comment]
That is why i got error, because i am missing in my app to add to definitions:

EXCEPTION: No provider for Http!

import { HttpModule } from '@angular/http';
+1

**Comment by manuel-di-iorio** [comment]
+1 for using the new HttpClientModule

```
Error: No provider for Http!
```

**Comment by naveedahmed1** [comment]
Any update on this?

**Comment by MurhafSousli** [comment]
@naveedahmed1 This is fixed now, try the beta version `npm i ngx-sharebuttons@beta`

**Comment by naveedahmed1** [comment]
Awesome! Thank you so much @MurhafSousli :)

**Comment by bjornharvold** [comment]
I can confirm that it is working. The style is completely off though...but that's something completely different :-)
