### ISSUE TITLE
Docu wrong for inputs: "sbTitle" ... should be "title"

### ISSUE THREAD

**Issue by raDiesle** [MurhafSousli/ngx-sharebuttons#152]
<share-buttons  [sbUrl]="'test'"></share-buttons>

inputs do not start with "sb*"

@Input() url: string;
    @Input() title: string;
    @Input() description: string;
    @Input() image: string;
    @Input() tags: string;

**Comment by MurhafSousli** [comment]
Hi @raDiesle you are mixing between component usage and directive usage, the docs do not use `sbUrl` on the component
