### ISSUE TITLE
Property 'myUrl' does not exist on type '...'

### ISSUE THREAD

**Issue by mohitook** [MurhafSousli/ngx-sharebuttons#154]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search for a similar issue before submitting
[ ] feature request
[x ] question
```

Hello, I had to upgrade to the latest angular 4 version and unfortunately when I do 

`ng build --prod`

it doesn't recognize the 'myUrl' property of your module :(.
Throws this error: Property 'myUrl' does not exist on type '..myComponent'.

I use it like this: 
`<share-buttons [description]="blablabla" [url]="myUrl" ...`

maybe if I do the build with turning of the aot will help, but it won't solve the problem for long term.

**Comment by MurhafSousli** [comment]
Hi @mohitook  please post your full usage code

**Comment by mohitook** [comment]
Hello,
Here is the full code(unfortunately you won't get any necessary information from it)
`<share-buttons [description]="Descriptionnn" [url]="myUrl" [title]=Title" 
          [linkedIn]="false"
          [tumblr]="false"
          [pinterest]="false"
          [stumbleUpOn]="false"
          [whatsApp]="false"
        ></share-buttons>`

The problem is, that the AOT compile don't recognize the myUrl property, which is a property provided by YOU.

**Comment by MurhafSousli** [comment]
@mohitook These inputs must be defined in your component by you! 
The library provide inputs, and you don't have to use all of inputs, use only what you need.
The next version will have a better documentation, so stay tuned!

**Comment by mohitook** [comment]
well, normally the imputs e.g.: description, title and so are defined in the component.. unfortunately as I said the AOT compiler doesn't recognize the "myURL" property, so the problem is only with this property because I need this in runtime, because the component can have multiple urls/which are the identifiers of the current page content. It could be a solution if I can get the current url somehow in the component but unfortunately I didn't find the perfect solution for this. YOur myUrl property has worked before, and till works, the problem is only with the AOT.

**Comment by MurhafSousli** [comment]
@mohitook you did not share your component, if you have added `private` to the property, it will cause this problem in AOT

**Comment by mohitook** [comment]
thank you, this is what I have searched for! I'll remove the [url] tag, thank you!
