### ISSUE TITLE
Share ignore params config

### ISSUE THREAD

**Issue by rluckez** [MurhafSousli/ngx-sharebuttons#155]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search for a similar issue before submitting
[ ] feature request
[ ] question
```

**Minimal usage of the plugin**
Hello, thanks for develop that plugin.
I'am triyng to use the directive as described below, but, it do not recognize my params config and always use page title and current url on share.
I'am using ionic 3, wich uses angular 4 at the moment.

![image](https://user-images.githubusercontent.com/11165664/30744257-a401ffc8-9f77-11e7-85b1-b2b63d6d3444.png)

![image](https://user-images.githubusercontent.com/11165664/30744326-f966c016-9f77-11e7-9c73-13a23e8a1f2f.png)

and this is what i got on share

![image](https://user-images.githubusercontent.com/11165664/30744398-47ded378-9f78-11e7-829b-3febd0041a02.png)

![image](https://user-images.githubusercontent.com/11165664/30744410-57df7110-9f78-11e7-81bb-467f568b090d.png)

I've added OG meta tags on page head.
Both directive and component is not working for me.
Is there something that i missed?

Thanks!

**Comment by MurhafSousli** [comment]
Hi @rluckez The code seems fine to me! can you reproduce your problem using this [plunkr](https://plnkr.co/edit/BpV3UElDgdp0S9NPFRRO?p=preview)?

**Comment by rluckez** [comment]
On plunkr works like a charm. I do not know what happens, not even the basic example "<share-buttons></share-buttons>" works on my project.
I'll try to use on a only angular project, instead ionic and see what happens.

**Comment by rluckez** [comment]
Sorry for take so long, i was working in another projects.
I solved the issue, in config params i have to change url from: "www.myurl.com" to "http://www.myurl.com"
That was my fault.
Thx man!

**Comment by YamanSehzade** [comment]
Hi @rluckez, 
How did you implement ionic ? Could you tell, please ?

**Comment by rluckez** [comment]
Hello @YamanSehzade if you are using ionic 2 or greater you can just follow example on documentation.
Just run npm install --save ngx-sharebuttons and import the module on app.module.ts.
What did you try?

**Comment by YamanSehzade** [comment]
I had a problem about node version so it was not working. Now, i haven't any problem. Thank you for reply...

**Comment by YamanSehzade** [comment]
@rluckez how could you implement style ?

i try to use share-buttons:
```
 <share-buttons [theme]="'circles'" [include]="'facebook','twitter','linkedin','google','whatsapp','email','copy']" [show]="7"
      [showName]="true" [size]="-3" [url]="'https://xxx"></share-buttons>
```


my share-buttons look like this:
![image](https://user-images.githubusercontent.com/22771125/31852708-98f1e8ac-b67c-11e7-896f-1ed0d0b395c3.png)

when i add that line in global variable.scss
```
@import '~ngx-sharebuttons/styles/variables';
@import '~ngx-sharebuttons/styles/share-buttons';
```

i get this error:
![image](https://user-images.githubusercontent.com/22771125/31852726-0471309c-b67d-11e7-9bbb-958752773a83.png)

Do you have any idea ?

**Comment by rluckez** [comment]
@YamanSehzade In version 3 your example used to work for me. Now in version 4 i've tested your example and had same issue.
Iam using the directive with my own custom button in my project, so, i did not face this issue. 
If you want, you can use your own buttons like me.

![image](https://user-images.githubusercontent.com/11165664/31852923-ec658372-b65e-11e7-8867-6c54db61e6d3.png)

I hope it helps =)

**Comment by MurhafSousli** [comment]
@YamanSehzade your screenshot shows that the URLs is missing `~`. I am not sure if you forgot to add it, or if it is a bug in ionic. but the `~` should point to your `node_modules` directory

![image](https://user-images.githubusercontent.com/22771125/31852726-0471309c-b67d-11e7-9bbb-958752773a83.png)

Try this
```scss
@import 'node_modules/ngx-sharebuttons/styles/share-buttons';
@import 'node_modules/ngx-sharebuttons/styles/themes/default-theme/default-theme';
```

If it is still not working, then just copy and paste the [styles folder](https://github.com/MurhafSousli/ngx-sharebuttons/tree/master/src/styles) in your assets folder, and import it from there
```scss
@import 'assets/styles/share-buttons';
@import 'assets/styles/themes/default-theme/default-theme';
```

_No need to import `variables.scss` unless you want to modify the styles_

**Comment by YamanSehzade** [comment]
Hi @MurhafSousli ,
I tried both.
```
@import '~ngx-sharebuttons/styles/variables';
@import '~ngx-sharebuttons/styles/share-buttons';
```
and
```
@import 'ngx-sharebuttons/styles/variables';
@import 'ngx-sharebuttons/styles/share-buttons';
```
They gave the same error. I accidentally put the other picture...
I decided to use the directive method. thank you for helping

**Comment by rluckez** [comment]
@YamanSehzade Sorry for take so long, i did not work this weekend, so, i couldn't help you as i wish.
