### ISSUE TITLE
Facebook button metadata  not working

### ISSUE THREAD

**Issue by jirungaray** [MurhafSousli/ngx-sharebuttons#156]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search for a similar issue before submitting
[ ] feature request
[ ] question
```

**Minimal usage of the plugin**
Facebook isn't taking metadata setup up in a custom button with the following settings:
`    <button shareButton="facebook" [sbImage]="event.imageUrl" [sbDescription]="event.description" [sbTitle]="event.name" [sbTags]="'curselo'"><i class="fa fa-facebook"></i></button>`

I can see the params being sent over like so:
https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fcurselo.com%2Fevents%2F5651124426113024&title=Huerta%20organica&description=Como%20armar%20una%20huerta%20org%C3%A1nica&picture=https://firebasestorage.googleapis.com/v0/b/curselo-web.appspot.com/o/images%2Fevents%2F5651124426113024.jpg?alt=media

But facebook is still using the page default metadata on the facebook card.

**Comment by MurhafSousli** [comment]
Hi @jirungaray, this is a dup of #148, #149, #145 
[more details in this SO](https://stackoverflow.com/a/23256034/1015648)
