### ISSUE TITLE
Support for FontAwesome Pro Release Candidate

### ISSUE THREAD

**Issue by john-boy** [MurhafSousli/ngx-sharebuttons#158]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search for a similar issue before submitting
[ ] feature request
[x] question
```

**FontAwesome Pro Support**

I am integrating FontAwesome Pro into my project.  The tags for SVG brands have changed.  For instance `fa fa-facebook` is now `fab fa-facebook`.  Will this new package be supported?  Soon?  Ever?

Thanks,

John Clark

**Comment by MurhafSousli** [comment]
Hi @john-boy version 4 beta is out, Now you can set icons class, check the new [docs](https://murhafsousli.github.io/ngx-sharebuttons/#/global-options)
