### ISSUE TITLE
Twitter share why no image ?

### ISSUE THREAD

**Issue by olivierscheffler** [MurhafSousli/ngx-sharebuttons#159]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search for a similar issue before submitting
[ ] feature request
[x ] question
```

**Minimal usage of the plugin**
I want to share a image with facebook and twitter but your package doesn't support image for twitter..
But if I read the documentation of twitter we can share an image with.
Why is it not possible with the package?

Thank you !

**Comment by MurhafSousli** [comment]
Hi @olivierscheffler As far as I know, Twitter displays the image if it exists in your page meta tags. After you tweet, refresh and you should get find it. but it won't show before posting the tweet

**Comment by olivierscheffler** [comment]
Hi @MurhafSousli 
The problem is I have a angular SPA but with two languages French and English..
And since it's a spa I have only one index.html so I can't use meta tags..
I have try with Facebook too with your package and even in a prod server it doesn't display the information I pass by the directive like you did in your wiki..
Do you have an idea how I can make this work with two languages but only one index.html so not possible to use meta tags?

Thank you very much!

**Comment by MurhafSousli** [comment]
Use **Universal** to make your app SEO Friendly. but this is not related to this plugin.

This video might help https://youtu.be/lncsmB5yfzE?t=12m57s

Facebook relies on the meta tags only. `[sbTitle]`, `[sbDescription]` and the other meta tags inputs do not necessarily work for all buttons. they override the tags only if the social network allows it.

**Comment by MurhafSousli** [comment]
Images works on tweets! you just get your app SEO friendly.

![image](https://user-images.githubusercontent.com/8130692/31538099-26c6441e-b00d-11e7-8156-167f46d97b6e.png)
