### ISSUE TITLE
Use native apps to share links on mobile

### ISSUE THREAD

**Issue by MurhafSousli** [MurhafSousli/ngx-sharebuttons#161]

**Comment by choopage** [comment]
Hi @MurhafSousli do you have a design brief in mind?

**Comment by MurhafSousli** [comment]
Hi @choopage 
The design is already implemented, we only need to get the correct deep linking URLs for each button and add them in [classes/index](https://github.com/MurhafSousli/ngx-sharebuttons/blob/master/src/classes/index.ts)
such as 
```
{
    type: 'twitter',
    shareUrl: 'https://twitter.com/intent/tweet?url=',
    androidUrl: 'com.twitter.package?url=',
    iosUrl: 'twitter://tweet?url='
}
```
then the following can applies
```ts
export class TwitterButton implements IShareButton {

  constructor(public prop: ShareButtonProp) {
  }

  link(url: string, args?: ShareButtonArgs) {

    let shareUrl;

    if (args.mobile === 'android') {
        shareUrl = this.prop.androidUrl;
    } else if(args.mobile === 'ios') {
        shareUrl = this.prop.iosUrl;
    } else {
        shareUrl  = this.prop.shareUrl;
    }

    shareUrl += url;
    // ...

    return shareUrl;
  }
}
```

**Comment by MurhafSousli** [comment]
In version 5, we just need to find out the deep linking values and fill them in `android` and `ios` properties in [share.prop.ts](https://github.com/MurhafSousli/ngx-sharebuttons/blob/master/lib/core/src/share.prop.ts)

**Comment by jcao02** [comment]
Is there a PR opened for this @MurhafSousli ? WhatsApp deep link would be something like `whatsapp://send?text=...`

**Comment by MurhafSousli** [comment]
@jcao02 No, there is not.
Each platform has its own sharer link, `whatsapp://send?text=` is for IOS, Android starts with `com.whatsapp.package` (not sure) . here is an article I found [Mobile Deep Linking for Web and Hybrid Apps](https://developer.telerik.com/featured/mobile-deep-linking-web-hybrid-apps/). but I could not find an official source to get the proper links and its arguments,

**Comment by ignazioa** [comment]
@MurhafSousli any plan to merge this anytime soon? The module works like a charm but this is currently a blocker for me (great work!)

**Comment by MurhafSousli** [comment]
@ignazioa Why is it blocking you?

**Comment by ignazioa** [comment]
@MurhafSousli buttons are working, however, some of them (facebook, whatsapp, linkedin) do not obviously deep-link the app on iOS ... or ... am I doing something wrong? 
Since I am only targeting a webapp and not native solutions, sharing will require extra work to get deep-linking to work ...

**Comment by ignazioa** [comment]
could you please eventually point me to viable workarounds using the package?

**Comment by MurhafSousli** [comment]
@ignazioa Currently only whatsapp uses the deep linking on mobile. 

Can you collaborate on this? 

This is how the props file looks [share.prop.ts](https://github.com/MurhafSousli/ngx-sharebuttons/blob/master/lib/core/src/share.prop.ts)

google the correct deep-links for each button you want, override `ios` and `android` props and test them instantly on your phone using this https://stackblitz.com/edit/ngx-sharebuttons-test?file=app/app.module.ts

---
Currently, I tested https://ngx-sharebuttons.stackblitz.io/#/ on my ios device

Twitter, LinkedIn and Whatsapp opens in the native apps

**Comment by daco** [comment]
> Currently, I tested https://ngx-sharebuttons.stackblitz.io/#/ on my ios device
WhatsApp does opens in the native app, but nothing is shared. Tested on iOS 11.2.6

**Comment by MurhafSousli** [comment]
Will track status in #238
