### ISSUE TITLE
Please Add Support for Server Side Rendering - Angular Universal

### ISSUE THREAD

**Issue by naveedahmed1** [MurhafSousli/ngx-sharebuttons#163]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search for a similar issue before submitting
[ ] feature request
[ ] question
```

### Versions
Beta 4

### Repro steps
When using this plugin with Server Side Rendering (Angular Universal), the app crashes with below error:

```
ReferenceError: Document is not defined
ReferenceError: Document is not defined
at exports.modules.548.ShareButtonDirective.ctorParameters 
```
It seems that you are accessing Document, Window or DOM directly which isn't recommended.

**Comment by MurhafSousli** [comment]
@naveedahmed1 the directive does not access `Document` directly, this is the **Document** that angular introduces (which I expected it to support Universal) but since you are getting this problem, it means it does not. I will investigate for the best way, if not we will be using the old way

https://github.com/MurhafSousli/ngx-sharebuttons/blob/851babe0c339b34e8b1e99e261b0ebca69834e21/src/directives/share-button.directive.ts#L12

https://github.com/MurhafSousli/ngx-sharebuttons/blob/851babe0c339b34e8b1e99e261b0ebca69834e21/src/directives/share-button.directive.ts#L95

**Comment by naveedahmed1** [comment]
Thank you @MurhafSousli for sharing this. While you investigate this, would it be possible to handle it the way it was in V3, in next beta?

**Comment by MurhafSousli** [comment]
@naveedahmed1 it is fixed now

**Comment by MurhafSousli** [comment]
@naveedahmed1 How do you see two copies of HttpClient? What is the error saying?

https://github.com/MurhafSousli/ngx-sharebuttons/blob/3a946ed92836b953e99c733bf73579626ad7a39d/src/modules/share-directive.module.ts#L26-L27

**Comment by naveedahmed1** [comment]
Since you have added HttpClient in the providers, that's why its creating another instance.

To reproduce, add HttpClient to the providers of your AppModule (that's how you would probably use it). Create an interceptor to add some headers to each outgoing request. In app component sent an http request, you will notice that your headers are added to each outgoing request.

Now, create a LazyModule, add this plugin to a component in that module. Now send an http request. from that component and monitor the headers of that request. Ideally, it should add the headers to this request as well. But that's not the case here, since the requests are sent from another instance of the HttpClient which was created when this plugin was added to the imports of this LazyModule.

**Comment by MurhafSousli** [comment]
@naveedahmed1 This is a different issue! and there is no error, plus I just tested it with a lazy module and it worked properly.

In this case, I recommend you to look at the code yourself and let me know if you find a bug in separate issue.

**Note** that `HttpClientModule` is imported in the library but it is not exported

**Comment by chozharajan** [comment]
Am getting `ReferenceError: navigator is not defined` for universal. how make _server side render_ support
any idea thanks in advance
