### ISSUE TITLE
npm installs the version 3 by default

### ISSUE THREAD

**Issue by Falci** [MurhafSousli/ngx-sharebuttons#165]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search for a similar issue before submitting
[X] feature request
[ ] question
```

### Versions
@angular/cli: 1.3.1
node: 6.9.4
os: darwin x64

### Repro steps
Follow the [Getting started page](https://murhafsousli.github.io/ngx-sharebuttons/#/getting-started):
`npm install --save ngx-sharebuttons`

This command will install the version 3.0.0
`└── ngx-sharebuttons@3.0.0 `

Since the version 3 is deprecated, the default install should be version 4.

I don't know why npm has installed version 3 instead of 4 but it'd be good to update the readme and/or Getting started page to enforce the version number, like:
`npm install --save ngx-sharebuttons@4.0.0`

**Comment by Falci** [comment]
I'm sure something is wrong, but not sure what.

Even using the version 4 I can't find the style files. Why it is not showing that folder/file?

![File structure](https://imgur.com/O54eTun.png)

As you can see, it's working for font-awesome, so it's not a project-config problem.
I can see more file/folders than version 3, but not the style

**Comment by MurhafSousli** [comment]
@Falci I am trying to solve universal issue atm, try `ngx-sharebutton@4.0.0-beta0` until I publish a fixed dist
