### ISSUE TITLE
Missing [include], [exclude] properties

### ISSUE THREAD

**Issue by bfbca** [MurhafSousli/ngx-sharebuttons#166]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search for a similar issue before submitting
[ ] feature request
[ ] question
```

### Versions

@angular/cli: 1.3.2
node: 7.10.1
os: linux x64
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/core: 2.4.10
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10
@angular/cli: 1.3.2
@angular/compiler-cli: 2.4.10

### Repro steps

share-buttons [url]="share.link" [title]="app.title" [description]="app.desc" [tags]="share.tags" [include]="['facebook']"></share-buttons>
### The log given by the failure

ERROR in Template parse errors:
Can't bind to 'include' since it isn't a known property of 'share-buttons'.
1. If 'share-buttons' is an Angular component and it has 'include' input, then verify that it is part of this module.
2. If 'share-buttons' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 (" <share-buttons [url]="share.link" [title]="app.title" [description]="app.desc" [tags]="share.tags" [ERROR ->][include]="['facebook']">
        </share-buttons>
      </div>
"): AppViewComponent@57:107
ERROR in ./src/main.ts

**Comment by MurhafSousli** [comment]
It seems that you installed v3 instead of v4, try installing again `npm i ngx-sharebuttons@latest`

**Comment by bfbca** [comment]
Thank you for reply. Sorry, after uninstalling v3, installing v4.0.2 unfortunately angular 2.4.10 CLI still errors out.

ERROR in Error encountered resolving symbol values statically. Could not resolve @angular/common/http relative to /home/[snip]/client/node_modules/ngx-sharebuttons/ngx-sharebuttons.d.ts., resolving symbol ShareDirectiveModule in /home/[snip]/client/node_modules/ngx-sharebuttons/ngx-sharebuttons.d.ts, resolving symbol ShareDirectiveModule in /home/[snip]/client/node_modules/ngx-sharebuttons/ngx-sharebuttons.d.ts

**Comment by MurhafSousli** [comment]
@bfbca Version 4 supports angular 4.3+ only, for angular 2 keep using version 3

**Comment by bfbca** [comment]
Ok thanks
