### ISSUE TITLE
Must this be imported only once, in root?

### ISSUE THREAD

**Issue by karptonite** [MurhafSousli/ngx-sharebuttons#169]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search for a similar issue before submitting
[ ] feature request
[x] question
```

To import the `ShareDirectivesModule`, you use `ShareDirectivesModule.forRoot()`. Am I correct to assume, therefore, that this must be imported in your application root? Can it be used in a lazy loaded module?

**Comment by MurhafSousli** [comment]
@karptonite It is **`ShareDirectiveModule`**
In your root component use `ShareDirectiveModule.forRoot()` only once and then in any child or lazy module that uses the directive, import it again but without `forRoot()`
