### ISSUE TITLE
Request for Font Awesome Pro support

### ISSUE THREAD

**Issue by john-boy** [MurhafSousli/ngx-sharebuttons#172]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search for a similar issue before submitting
[x] feature request
[ ] question
```

### Versions
4.0.2

I want to use the new version of Font Awesome (PRO).  Will this be supported?  If so, when?

Thanks for your help, John

**Comment by MurhafSousli** [comment]
@john-boy font awesome 5 pro has different syntax than font awesome 4. try this `<share-button>` component with a custom template
```html
<share-button button="facebook">
   <i class="fa">facebook</i>
   <b>Share!</b>
</share-button>
```

**Comment by john-boy** [comment]
Thanks, this approach works.  There is one modification to the suggested approach.  The pro version uses class 'fab', i.e. <i class="fab">facebook</i>.
