### ISSUE TITLE
Problem with import of HttpClientModule overwriting interceptors

### ISSUE THREAD

**Issue by karptonite** [MurhafSousli/ngx-sharebuttons#174]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search for a similar issue before submitting
[ ] feature request
[ ] question
```

### Versions
```
@angular/cli: 1.4.7
node: 8.7.0
os: darwin x64
@angular/animations: 5.0.0-rc.2
@angular/common: 5.0.0-rc.2
@angular/compiler: 5.0.0-rc.2
@angular/core: 5.0.0-rc.2
@angular/forms: 5.0.0-rc.2
@angular/http: 5.0.0-rc.2
@angular/platform-browser: 5.0.0-rc.2
@angular/platform-browser-dynamic: 5.0.0-rc.2
@angular/platform-server: 5.0.0-rc.2
@angular/router: 5.0.0-rc.2
@angular/cli: 1.4.7
@angular/compiler-cli: 5.0.0-rc.2
@angular/language-service: 5.0.0-rc.2
typescript: 2.5.3
```

### Repro steps
import `ShareDirectiveModule` in a module (I've only seen it in a lazy-loaded module, but I don't think it is required), when HTTP_INTERCEPTORS are provided at a higher level (for example, in the root app module).

### The Issue
The `ShareDirectiveModule` imports `HttpClientModule`. According to the angular docs, the `HttpClientModule` need only be imported once, in the root of the App. One consequence of re-importing the `HttpClientModule` is that `HTTP_INTERCEPTORS` are essentially reset both in the `ShareDirectiveModule` (which isn't a problem) and for the module which imports the `ShareDirectiveModule`. 

In my App, for example, I found that all of the HttpRequests that were initiated in the module that also imported your module (but nothing at a higher level) ran without my interceptors.

I'm not sure if this is the intended behavior for angular, or if it is an angular bug, but there might be an easy fix: instead of having `ShareDirectiveModule` import `HttpClientModule`, amend the docs to have users import `HttpClientModule` when they import the `forRoot()`  for your module. You may want to do the same with the `HttpClientJsonpModule`, which adds an interceptor--I'm not sure if it is necessary, though.

Of course, that means that all of your requests will also pass through my interceptor, but it is my responsibility to write the interceptors in a way that doesn't cause problems for your requests.

Obviously, this is a breaking change, but as the package is written now, it is a problem for users who rely on `HTTP_INTERCEPTORS`.

**Comment by MurhafSousli** [comment]
Hi @karptonite, The library imports `HttpClientModule` and `HttpClientJsonpModule` for internal use but it does not export them, therefore it should not reset your configuration!

For instance, the current demo uses [ngx-progress](https://github.com/MurhafSousli/ngx-progressbar#for-httpclient-angular--43) where custom `HTTP_INTERCEPTORS` are used to start and end the progress, yet It still works fine with the share buttons.

We need a reproduction for the issue before we try to fix it, can you reproduce the issue using this [stackblitz](https://stackblitz.com/edit/angular-rqwn1j), the library is already loaded.

**Comment by karptonite** [comment]
I'm working on a repro now.

**Comment by karptonite** [comment]
This was a bit involved for stackblitz, but here is a repro:
https://github.com/karptonite/sharebuttons-conflict
Just clone the repro, run `yarn`, then `yarn start`, then load up localhost://4200.

If you click the submodule, you'll see that a book title is not loaded in the submodule, because the necessary interceptor is not run. If you remove the import of `ShareButtonsModule` from `submodule.module.ts`, you'll see that that fixes the bug.

Regarding only importing for internal use, I don't believe that is what happens when you import modules that have providers--providers are all global, so if you re-provide for `HttpClient` (which is, I think, what `HttpClientModule` does, than the module that imports your module will use that provider.

**Comment by karptonite** [comment]
Thinking about this further, if you want to be able to use HttpClient without any interference with anything outside of the package, and vice versa, you might need your own provider that isolates your version of `HttpClient` from the rest of the app, possibly by using its own namespace. I don't know how you'd go about that--I doubt it would be trivial.

**Comment by karptonite** [comment]
I don't think this is necessarily the best way to handle this, but you might take a look at this:
https://github.com/ngx-translate/http-loader

**Comment by MurhafSousli** [comment]
@karptonite I am checking it now

**Comment by MurhafSousli** [comment]
@karptonite 
Don't name your custom http module as [CoreModule](https://github.com/karptonite/sharebuttons-conflict/blob/master/src/app/core/core.module.ts). instead, rename it to **CustomHttpModule**
then, in your lazy module just add your **CustomHttpModule**

In your [lazy module](https://github.com/karptonite/sharebuttons-conflict/blob/master/src/app/submodule/submodule.module.ts)
```ts
@NgModule({
  // If you remove ShareButtonsModule in the imports here, the http
  // request works
  imports: [
    CommonModule, 
    RouterModule.forChild(routes), 
    CustomHttpModule,     // <= Add your custom http module
    ShareButtonsModule
  ],
  // ...
```
Problem solved!

**Comment by naveedahmed1** [comment]
The issue still persists, this approach results in multiple instances of the HttpClient. I think it can only be resolved if you make this plugin independent of HttpClient i.e. neither import HttpClientModule nor add HttpClient to providers list in your plugin. In documentation ask users to import HttpModule in their root module.

**Comment by karptonite** [comment]
@naveedahmed1 @MurhafSousli Yes, I think this issue should be reopened. Importing HttpClientModule in each lazy loaded module is contrary to its intended use, and not an appropriate solution to this problem. See https://angular.io/guide/http#setup-installing-the-module

This is something that you can solve by having the user pass a HttpClient instance as done here, https://github.com/ngx-translate/http-loader, or find a way to create inject an isolated instance of HttpClient with its own InjectionToken (I think that would be preferable).

**Comment by MurhafSousli** [comment]
@karptonite @naveedahmed1 Alright, but I need some time to investigate about this

**Comment by naveedahmed1** [comment]
@MurhafSousli I hope you are doing well, do you have any update to share?

**Comment by MurhafSousli** [comment]
@naveedahmed1 probably next week

**Comment by naveedahmed1** [comment]
Sounds great 😊

**Comment by naveedahmed1** [comment]
Meanwhile I have gone through the code, and I think we can safely remove the HttpClientModule import for this plugin. Whats your conclusion @MurhafSousli ?

**Comment by MurhafSousli** [comment]
@naveedahmed1 Alright, let's remove it

**Comment by naveedahmed1** [comment]
Awesome!

**Comment by karptonite** [comment]
That doesn't entirely solve the problem. `HttpClientJsonpModule` will now be adding an interceptor to the main application's HttpClient, unless you remove that as well.

**Comment by naveedahmed1** [comment]
Yes you are right, I would suggest removing that as well, BTW can't we remove the dependency on HttpClientJsonpModule ?

**Comment by karptonite** [comment]
Even without HttpClientJsonpModule, it is not ideal, since if the main application has interceptors, the requests from ngx-sharebuttons will pass through those interceptors, but it is _much_ better to have that than to interfere with the main application.

**Comment by naveedahmed1** [comment]
But normally with interceptors, when we have to perform some additional processing on request/response we should check if the request is being sent to our own server or to some external server. For example if we are appending jwt token, we should make sure its not going to a third part server. (I assume this was your concern).

**Comment by karptonite** [comment]
Yeah, of course that is how we should write interceptors. I'm just saying that having a user's interceptors breaking the package (if they are not well written, or do something unexpected) could be a confusing source of bugs. But again, much better than messing with the interceptors themselves.

**Comment by naveedahmed1** [comment]
Agreed!

**Comment by MurhafSousli** [comment]
@karptonite `HttpClientModule` is removed now
@naveedahmed1 `HttpClientJsonpModule` became optional, if you don't need linked and tumblr count
```
HttpClientModule, // required
HttpClientJsonpModule, // optional
ShareButtonsModule.forRoot()
```

**Comment by karptonite** [comment]
Thanks! A definite improvement!

**Comment by naveedahmed1** [comment]
Great! Thank you so much @MurhafSousli  :)

**Comment by naveedahmed1** [comment]
I think this issue which was fixed in 4.1.0, now appears again in 6.0.0. @MurhafSousli can you please take a look?

**Comment by MurhafSousli** [comment]
@naveedahmed1 The code has not changed! the plugin does not import the `HttpClientModule` at all
https://github.com/MurhafSousli/ngx-sharebuttons/blob/27ce548b41bea0f7b2800a6faf347ef935684efc/projects/core/src/lib/share.module.ts#L13-L22

**Comment by MurhafSousli** [comment]
That's right! I opened an issue for this #297

**Comment by naveedahmed1** [comment]
Awesome, thanks, I hope this can be fixed soon :)

**Comment by naveedahmed1** [comment]
Fixed, this was real quick , great job bro!
