### ISSUE TITLE
Font awesome import suggestion

### ISSUE THREAD

**Issue by naveedahmed1** [MurhafSousli/ngx-sharebuttons#175]
**I'm submitting a ...**  (check one with "x")
```
[ x] feature request
```

I think this plugin automatically imports `font-awesome` from `https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css`

I think it would be better if user is asked to import font awesome in their index.html.

This would be helpful for the cases where user is already using font-awesome but serving it through a different cdn or server. This will prevent duplicate copies of the font awesome to be downloaded on client.

**Comment by MurhafSousli** [comment]
@naveedahmed1 No, the library does not include it automatically, the user should include it manually
