### ISSUE TITLE
Ionic 3 Framework: Sass Error:  File to import not found or unreadable: ~ngx-sharebuttons/styles/share-buttons. Parent style sheet: project/src/theme/variables.scss

### ISSUE THREAD

**Issue by saiy2k** [MurhafSousli/ngx-sharebuttons#177]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search for a similar issue before submitting
[ ] feature request
[ ] question
```

### Versions
cli packages: (/home/saiy2k/.npm-global/lib/node_modules)
    @ionic/cli-utils  : 1.13.1
    ionic (Ionic CLI) : 3.13.2
local packages:
    @ionic/app-scripts : 3.0.0
    Ionic Framework    : ionic-angular 3.7.1
System:
    Node : v6.11.3
    npm  : 5.5.1 
    OS   : Linux 4.10
Angular Version:
        "@angular/animations": "^4.4.5",
        "@angular/common": "4.4.3",
        "@angular/compiler": "4.4.3",
        "@angular/compiler-cli": "4.4.3",
        "@angular/core": "4.4.3",
        "@angular/forms": "4.4.3",
        "@angular/http": "^4.4.3",
        "@angular/platform-browser": "4.4.3",
        "@angular/platform-browser-dynamic": "4.4.3",
        "@ionic/storage": "^2.0.1",

### Repro steps
I followed instructions in `Getting started` and sharing is working good, except for 1 thing. The styles are not getting applied. I always get this error, when I try to import the style:

`File to import not found or unreadable: ~ngx-sharebuttons/styles/share-buttons. Parent style sheet: /home/saiy2k/projects/ionic/g3/src/theme/variables.scss`
![share issue](https://user-images.githubusercontent.com/701985/31883437-8a2b791e-b807-11e7-9412-bbaba7f98f01.png)

Same happens when I put the import code in src/app/app.scss rather than src/theme/variables.scss

### The log given by the failure

Sass Error
File to import not found or unreadable: ~ngx-sharebuttons/styles/share-buttons. Parent style sheet: /home/saiy2k/projects/ionic/g3/src/theme/variables.scss

**Comment by MurhafSousli** [comment]
Hi @saiy2k, I just tested it with an ionic project, Ionic doesn't seem to support `~`, to fix this simply import the styles explicitly from `node_modules`

in **app.scss**
```scss
@import '../../node_modules/ngx-sharebuttons/styles/share-buttons.scss';
@import '../../node_modules/ngx-sharebuttons/styles/themes/default/default-theme.scss';
```

**Comment by saiy2k** [comment]
Thanks. It worked :-)

**Comment by shariajoe** [comment]
Really struggling to have this up on ionic three with lazyloaded pages read the FAQS but still finding it difficult. Kindly assist

**Comment by shariajoe** [comment]
Also getting this error:
ERROR TypeError: Cannot read property 'toLowerCase' of undefined
    at ShareButtonsService.createShareButton (ngx-sharebuttons.es5.js:963)
    at ShareButtonDirective.set [as createButton] (ngx-sharebuttons.es5.js:1151)
    at updateProp (core.js:12343)
    at checkAndUpdateDirectiveInline (core.js:12052)
    at checkAndUpdateNodeInline (core.js:13597)
    at checkAndUpdateNode (core.js:13540)
    at debugCheckAndUpdateNode (core.js:14412)
    at debugCheckDirectivesFn (core.js:14353)
    at Object.eval [as updateDirectives] (ProductPage.html:329)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:14338)

**Comment by MurhafSousli** [comment]
@shariajoe The error you are getting is not related to this issue.
Please open a new issue and add all information needed including the code you use to import the plugin
But before that, I suggest you check this [stackblitz](https://stackblitz.com/edit/ngx-sharebuttons) that shows how to use in lazy module

**Comment by shariajoe** [comment]
Thank you so much the link you helped solve all my issues. Much appreciated
