### ISSUE TITLE
Add email button

### ISSUE THREAD

**Issue by MurhafSousli** [MurhafSousli/ngx-sharebuttons#18]

**Comment by Gagaro** [comment]
Hi, any reason you ended up not doing this?

Cheers

**Comment by MurhafSousli** [comment]
@Gagaro honestly no one had asked for it

**Comment by Gagaro** [comment]
Thanks for the quick response :+1: . I'm not sure we will need it either, just wanted to know if you were not willing to have this.

**Comment by raDiesle** [comment]
I would request for it & would love it!
Thanks for the tool, @MurhafSousli !

**Comment by ben-crowhurst** [comment]
+1 Very keen on this feature.
