### ISSUE TITLE
CSS Error

### ISSUE THREAD

**Issue by Jay-PC** [MurhafSousli/ngx-sharebuttons#183]
**I'm submitting aa (check one with "x")
```
[X] bug report => search for a similar issue before submitting
[ ] feature request
[ ] question
```

### Versions 
@angular/cli: 1.2.6
node: 6.11.1
os: win32 x64
@angular/animations: 4.4.6
@angular/cdk: 2.0.0-beta.12-65d3630
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/material: 2.0.0-beta.12-65d3630
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/router: 4.4.6
@angular/cli: 1.2.6
@angular/compiler-cli: 4.4.6
@angular/language-service: 4.4.6
### Repro steps

Followed your directions for npm for ShareDirectiveModule. At the point where I import into the CSS the following...
@import "~ngx-sharebuttons/styles/share-buttons";
@import "~ngx-sharebuttons/styles/themes/circles/circles-theme

I get an error when I mouse over the "@import" in VSC... 
[css] at-rule unknown

I added the ".css" to the end of both paths...but it didn't seem to help, although other paths in my style.css do list the .css at the end.

My HTML is the following...

      <button md-fab shareButton="facebook" [style.backgroundColor]="share.meta.facebook.color">
          <i [class]="share.meta.facebook.icon"></i>
      </button>

but I get a hyphen instead of an icon...

### The log given by the failure

In the browser, I get... ERROR TypeError: _co.share is undefined

**Comment by MurhafSousli** [comment]
@Jay-PC The CSS has nothing to do with the share directive, it only applies on the components.

For `share is undefined` error, Did you add the share service in your component constructor?
```html
<button md-fab shareButton="facebook" [style.backgroundColor]="share.meta.facebook.color">
      <i [class]="share.meta.facebook.icon"></i>
  </button>
```
```ts
constructor(public share: ShareButtonsService) { 
}
```
