### ISSUE TITLE
4.1.3 Update Metadata Issue

### ISSUE THREAD

**Issue by bricktownseo** [MurhafSousli/ngx-sharebuttons#185]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search for a similar issue before submitting
[ ] feature request
[ ] question
```

### Repro steps
We included your code through npm install and it pulled in version 4.1.3
When gulp build runs it generates a metadata file with version number "4" while version 4.1.2 generates a version number of "3". When including in an angular project, ng serve fails to compile and run because of a metadata version mismatch. I am happy to provide more details if needed!

**Comment by MurhafSousli** [comment]
Hi @bricktownseo, Yes, can you collaborate on explaining more! what does the error say? and which build setup are you using?

**Comment by MurhafSousli** [comment]
@bricktownseo I still didn't get the issue! Does it still exist in **v4.1.4**?

**Comment by pavlovicnemanja** [comment]
I guess this is similar issue, I'm getting this error on `ng build --prod`
```ERROR in Error: Metadata version mismatch for module C..node_modules/ngx-sharebuttons/ngx-sharebuttons.d.ts, found version 4, expected 3
```

**Comment by ericktatsui** [comment]
I'm using the version 4.1.4 and it still happens.
If I change the version in the ngx-sharebuttons.metadata.json file from 4 to 3, it works.

**The error is:**
`ERROR in Error: Metadata version mismatch for module {{my_app_path}}/node_modules/ngx-sharebuttons/ngx-sharebuttons.d.ts, found version 4, expected 3, resolving symbol SharedModule in {{my_app_path}}/src/app/shared/shared.module.ts, resolving symbol SharedModule in {{my_app_path}}/src/app/shared/shared.module.ts, resolving symbol SharedModule in{{my_app_path}}/src/app/shared/shared.module.ts
    at syntaxError ({{my_app_path}}/node_modules/@angular/compiler/bundles/compiler.umd.js:1729:34)
    at simplifyInContext ({{my_app_path}}/node_modules/@angular/compiler/bundles/compiler.umd.js:25111:23)
    at StaticReflector.simplify ({{my_app_path}}/node_modules/@angular/compiler/bundles/compiler.umd.js:25123:13)
    at StaticReflector.annotations ({{my_app_path}}/node_modules/@angular/compiler/bundles/compiler.umd.js:24553:41)
    at _getNgModuleMetadata ({{my_app_path}}/node_modules/@angular/compiler-cli/src/ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule ({{my_app_path}}/node_modules/@angular/compiler-cli/src/ngtools_impl.js:109:26)
    at {{my_app_path}}/node_modules/@angular/compiler-cli/src/ngtools_impl.js:129:27
    at Array.reduce (<anonymous>)
    at _extractLazyRoutesFromStaticModule ({{my_app_path}}/node_modules/@angular/compiler-cli/src/ngtools_impl.js:128:10)
    at Object.listLazyRoutesOfModule ({{my_app_path}}/node_modules/@angular/compiler-cli/src/ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes ({{my_app_path}}/node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools ({{my_app_path}}/node_modules/@ngtools/webpack/src/plugin.js:207:44)
    at _donePromise.Promise.resolve.then.then.then.then.then ({{my_app_path}}/node_modules/@ngtools/webpack/src/plugin.js:443:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`


**Take a look at my package.json:**
`{
  "name": "dft-core-client-webapp",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "json-server": "json-server json-server/db.json --watch",
    "start": "ng serve",
    "build": "ng build --base-href ./",
    "test": "ng test --watch=false",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "build-prod": "ng build --aot -prod --base-href ./",
    "build-dev": "ng build --aot --base-href ./"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.4.3",
    "@angular/common": "^4.4.3",
    "@angular/compiler": "^4.4.3",
    "@angular/core": "^4.4.3",
    "@angular/forms": "^4.4.3",
    "@angular/http": "^4.4.3",
    "@angular/platform-browser": "^4.4.3",
    "@angular/platform-browser-dynamic": "^4.4.3",
    "@angular/router": "^4.4.3",
    "@types/lodash-es": "^4.14.6",
    "@types/moment": "^2.13.0",
    "angular2-materialize": "^15.1.9",
    "angular2-simple-countdown": "0.0.6",
    "angular2-text-mask": "^8.0.4",
    "chart.js": "^2.7.0",
    "core-js": "^2.5.1",
    "fastclick": "^1.0.6",
    "hammerjs": "^2.0.8",
    "http-serve": "^1.0.1",
    "ionicons": "^3.0.0",
    "jquery": "^3.2.1",
    "lodash": "^4.17.4",
    "lodash-es": "^4.17.4",
    "materialize-css": "^0.98.2",
    "moment": "^2.19.1",
    "moment-timezone": "^0.5.13",
    "ng-inline-svg": "^3.4.0",
    "ng2-charts": "^1.6.0",
    "ngx-auto-unsubscribe": "^1.0.2",
    "ngx-infinite-scroll": "^0.5.1",
    "ngx-sharebuttons": "^4.1.4",
    "ngx-webstorage": "^1.8.0",
    "normalizr": "^3.2.3",
    "raven-js": "^3.17.0",
    "rxjs": "^5.4.3",
    "zone.js": "https://github.com/angular/zone.js.git#d4e5ae8f6e72f0b4ef8e816e369530b72e582ba7"
  },
  "devDependencies": {
    "@angular/cli": "^1.4.2",
    "@angular/compiler-cli": "^4.4.3",
    "@angular/language-service": "^4.4.3",
    "@types/jasmine": "2.5.53",
    "@types/lodash": "^4.14.74",
    "@types/node": "^8.0.28",
    "codelyzer": "~3.1.2",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "^1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "node-sass": "^4.5.3",
    "protractor": "~5.1.2",
    "ts-node": "~3.3.0",
    "tslint": "~5.5.0",
    "tslint-config-airbnb": "^5.3.0",
    "tslint-config-prettier": "^1.5.0",
    "typescript": "~2.4.2"
  }
}`

**Comment by MurhafSousli** [comment]
@pavlovicnemanja what angular version are you using?
@ericktatsui upgrade to ng 5

**Comment by nilasissen** [comment]
having same issue 'ERROR in Metadata version mismatch for module /frontend/node_modules/ngx-sharebuttons/ngx-sharebuttons.d.ts, found version 4, expected 3, resolving symbol AppModule in s'
   "ngx-sharebuttons": "^4.1.4",

**Comment by pavlovicnemanja** [comment]
@MurhafSousli Angular 4

**Comment by bergergit** [comment]
I was having the same error, and using Angular 4 with Ionic.
To fix that, I've upgraded to Angular 5.

I've created a new project (ionic start newproject), and replaced my current package.json with the new package versions of the new package.json of newproject.

For reference to whoever is using Ionic:
```
{
  "name": "testupdate",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "5.0.1",
    "@angular/compiler": "5.0.1",
    "@angular/compiler-cli": "5.0.1",
    "@angular/core": "5.0.1",
    "@angular/forms": "5.0.1",
    "@angular/http": "5.0.1",
    "@angular/platform-browser": "5.0.1",
    "@angular/platform-browser-dynamic": "5.0.1",
    "@ionic-native/core": "4.4.0",
    "@ionic-native/splash-screen": "4.4.0",
    "@ionic-native/status-bar": "4.4.0",
    "@ionic/storage": "2.1.3",
    "ionic-angular": "3.9.2",
    "ionicons": "3.0.0",
    "rxjs": "5.5.2",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.1.2",
    "typescript": "2.4.2"
  },
  "description": "An Ionic project"
}

```

**Comment by nilasissen** [comment]
@bergergit my project is in production mode sudden update is not feasible . @MurhafSousli  any idea to resolve it other thn updating to 5 ?

**Comment by Manaskumar119** [comment]
stuck with same error 
 @bricktownseo  @bricktownseo @bergergit @pavlovicnemanja @ericktatsui @nilasissen  ..
Any one
Please help
