### ISSUE TITLE
Custom buttons

### ISSUE THREAD

**Issue by TomK32** [MurhafSousli/ngx-sharebuttons#187]
What's the best approach for a custom button that's not facebook, linkedin etc.?

There's only a few places like `ShareButtonsService` that have the buttons hardcoded and if those are replaced with something like `registerButton` then buttons with different actions would be possible.

I workaround by using the same tags and css classes, but that's of course not ideal.

**Comment by MurhafSousli** [comment]
@TomK32 I didn't understand, what do you mean by
 > a custom button that's not facebook, linkedin etc.

What are you trying to accomplish?

**Comment by TomK32** [comment]
I just want to add another button for another social website that's not in the sharebuttons yet.

**Comment by FelixKre** [comment]
Hi. It would be nice If you could add a "Xing" share button. Its the largest german business network.

**Comment by MurhafSousli** [comment]
@TomK32 Currently buttons implementation is hard-coded, each button has its own class and parameters, do you have a dynamic design in mind?

**Comment by FelixKre** [comment]
Do you mean a specific theme like I can choose from the "lab" on the ngx share button page? Otherwise, I would prefer the standard one https://dev.xing.com/plugins/share_button

**Comment by MurhafSousli** [comment]
@FelixKre No, this is not related to themes, but It needs a pull request to add Xing button. or at least the sharer link information like the ones defined [here](https://github.com/MurhafSousli/ngx-sharebuttons/blob/master/src/classes/index.ts)

**Comment by MurhafSousli** [comment]
@TomK32 In version 5 you can add custom button, let's say add xing button
```ts
import { ShareButtons, noneOperator } from '@ngx-share/core';

  constructor(private share: ShareButtons) {
    this.share.registerButton('xing', {
      type: 'xing',
      text: 'Xing',
      icon: 'fa fa-xing',
      share: {
        desktop: 'sharerURLForXing',  // the sharer link used to share on xing
        android: 'sharerURLForXing',  // the sharer link used to share on xing
        ios: 'sharerURLForXing',      // the sharer link used to share on xing
        operators: [noneOperator]
      }
    });
  }
```
