### ISSUE TITLE
(feat): Send with Outlook

### ISSUE THREAD

**Issue by choopage** [MurhafSousli/ngx-sharebuttons#189]
**I'm submitting a ...**
```
[x] feature request
```

### Versions
```
@angular/cdk: 5.0.0-rc0
@angular/cli: 1.5.0
@angular/material: 5.0.0-rc0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.0
typescript: 2.5.3
webpack: 3.8.1
```

### Details 
Like how Wave Accounting app. **Send with Outlook**
![screen shot 2017-11-22 at 10 55 47 am](https://user-images.githubusercontent.com/6467136/33107790-c87aa25c-cf73-11e7-8f70-e23f79ca544e.png)

**Comment by MurhafSousli** [comment]
Will not do, the email button is sufficient for this plugin
