### ISSUE TITLE
Weird css behaviour

### ISSUE THREAD

**Issue by AlexLomm** [MurhafSousli/ngx-sharebuttons#193]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search for a similar issue before submitting
[ ] feature request
[ ] question
```

### Versions
Angular CLI: 1.5.5
Node: 6.10.0
Npm: 5.5.1
OS: darwin x64
Angular: 5.0.3
typescript: 2.4.2
webpack: 3.8.1
ngx-sharebuttons: 4.1.4

### Repro steps
When accessing a blog article via a **direct url**, the share buttons appear like this:
![screen shot 2017-11-30 at 10 54 16 am](https://user-images.githubusercontent.com/11467210/33418024-4e86018a-d5bd-11e7-9de5-a417d4a635a3.png)
As you see, their style is broken. However, if I navigate into the article **by clicking on a link** (initiating the angular router), they appear as they should:
![screen shot 2017-11-30 at 10 55 34 am](https://user-images.githubusercontent.com/11467210/33418066-8f5bcf82-d5bd-11e7-9cad-262ebcdbbdb5.png)

### The log given by the failure
No failure logs

**Comment by volvotrax** [comment]
Some CSS classes are overridden.
e.g. a padding is added to the right:
```
.sb-default .sb-wrapper.sb-show-icon.sb-show-template .sb-template {
    padding-right: 1em;
    padding-left: 0;
}
```

I found this workaround:
```
/* your css file */
.sb-icon {
  width: 100% !important;
}
.sb-template {
  padding: 0px !important;
}
```
Don't forget to change view encapsulation type:

```
/* yourcomponent.ts */
@Component({
...
  encapsulation: ViewEncapsulation.None
})

```

**Comment by AlexLomm** [comment]
Thank you @volvotrax. I'm already aware how to fix the issue, however it seems really weird to me. Why is the css affected in the first place? And why does triggering the router fix it?

**Comment by MurhafSousli** [comment]
This is weird! is it happening in all browsers or on a specific one? 

This padding is added when `sb-show-template` is active, which should not unless you are using a custom text or template such as
```html
<share-button>custom text</share-button>
```
Have a look at the [template code](https://github.com/MurhafSousli/ngx-sharebuttons/blob/master/src/components/share-button/share-button.component.html)
```html
<div #template class="sb-template">
   <ng-content></ng-content>
</div>
```
`sb-template` style is triggered when `[class.sb-show-template]="template.innerText?.length"`

@AlexLomm Can you reproduce this issue with this https://stackblitz.com/edit/ngx-sharebuttons

**Comment by AlexLomm** [comment]
Thanks for replying. 

It was happening in chrome (haven't tested in other browsers). I fixed it by enabling the share-buttons element in `ngAfterViewInit()`.

I'm not able to reproduce the problem on stackblitz, must be something on my end.
