### ISSUE TITLE
Custom icon

### ISSUE THREAD

**Issue by dgpoo** [MurhafSousli/ngx-sharebuttons#194]
Hello,
i want to use custom images for social share instead of default icons.how can i overide it
Thank you

**Comment by MurhafSousli** [comment]
Hi @dgpoo 

Use the share directive
```html
<button class="custom-button" shareButton="pinterest">
   <img src="custom-icon.png"/>
</button>
```
Or use share button component and add your custom elements inside the button
```html
<share-button button="twitter">
   <!-- CONTENT HERE WILL REPLACE THE ORIGINAL ICON AND TEXT -->
   <img src="custom-icon.png"/>
   <span>Tweet!</span>
</share-button>
```

**Comment by dgpoo** [comment]
Hello @MurhafSousli ,
Thank you for reply and giving solution i will check it.

**Comment by jackweldon** [comment]
Is it possible to use a custom icon or a different font awesome icon for the ellipses share icon?

**Comment by MurhafSousli** [comment]
@jackweldon Yes
```ts
import { faFacebookSquare, faTwitterSquare } from '@fortawesome/free-brands-svg-icons';

export class AppComponent {

  constructor(private shareButton: ShareButtons) {
   
    shareButton.setConfig({
      prop: {
        facebook: {
          icon: faFacebookSquare
        },
        twitter: {
          icon: faTwitterSquare
        }
      }
    });
  }
}
```

**Comment by jackweldon** [comment]
@MurhafSousli thanks for the response, I don't mean the social icons, but the 'see more ellipsis'

![image](https://user-images.githubusercontent.com/9987934/41363206-43557e0a-6f2b-11e8-900f-1b79852218b8.png)

**Comment by MurhafSousli** [comment]
@jackweldon you can not change this one, it is hardcoded

**Comment by jackweldon** [comment]
@MurhafSousli could it be included in the future?

**Comment by MurhafSousli** [comment]
@jackweldon Yes, it will
