### ISSUE TITLE
Copy button feedback

### ISSUE THREAD

**Issue by thatisuday** [MurhafSousli/ngx-sharebuttons#195]
[ x] bug report => search for a similar issue before submitting
[x ] feature request
[ ] question

When user click copy button, url link is copied to clipboard but no feedback is provided. For normal audience, they don't know what happened.

Is there any possibility that we can show some sort of tooltip with massage, 'link copied to clipboard'?

Also there is no configuration to change icon of 'checkmark'  (fa fa-click) which appears after clicking copy button.

**Comment by MurhafSousli** [comment]
Hi @thatisuday, there is a feedback if you use `[showText]="true"` on the component
you can configure the icon and text for the feedback like this:
```ts
const config = {
  copy: {
    icon: 'fa class',
    text: 'copy',
    successIcon: 'fa class'
    successText: 'copied',
    failIcon: 'fa class'
    failText: 'error',
  },
};

@NgModule({
  imports: [
    HttpClientModule,
    ShareButtonsModule.forRoot({}, config)
  ]
})
```
