### ISSUE TITLE
Facing challenge while implementing v4 

### ISSUE THREAD

**Issue by bbj1980** [MurhafSousli/ngx-sharebuttons#199]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] question
```

### Versions

Node: 6.10.3
OS: win32 x64
Angular: 4.4.6
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic, router
... tsc-wrapped

@angular/cdk: 2.0.0-beta.12
@angular/cli: 1.6.2
@angular/material: 2.0.0-beta.12
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.2
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.2.2
webpack: 3.10.0

### The log given by the failure

ERROR in Error: Metadata version mismatch for module F:/Deliverable-Client/Web V1/Pyd-ICE/node_modules/@ngx-share/core/ngx-share-core.d.ts, found version 4, expected 3, resolving symbol sharedModule in F:/Deliverable-Client/Web V1/Pyd-ICE/src/app/sharedcomponents/shared-routing.module.ts, resolving symbol sharedModule in F:/Deliverable-Client/Web V1/Pyd-ICE/src/app/sharedcomponents/shared-routing.module.ts, resolving symbol sharedModule in F:/Deliverable-Client/Web V1/Pyd-ICE/src/app/sharedcomponents/shared-routing.module.ts
    at Error (native)

**Comment by MurhafSousli** [comment]
For Angular 4 use this https://github.com/MurhafSousli/ngx-sharebuttons/wiki
Or upgrade to Angular 5
dup #192 #190
