### ISSUE TITLE
Demo needs updates!

### ISSUE THREAD

**Issue by Tails128** [MurhafSousli/ngx-sharebuttons#201]
### Bug Report or Feature Request (mark with an `x`)

- [x] bug report 
- [ ] feature request
- [ ] question

I've noticed that in some pages (E.G.: [this one](https://murhafsousli.github.io/ngx-sharebuttons/#/share-button-directive) ) still use share.meta instead of share.prop

**Comment by MurhafSousli** [comment]
@Tails128 Right! thanks for reporting

**Comment by MurhafSousli** [comment]
Fixed!
