### ISSUE TITLE
Styles don't applied

### ISSUE THREAD

**Issue by abelardolg** [MurhafSousli/ngx-sharebuttons#202]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?

Windows 7

### Versions

The latest version of Angular-cli and Angular.

### Repro steps

I reproduce your demo from scratch but the buttons aren't showed stylized like yours.
The below picture shows what is the appearance of the buttons at my app:
![image](https://user-images.githubusercontent.com/22522883/34864931-d8706cac-f776-11e7-8278-3847bf5706e7.png)

### The log given by the failure

No logs were generated.

### Desired functionality

The buttons should be stylized as they appear at the demo page. 
Attached to this report my source code can be reviewed. All steps were strictly executed according your instructions.
[src.zip](https://github.com/MurhafSousli/ngx-sharebuttons/files/1625294/src.zip)

### Mention any other details that might be useful

Best regards.

**Comment by MurhafSousli** [comment]
you are using `'modern-dark'` theme but you import the default theme
you need to import the theme that you use, add this in `style.scss`
```css
@import '~@ngx-share/button/styles/themes/modern/modern-dark-theme.css';

// or 

@import '~@ngx-share/button/styles/themes/modern/modern-dark-theme';
```
See this https://stackblitz.com/edit/ngx-sharebuttons

**Comment by m-te** [comment]
> You are using `'modern-dark'` theme but you import the default theme
> you need to import the same theme you use!
> For `css` version
> 
> ```css
> @import '~@ngx-share/button/styles/themes/modern/modern-dark-theme.css';
> ```
> 
> For `scss` version
> 
> ```css
> @import '~@ngx-share/button/styles/themes/modern/modern-dark-theme';
> ```
> 
> See this https://stackblitz.com/edit/ngx-sharebuttons

Hi, I was facing the same problem while trying to apply circles-light theme, but changing the import in your stackblitz to circles-theme don't work, I've seen imports from @ngx-sharebuttons in docs I think and @ngx-share in the stackblitz provided here, so it's bit confusing where to import from and how to apply theme(doing [theme]="'some-theme'" doesn't work, only theme="some-theme" works), it would be great if you could guide as how to get circles-light working, or where should I refer to see which imports I need for a particular theme

Thanks

**Comment by nikhilprasad11** [comment]
Correct Path

@import '~@ngx-share/button/themes/modern/modern-dark-theme';
