### ISSUE TITLE
Error with version number when trying to install plugin (found 4 expecting 3)

### ISSUE THREAD

**Issue by AAniculaesei-modus** [MurhafSousli/ngx-sharebuttons#203]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] question
```

### OS and Version?
macos - Sierra

### Versions
node --version
v6.12.0

npm --version
3.10.10

 "@angular/core": "^4.3.1",

### The log given by the failure
When I try to add the plugin it gives me this error:

` ERROR in Error: Metadata version mismatch for module /Volumes/Work/Projects/node_modules/@ngx-share/buttons/ngx-share-buttons.d.ts, found version 4, expected 3, resolving symbol UserModule in /Volumes/Work/Projects/src/app/modules/user/user.module.ts, resolving symbol UserModule in /Volumes/Work/Projects/src/app/modules/user/user.module.ts, resolving symbol UserModule in /Volumes/Work/Projects/WolfPOC/src/app/modules/user/user.module.ts
`
Can you tell me what am I doing wrong here?

Thank you

**Comment by MurhafSousli** [comment]
dup #192 #190 #199 #200
