### ISSUE TITLE
names of all buttons

### ISSUE THREAD

**Issue by JanvanCasteren** [MurhafSousli/ngx-sharebuttons#207]
I just have simple question:

you write:
Button name, e.g. 'facebook', 'twitter' ...etc.

But what are the names of the other possible buttons?

**Comment by MurhafSousli** [comment]
You right, I should add this to the docs, the buttons are:

- facebook 
- twitter
- google
- linkedin
- pinterest
- reddit
- tumblr
- whatsapp
- telegram
- vk
- stumble _for stumbleUpOn_
- email
- copy
- print

**Comment by JanvanCasteren** [comment]
thank you!
