### ISSUE TITLE
Whatsapp sharing fails on mobile

### ISSUE THREAD

**Issue by sukheja-varun** [MurhafSousli/ngx-sharebuttons#208]
For whatsapp sharing it redirects to web.whatsapp.com which works for desktop but fails in mobile.
Better to redirect to api.whatsapp which will redirect to desktop application on desktop and mobile app when running on mobile browser.

**Comment by MurhafSousli** [comment]
@sukheja-varun Right, I have not get the chance to test all the buttons on mobile. I rely on users feedback.
```js
ShareButtonsModule.forRoot({
  prop: {
    whatsapp: {
      share: {
        ios: 'whatsapp://send?',
        android: 'whatsapp://send?'
      }
    }
  }
})
```
Here is a [stackblitz](https://stackblitz.com/edit/ngx-sharebuttons-gfcxuv?file=app%2Fapp.module.ts)

Try it on your phone: https://ngx-sharebuttons-gfcxuv.stackblitz.io/#/

**Comment by mickaelb1** [comment]
According to the documentation of whatsapp (https://faq.whatsapp.com/en/android/28000012), is need to be: 

```
ShareButtonsModule.forRoot({
  prop: {
    whatsapp: {
      share: {
        ios: 'whatsapp://send?text=',
        android: 'whatsapp://send?text='
      }
    }
  }
})
```

and it's work on my old S4.
but may be, we need to look at another (new) way : by not using whatsapp sheme: 
https://faq.whatsapp.com/en/general/26000030/?category=5245251
