### ISSUE TITLE
Refused to display 'https://twitter.com/intent/tweet' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'".

### ISSUE THREAD

**Issue by rtm** [MurhafSousli/ngx-sharebuttons#209]
I guess I know what is causing this error message, but how would I go about fixing it?

> Refused to display 'https://twitter.com/intent/tweet' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'".

Here's a similar error with Google:

> Refused to display 'https://plus.google.com/share' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

**Comment by MurhafSousli** [comment]
@rtm This is their policy, they do not allow launching the share window in a custom modal or an iframe #1

**Comment by rtm** [comment]
@MurhafSousli  Thanks for the response. But I must be missing something very basic. That basically makes this package unusable? There is reference to using `window.open` instead of an iframe. How do I choose that behavior?
