### ISSUE TITLE
ngx-sharebuttons not taking the updated meta value 

### ISSUE THREAD

**Issue by shashijha** [MurhafSousli/ngx-sharebuttons#210]
I have multiple post on the same page and wanted to share each post and where i am  changing the dynamic value for og:title , og:image, og:description and og:url and it is not taking updated one. taking default value. Could you please help me to resolve this issue.

**Comment by Tatenda** [comment]
Please provide more information on you development environment and also the error you are getting. Preferably structuring your issue according to the given guidelines would have to assist you.

**Comment by shashijha** [comment]
I have used below onclick method on share link to set the meta tag value and showing the all the sharing option (for ex facebook twitter linkedin g+ etc.) 
setMetaTag(post) {
       this.metadataService.setTag('og:title', post.title);
        this.metadataService.setTag('og:image', this.urlLoc + post.image);
        this.metadataService.setTag('og:description', post.description);
        this.metadataService.setTag('og:url', this.urlLoc);
        this.metadataService.setTag('og:type', 'post');
    }
and on click of sharing icon wanted to get the updated meta value. but it is taking default value what i have set initially on the index.html page. 

I tried to use alternate way as mentioned
<share-buttons [url]="url" [title]="title" [description]="description" [image]="img" [defaultStyle]="false"></share-buttons>

[image]="img"    img value is getting truncated
for ex if img value is "http://abc.com/images/xyz.jpg"
but it takes only "http://abc.com/im"

I am not getting any error in both scenario but unable to achieve the result .

**Comment by MurhafSousli** [comment]
@shashijha Are you using universal?

**Comment by shashijha** [comment]
I am not using universal

**Comment by MurhafSousli** [comment]
So you can't change the meta tags dynamically, that is how it works.
Explanation can be found in [ngx-sharebuttons - FAQ](https://murhafsousli.github.io/ngx-sharebuttons/#/faq)
