### ISSUE TITLE
ngx-sharebuttons"' has no exported member 'ShareButtons'

### ISSUE THREAD

**Issue by collinkueter** [MurhafSousli/ngx-sharebuttons#212]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?

macOS High Sierra

### Versions

Angular CLI: 1.6.1
Node: 9.3.0
OS: darwin x64
Angular: 5.1.2
... common, compiler, compiler-cli, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router

@angular/animations: 5.2.1
@angular/cdk: 5.1.0
@angular/cli: 1.6.1
@angular/material: 5.1.0
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.1
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.10.0

### Repro steps

simply trying to import the follow: 
import { ShareButtons } from 'ngx-sharebuttons';

### The log given by the failure

Module '"/Users/{username}/projects/{project_name}/node_modules/ngx-sharebuttons/ngx-sharebuttons"' has no exported member 'ShareButtons'.

### Desired functionality

To be able to import the ShareButtons service.

### Mention any other details that might be useful

The share buttons work but I am not able to use the ShareButtons service because it will not let me import the service.

**Comment by MurhafSousli** [comment]
@collinkueter `import { ShareButtons } from 'ngx-share/core';`

**Comment by collinkueter** [comment]
ngx-share/core modules does not exist.

**Comment by MurhafSousli** [comment]
@collinkueter Sorry '@ngx-share/core'... the same package you installed!
