### ISSUE TITLE
Twitter description not encoded correctly

### ISSUE THREAD

**Issue by LoveMHz** [MurhafSousli/ngx-sharebuttons#213]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report
- [ ] feature request
- [ ] question
```

### OS and Version?

Linux dustin-ws 4.13.0-32-generic #35-Ubuntu SMP Thu Jan 25 09:13:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Versions

Angular CLI: 1.6.4
Node: 6.11.5
OS: linux x64
Angular: 5.2.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

angular/cli: 1.6.4
angular-devkit/build-optimizer: 0.0.38
angular-devkit/core: 0.0.25
angular-devkit/schematics: 0.0.48
ngtools/json-schema: 1.1.0
ngtools/webpack: 1.9.4
schematics/angular: 0.1.13
schematics/schematics: 0.0.13
typescript: 2.5.3
webpack: 3.10.0

"ngx-share/core": "^5.0.0"

### Repro steps

\<a shareButton="twitter" sbUrl="https://example.com" sbDescription="\@LoveMHz \#TestTag test \#Test">Share on Twitter</a>

### The log given by the failure

The Twitter URL gets encoded as "https://twitter.com/intent/tweet?url=https%3A%2F%2Fexample.com&text=@LoveMHz%20#TestTag test #Test"

Which results in the tweet being "@LoveMHz  https://example.com"

### Desired functionality

The text attribute being properly encoded as "%40LoveMHz%20%23TestTag%20test%20%23Test" and for the tweet to read as "\@LoveMHz \#TestTag test \#Test"

**Comment by MurhafSousli** [comment]
As you see the encoded text is correct, but Twitter does not accept hashtags in the text area, there is a tags input where you can define your tags.

**Comment by LoveMHz** [comment]
@MurhafSousli It does appear they support it though. If I manually encode the requested URL then it does appear correctly.

https://twitter.com/intent/tweet?url=https%3A%2F%2Fexample.com&text=%40LoveMHz%20%23TestTag%20test%20%23Test

**Comment by MurhafSousli** [comment]
Ok, then the description needs to be encoded before
here is a workaround until I update 

https://stackblitz.com/edit/ngx-sharebuttons-jaakcs?file=app/app.module.ts
