### ISSUE TITLE
share button click opening the blank page instead of  mobile application after calling a async service

### ISSUE THREAD

**Issue by jamaltheen** [MurhafSousli/ngx-sharebuttons#218]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### Repro steps

html:
```
<li (click)="this.shareUnique('twitter', test)">twitter</li>
 <li type="hidden"  #test [shareButton]="sharevia" [sbUrl]=url [sbTitle]='title' [sbDescription]='description' ></li>
```

typescript:
shareUnique(sharebutton, element) {
 this.globalservice.generalService().subscribe( res => {
     if (res.status === true) {
      this.sharevia = sharebutton;
       this.description = res.SHARE_CONTENT;
         this.title = res.SUBJECT;
        this.url = res.URL;
      element.click();
}
### Desired functionality

open the twitter app or desired mobile application(email, whatsapp) but blank page opened.

**Comment by MurhafSousli** [comment]
@jamaltheen Reproduce it in https://stackblitz.com/edit/ngx-sharebuttons and I will look into it
