### ISSUE TITLE
How to use Font Awesome 5 icons

### ISSUE THREAD

**Issue by qlaffont** [MurhafSousli/ngx-sharebuttons#219]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [X] feature request
- [ ] question
```

### OS and Version?

All

### Versions

Angular CLI: 1.6.4
Node: 8.9.1
OS: win32 x64
Angular: 5.2.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cli: 1.6.4
@angular-devkit/build-optimizer: 0.0.38
@angular-devkit/core: 0.0.25
@angular-devkit/schematics: 0.0.48
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.4
@schematics/angular: 0.1.13
@schematics/schematics: 0.0.13
typescript: 2.4.2
webpack: 3.10.0

### Repro steps

Install last version of font awesome and use share-buttons component.

**Comment by MurhafSousli** [comment]
You can use Font awesome 5, just override icons classes, here is an example

https://stackblitz.com/edit/ngx-sharebuttons-fa5?file=app%2Fapp.module.ts

Will use Font awesome 5 by default in the next update

**Comment by qlaffont** [comment]
Okay Thanks ^^

**Comment by MurhafSousli** [comment]
I will keep this open for now, will close it with the next update
