### ISSUE TITLE
share by mail don't copy url in the body of email

### ISSUE THREAD

**Issue by peppedeka** [MurhafSousli/ngx-sharebuttons#221]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?
All

### Versions
Angular CLI: 1.6.4
Node: 8.9.1
OS: win32 x64
Angular: 5.2.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

: 1.6.4
: 0.0.38
: 0.0.25
: 0.0.48
: 1.1.0
: 1.9.4
: 0.1.13
: 0.0.13
typescript: 2.4.2
webpack: 3.10.0

### Repro steps
Install and use  share-buttons component.

**Comment by MurhafSousli** [comment]
There is no link shared in the email body, it is empty by default!

**Comment by peppedeka** [comment]
Many thanks for response, exist a way to share by email current url?i dont
understand the reason to use sharing via email if i cant share current url

Il giorno lun 26 feb 2018 alle 20:30 Murhaf Sousli <notifications@github.com>
ha scritto:

**Comment by superallumette** [comment]
Hello,
I also have found that the url is not copied to the body by default, which I expected as the default behavior but I was able to add it using description member.
Unfortunately, I am not able to able to populate the subject using the title property, even though it works fine with others social networks. 
Have you experienced the same issue ?

**Comment by peppedeka** [comment]
Hi superallumette,
Yes hi founded same issue, my solution was send mail my window

mailTo() {
window.open('mailto:?subject=Hi&body=' + window.location.href);
}



<button mat-button (click)="mailTo()">
<img src="../../../assets/icon/email_mail_envelope_send_message-128.png"
height="42">
</button>

**Comment by superallumette** [comment]
Hello, it's fine for me to manually add the URL. I'm using a little description already.
But the title is not bound to the corresponding property and I would rather not create my own button just for the email feature :)

**Comment by superallumette** [comment]
Hello @MurhafSousli, can I just know if there is any plan to resolve the issue with the subject not being included ?
As peppedeka said, it would be nice that description include page location by default, but it can be set manually so that is fine.
There is actually no workaround for the subject though.

Thank you for this plugin !

**Comment by MurhafSousli** [comment]
@superallumette it is fixed, update is coming soon
