### ISSUE TITLE
Sharing on native apps status

### ISSUE THREAD

**Issue by MurhafSousli** [MurhafSousli/ngx-sharebuttons#238]
Testing status

❌No Support: Means it is tested but the share dialog opens in the mobile browser

| Button               | 💻 Desktop    | 📱 iPhone         | 📱 Android         |
| ----------------- | --------------- | ----------------  | ----------------- |
| Facebook          | ✔️ Support     | ❌No Support  | ❌No Support  |
| Twitter              | ✔️ Support     | ✔️ Support       | ✔️ Support       |
| Pinterest           | ✔️ Support     | ✔️ Support       | ✔️ Support       |
| Google             | ✔️ Support     | ✔️ Support       | ✔️ Support       |
| LinkedIn           | ✔️ Support     | ✔️ Support       | ✔️ Support       |
| Whatsapp        | ✔️ Support     | ✔️ Support        | ✔️ Support      |
| Telegram         | ✔️ Support     | ✔️ Support        | ✔️ Support       |
| Messenger       | ❌No Support | ✔️ Support      | ✔️ Support       |
| Viber                | ❌No Support | ✔️ Support      | ✔️ Support       |
| VK                    | ✔️ Support     |  ❔ Not tested    | ❔ Not tested    |
| Reddit              | ✔️ Support     | ❌No Support   | ❔ Not tested    |
| Tumblr             | ✔️ Support     | ❌No Support   |  ❔ Not tested   |
| StumbleUpOn  | ✔️ Support     | ❌No Support   | ❔ Not tested   | 
| Xing                  | ✔️ Support     |  ❔ Not tested   |  ❔ Not tested   |
| SMS                 | ✔️ Support      | ✔️ Support      | ✔️ Support       |
| Copy                | ✔️ Support      | ✔️ Support      | ✔️ Support       |
| Print                 | ✔️ Support      | ✔️ Support      | ✔️ Support       |
| Email                | ✔️ Support      | ✔️ Support      | ✔️ Support       |

**Notes:**
Facebook: Does not support sharing on native apps
Tumbler: Opens in native app but then the app opens the browser again

**Comment by parthkharecha** [comment]
@MurhafSousli  any other solution for facebook sharing on native app???

**Comment by MurhafSousli** [comment]
@parthkharecha It seems that Facebook does not support it without the SDK. more [info](https://stackoverflow.com/questions/27347171/facebook-share-from-mobile-web-to-native-app-without-javascript).

**Comment by MurhafSousli** [comment]
Some might help to test them and post their feedback here

**Comment by pulsejet** [comment]
That's fine, but how about *also* having this in the readme? This is valuable info!

**Comment by MurhafSousli** [comment]
will have it there with the next update

**Comment by hinalshah91** [comment]
Hi, if there is app installed, sharing should open the app and if there is no app installed, it should open the web browser. For eg: if whatsapp application is installed, clicking on share button should open the app directly and if there is no app installed it should open https://web.whatsapp.com/. In my case, Sharing on whatsapp or facebook through my website opens the website only. What should I do?

**Comment by agiratech-venkat** [comment]
I want to open the link in Facebook app but not in the browser when I click the link  on mobile, is there any feasible solution to implement this?

**Comment by trunghieulam** [comment]
I think it's better to change the protocol to call a deep link of FB instead: https://stackoverflow.com/a/22335921

**Comment by MurhafSousli** [comment]
@trunghieulam That is a link to a page, it is not a sharer URL, you can override the sharer URL of FB using the global options, this way you can test if it works or not, then let me know if it is better.
