### ISSUE TITLE
Consider new ng Font awesome library & chrome native share

### ISSUE THREAD

**Issue by tomgruszowski** [MurhafSousli/ngx-sharebuttons#252]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X ] feature request
- [ ] question
```
### Desired functionality
What would like to see implemented?
Any thoughts on using this lib with [angular-fontawesome](https://github.com/FortAwesome/angular-fontawesome). I realize it's probably very difficult to support both the classic font based and this one but the new library is tree shakable + SVG and seems to work very nice, there is very little justification in using the old font based icons once you go down this route.

Also, [Chrome native Share](https://developers.google.com/web/updates/2016/09/navigator-share)

Thanks for an awesome lib.

**Comment by MurhafSousli** [comment]
@tomgruszowski thanks!
When I tried that [angular-fontawesome](https://github.com/FortAwesome/angular-fontawesome), it wasn't stable at that time. I will give it another shot.

I like the chrome navigator share, it is very interesting! but I don't think we can make use of it with this plugin. It doesn't show share buttons, and it isn't cross-browser. it only allows sharing on the installed native apps.

**Comment by tomgruszowski** [comment]
It seems to work well, they recently did a major refactor and renamed a few of the packages. Also can you up your TS version to 2.7 to align it with the soon to be released (any day) Angular 6? There is a slight build issue with pipes and spread operator when using newer TS.

Side note, I noticed you have a copy of the files in the app and lib. Not sure you're aware of how ng-packagr reference app does this but it's not necessary, have a peak at [ng-packaged](https://github.com/dherges/ng-packaged).

I'm going to take a quick stab at integrating angular-fontawesome lib, if I can make it generic enough I'll send you a pull. I think using this as your default solution is best as it doesn't prevent someone from using the classic font files along with this but not many people would do it the other way around; to include font libraries for a dozen icons.

**Comment by MurhafSousli** [comment]
@tomgruszowski I have updated it with angular-fontawesome, it is much better now, I will first publish the update for version 5, then to Angular 6.

The reason demo has a separate copy is to make it possible to edit the source code directly through the Github stackblitz feature. also ng-packagr doesn't seem to support watching while development!

The new version is almost done. currently, I am trying to solve some solve some issues related to Universal

**Comment by tomgruszowski** [comment]
Impressive solution to address this.
