### ISSUE TITLE
Error with build

### ISSUE THREAD

**Issue by Amos47** [MurhafSousli/ngx-sharebuttons#254]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version
Happening mainly on Circle CI's `circleci/node:boron-browsers` image

### Versions
```
Angular CLI: 1.6.4
Node: 8.9.4
OS: darwin x64
Angular: 5.2.0
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

@angular/cli: 1.6.4
@angular/tsc-wrapped: 5.0.0-beta.7
@angular-devkit/build-optimizer: 0.0.38
@angular-devkit/core: 0.0.25
@angular-devkit/schematics: 0.0.48
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.4
@schematics/angular: 0.1.13
@schematics/schematics: 0.0.13
typescript: 2.4.2
webpack: 3.10.0
```

### Repro steps
Not sure. This is a production app with a lot of things going on.
I ran into trouble when updating to the newest version and have been running into trouble just trying to downgrade.
The problem mainly occurs during the build step. It seems like there's some dependency errors as well as an additional syntax issue.

### The log given by the failure
```
ERROR in ./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--8-3!./src/styles.scss
Module build failed: 
  --button-color: $sb-more !important;

                ^
      Invalid CSS after "...color: $sb-more": expected "}", was "!important;"
      in /home/circleci/web-2/node_modules/@ngx-share/button/styles/share-buttons.scss (line 103, column 18)
ERROR in ./node_modules/@ngx-share/button/esm5/ngx-share-button.js
Module not found: Error: Can't resolve '@fortawesome/angular-fontawesome' in '/home/circleci/web-2/node_modules/@ngx-share/button/esm5'
```

**Comment by MurhafSousli** [comment]
@Amos47 It could be your CLI version and the CSS variable, try to update to the latest version

**Comment by tomgruszowski** [comment]
@MurhafSousli I'm on latest CLI, this didn't happen yesterday :)

**Comment by MurhafSousli** [comment]
Can you reproduce it?

**Comment by tomgruszowski** [comment]
Yes, both in my project and a clean checkout of this repo. I even diffed your lib styles with the app ones, no issue there ... looks like you had --#{$button}-color: $color; (with a hash) and no just the CSS var.

**Comment by tomgruszowski** [comment]
Shouldn't --button-color be on the right side of the colon? It's not an issue with CSS vars, but commenting out this line fixes build, I'm not sure what the intent of this change was, its the only instance of this var being on leftside of colon.

**Comment by MurhafSousli** [comment]
@tomgruszowski the last update didn't change the variables file! It just adds a new variable for the SMS button.

How is this [github stackblitz](https://stackblitz.com/github/murhafsousli/ngx-sharebuttons) working!

![image](https://user-images.githubusercontent.com/8130692/38451346-c034f7f4-3a36-11e8-913e-d18cd851006e.png)

**Comment by tomgruszowski** [comment]
![image](https://user-images.githubusercontent.com/1247564/38451383-393015e4-39ec-11e8-9ca4-856b1330b458.png)

:) this is the issue ...

**Comment by MurhafSousli** [comment]
@tomgruszowski Yes that change was because each button's "--button-color" is set by the share directive (This makes theming more dynamic, users don't have to use css to change button colors), however the more button "expand". is not a share button, so its `--button-color` is not set, therefore I had to hardcode it for that particler class.

**Comment by bjornharvold** [comment]
Same issue here. Updated to latest version of Share buttons get error:

```
ERROR in ./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--8-3!./src/styles.scss
Module build failed: 
  --button-color: $sb-more !important;
                ^
      Invalid CSS after "...color: $sb-more": expected "}", was "!important;"
      in /Users/crash/git/test/node_modules/@ngx-share/button/styles/share-buttons.scss (line 103, column 18)
```

**Comment by MurhafSousli** [comment]
@bjornharvold what is the postcss version? I have
```
"postcss": "^6.0.17"
```

**Comment by tomgruszowski** [comment]
@MurhafSousli same version here

**Comment by bjornharvold** [comment]
"version": "6.0.21"
