### ISSUE TITLE
Does not support Font Awesome Pro

### ISSUE THREAD

**Issue by bjornharvold** [MurhafSousli/ngx-sharebuttons#260]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?
High Sierra

### Versions
```
Angular CLI: 1.7.4
Node: 9.4.0
OS: darwin x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

@angular/cli: 1.7.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.6.2
webpack: 3.11.0
```

### Repro steps
Include the Font Awesome 5 Pro module and build to prod

### The log given by the failure
```
ERROR in ./node_modules/@ngx-share/buttons/esm5/ngx-share-buttons.js
Module not found: Error: Can't resolve '@fortawesome/free-solid-svg-icons' in '/Users/crash/git/travelkoin/travelkoin-consumer/node_modules/@ngx-share/buttons/esm5'
ERROR in ./node_modules/@ngx-share/core/esm5/ngx-share-core.js
Module not found: Error: Can't resolve '@fortawesome/free-solid-svg-icons' in '/Users/crash/git/travelkoin/travelkoin-consumer/node_modules/@ngx-share/core/esm5'
```

### Mention any other details that might be useful
This is related to issue 259 as I cannot override free icons with pro icons

**Comment by MurhafSousli** [comment]
@bjornharvold 
The plugin uses [angular-fontawesome](https://github.com/FortAwesome/angular-fontawesome) for the icons, so to import the pro icons follow the instruction in [angular-fontawesome]

You still need to install `@fortawesome/free-solid-svg-icons` and `@fortawesome/free-solid-svg-icons` as they are the default icons. Then you can override them with the pro icons

**Comment by bjornharvold** [comment]
Ah - import both libraries. Gotcha! Thank you
