### ISSUE TITLE
Can't implement styles.

### ISSUE THREAD

**Issue by sarath3940** [MurhafSousli/ngx-sharebuttons#262]
Hi, you mentioned that the styles package should be implemented in global style "app/src/style.scss". But, I'm working on angular 5. So, I can't find any .scss file. I tried to implement in "app/src/style.css", I'm facing with the error as shown in the picture. And I want to implement your styles. How can I achieve that. I'm a beginner and doing my own project. Don't mind if the issue is too basic....
![error](https://user-images.githubusercontent.com/37688535/38618411-30937b50-3db7-11e8-8a33-1e2ccf3bddc4.png)

**Comment by MurhafSousli** [comment]
@sarath3940 It seems that you created the app for CSS instead of SCSS.
You can still import the CSS themes, just add `.css` at the end of the styles you import
```css
@import '~@ngx-share/button/styles/share-buttons.css';
@import '~@ngx-share/button/styles/themes/default/default-theme.css';
```
