### ISSUE TITLE
[url] is not working when the url is bigger

### ISSUE THREAD

**Issue by PaulCheriyan009** [MurhafSousli/ngx-sharebuttons#266]
### [url] is not working when the url added is is bigger
``` 
for example 
<share-button button="google" [url]="'http://10.10.14.95:8080/cmscontrolpanel/appShareService?userId=2197&mediaId=1&countryISOCode=IND'"></share-button>
```
but in view it is showing 

 `<share-button _ngcontent-c10="" button="google" ng-reflect-create-button="google" ng-reflect-set-url="http://10.10.14.95:8080/cmscon" class="sb-button sb-default"><button class="sb-wrapper sb-google sb-show-icon" ng-reflect-share-button="google" ng-reflect-get-count="false" ng-reflect-url="http://10.10.14.95:8080/cmscon" style="--button-color:#DB4437; font-size: 14px;"><div class="sb-inner"><div class="sb-content"><div class="sb-icon ng-star-inserted"><fa-icon ng-reflect-icon-prop="[object Object]" class="ng-fa-icon"><svg aria-hidden="true" data-prefix="fab" data-icon="google-plus-g" class="svg-inline--fa fa-google-plus-g fa-w-20" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 512"><path fill="currentColor" d="M386.061 228.496c1.834 9.692 3.143 19.384 3.143 31.956C389.204 370.205 315.599 448 204.8 448c-106.084 0-192-85.915-192-192s85.916-192 192-192c51.864 0 95.083 18.859 128.611 50.292l-52.126 50.03c-14.145-13.621-39.028-29.599-76.485-29.599-65.484 0-118.92 54.221-118.92 121.277 0 67.056 53.436 121.277 118.92 121.277 75.961 0 104.513-54.745 108.965-82.773H204.8v-66.009h181.261zm185.406 6.437V179.2h-56.001v55.733h-55.733v56.001h55.733v55.733h56.001v-55.733H627.2v-56.001h-55.733z"></path></svg></fa-icon></div></div></div></button></share-button>`

**Comment by MurhafSousli** [comment]
Please fill all the required info in the issue template. and include a reproduction of your issue in a [stackblitz](https://stackblitz.com/edit/ngx-sharebuttons)

Closing this as it does not follow the issue template
