### ISSUE TITLE
Upgrading from 5.2.0 to 5.3.1 gives compile errors

### ISSUE THREAD

**Issue by pmeems** [MurhafSousli/ngx-sharebuttons#271]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### Versions
Angular CLI: 1.7.4
Node: 8.9.4
OS: win32 x64
Angular: 5.2.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

@angular/cdk: 5.2.5
@angular/cli: 1.7.4
@angular/material: 5.2.5
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.7.2
webpack: 3.11.0

### The log given by the failure

ERROR in : 'share-buttons' is not a known element:

### Desired functionality
After upgrading my code should still work or in the documentation should be told what I need to change.

### Mention any other details that might be useful

When I revert back to v5.2.0 my project compiles.
I'm using WebStorm v2018.1.2
The tag I'm using comes from the documentation: `<share-buttons show="11"></share-buttons>`

My app.module:
```
import {ShareButtonsModule} from '@ngx-share/buttons';
import { ShareButtonsOptions } from '@ngx-share/core';
const shareButtonsOptions: ShareButtonsOptions = {
  include: ['facebook', 'twitter', 'google', 'linkedin', 'reddit', 'whatsapp', 'telegram', 'vk', 'stumble', 'email', 'copy', 'print'],
  theme: 'material-dark',
  gaTracking: true
};
```
In my Imports:
`ShareButtonsModule.forRoot({ options: shareButtonsOptions })`

**Comment by MurhafSousli** [comment]
I suggest you remove the node_modules and re-install again, make sure that you have read the breaking changes which occured in 5.3.x in the [changelog](https://github.com/MurhafSousli/ngx-sharebuttons/blob/master/CHANGELOG.MD)
