### ISSUE TITLE
Support for Angular 6 / RxJS 6

### ISSUE THREAD

**Issue by SebastianPodgajny** [MurhafSousli/ngx-sharebuttons#274]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?
all

### Versions
```
Angular CLI: 6.0.0
Node: 9.11.1
OS: linux x64
Angular: 6.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, http, language-service, material, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@angular/flex-layout              6.0.0-beta.15
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0
```

### Repro steps
ng build

### The log given by the failure
![image](https://user-images.githubusercontent.com/21180501/39678370-cef7fa5e-518b-11e8-92f3-2bd2b42c5b47.png)

### Desired functionality
I would like to use ngx-sharebuttons with Angular 6 / RxJS 6

### Mention any other details that might be useful
https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md

**Comment by MurhafSousli** [comment]
it is coming soon, but anyway, the current Angular version 6.0.0 has a bug with AOT so we don't need to rush

**Comment by SebastianPodgajny** [comment]
I'm using Angular 6.0 without problems, however there is bug in build-optimizer. You can disable it in angular.json

```
"production": {
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": false, <--------- here
              "serviceWorker": true,
              "ngswConfigPath": "src/ngsw-config.json",
              "fileReplacements": [...]
}
```
issue: https://github.com/angular/angular-cli/issues/10655

**Comment by naveedahmed1** [comment]
@MurhafSousli any update on this?

**Comment by RicardoVaranda** [comment]
Would also love some news on this, quite annoying warning message :$

**Comment by naveedahmed1** [comment]
This change would also help in reducing the bundle sizes. In my case this is the only plugin that's dependent on rxjs-compat.

**Comment by akopachov** [comment]
+1
This is the only one plugin I'm waiting to get rid of `rxjs-compat` dependency

**Comment by naveedahmed1** [comment]
The upgrade process should be as simple as running below commands:

```
npm install -g rxjs-tslint
rxjs-5-to-6-migrate -p src/tsconfig.app.json
```

`rxjs-tslint` is a great tool from the rxjs team to automatically migrate your project which uses RxJS 5 to RxJS 6.

**Comment by skbelalmd** [comment]
@MurhafSousli any update on this?

**Comment by eruecco87** [comment]
+1 for the Angular 6 / RxJS 6 support needed.

**Comment by kevupton** [comment]
🚶 👍 📦  Please ❤️ 🥇 💃

**Comment by eruecco87** [comment]
Looks like installing first rxjs-compat takes care of it.

**Comment by RicardoVaranda** [comment]
@eruecco87 This is only supposed to be a temporary fix until package owners update their applications and not a permanent solution.

**Comment by eruecco87** [comment]
I know, I'm just commenting for those who need to get it working now instead of sitting by their screens waiting for the package to be updated.

**Comment by naveedahmed1** [comment]
@MurhafSousli is it published on npm? I am receiving below error:

`No matching version found for ngx-sharebuttons@6.0.0`

**Comment by MurhafSousli** [comment]
`@ngx-share/buttons`

**Comment by naveedahmed1** [comment]
Thanks everything worked perfectly 👍
