### ISSUE TITLE
Social network image is loading

### ISSUE THREAD

**Issue by sarn3792** [MurhafSousli/ngx-sharebuttons#276]
Hi.

I've installed share buttons module but no image of any social network appears, only loading icon is visible.
This is my code:

- myComponent.component.html:

 `<share-buttons [include]="['facebook','twitter','whatsapp']" [show]="3" [url]="'https://twitter.com/'"></share-buttons>`

- .angular-cli.json:
`"styles": [
        "styles.css",
        "../node_modules/ngx-sharebuttons/styles/share-buttons.css",
        "../node_modules/ngx-sharebuttons/styles/themes/default/default-theme.css"
      ]`

Attach an image. 
![image](https://user-images.githubusercontent.com/9375416/39732377-8f69532c-5232-11e8-9549-5b079623f1a2.png)

Hope you can help me

Thanks!!!

**Comment by MurhafSousli** [comment]
Did you install FontAwesome packages?

`@fortawesome/fontawesome-svg-core`
`@fortawesome/free-brand-svg-icons`
`@fortawesome/free-solid-svg-icons`
`@fortawesome/angular-fontawesome`

**Comment by MurhafSousli** [comment]
can you reproduce a [stackblitz](https://stackblitz.com/edit/ngx-sharebuttons)!
