### ISSUE TITLE
fortawesome decoupling

### ISSUE THREAD

**Issue by wizlif** [MurhafSousli/ngx-sharebuttons#280]
### Bug Report or Feature Request (mark with an `x`)
```
-[ ] bug report -> please search issues before submitting
- [x] feature request
-[x] question
```
This is an awesome product, however is it possible to use a cdn to serve the fonts instead of coupling them in the addon, it seems that fortawesome increases the project size by over 20%.
![screenshot-127 0 0 1-8888-2018 05 22-12-13-43](https://user-images.githubusercontent.com/15793624/40353373-0c18d22a-5dba-11e8-8946-34215454b05a.png)

**Comment by MurhafSousli** [comment]
That cannot be true! but you can open an issue regarding this on their repo https://github.com/FortAwesome/angular-fontawesome/issues

**Comment by MurhafSousli** [comment]
@wizlif I saw an existing issue on fortawesome repo, however when I tested it the demo app size, it was pretty small. did you try it in production?

**Comment by wizlif** [comment]
Thanks, i guess i'll follow it from that reference.

**Comment by MurhafSousli** [comment]
The plugin now does not load the icons out of the box, read more on [Icons Guide](https://murhafsousli.github.io/ngx-sharebuttons/#/icons)
