### ISSUE TITLE
iOS SMS Share Link populates recipient/to field instead of message field

### ISSUE THREAD

**Issue by mspriggs** [MurhafSousli/ngx-sharebuttons#283]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?

iOS 11.3.1 on iPhone X & iPad Pro

### Versions

angular/cdk: 5.0.3
angular/cli: 1.6.3
angular/material: 5.0.3
angular-devkit/build-optimizer: 0.0.36
angular-devkit/core: 0.0.22
angular-devkit/schematics: 0.0.42
ngtools/json-schema: 1.1.0
ngtools/webpack: 1.9.3
schematics/angular: 0.1.11
schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.10.0

### Repro steps

Open page with SMS component available. Once selected, iMessage opens and the "to" field is populated with a link to the content trying to share, while the text message field itself is empty.

You can replicate the issue by visiting this page on an iPhone or iPad and clicking the SMS button...
https://murhafsousli.github.io/ngx-sharebuttons/#/share-buttons-component

### The log given by the failure

N/A

### Desired functionality

The content link should populate the text message field in iMessage while the "to" or "recipient" field should be empty.

### Mention any other details that might be useful

This does work correctly on Android devices.

**Comment by MurhafSousli** [comment]
Current workaround
```ts
ShareButtonsModule.forRoot({
    prop: {
      sms: {
        share: {
          ios: 'sms:&',
      }
    }
  }
}
```
