### ISSUE TITLE
Error TS2307: Cannot find module '@fortawesome/fontawesome-svg-core'.

### ISSUE THREAD

**Issue by hxibrahim** [MurhafSousli/ngx-sharebuttons#286]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?
> macOS(High Sierra)

### Versions
`ng --version` -> 1.7.4

### Repro steps
1. create a new angular cli project.
2. install this package as explained in documentation using:

`$ npm i -S @ngx-share/core`
`$ npm i -S @fortawesome/{free-solid-svg-icons,free-brands-svg-icons}`

### The log given by the failure

ERROR in node_modules/@ngx-share/core/share.models.d.ts(2,26): error TS2307: Cannot find module 'fortawesome/fontawesome-svg-core'.

### Desired functionality
As explained in documentation, the installation should be successfull without the need for 'fortawesome/fontawesome-svg-core' module.

### Mention any other details that might be useful
NA.

**Comment by MurhafSousli** [comment]
I forgot to update the documentation. it is mandatory 
https://github.com/MurhafSousli/ngx-sharebuttons/blob/791f1d21b57eb733c7353b97345a27d2cc8f8a12/lib/core/src/share.models.ts#L2

**Comment by hxibrahim** [comment]
Thank you for quick the response and also for the project. Very nice job!
That would be nice to decouple "fortawesome" because for the people who already have bootstrap and font-awesome combined projects it is an over-head to add this package. So that only "ngx-share/core" would be enough to get it running like following example:

`<button shareButton="facebook">
    <i class="fa fa-fw fa-facebook"></i>
</button>`

This works very well and exactly what I (may be also many other) need, without the need for any "fort-awesome" package.

**Comment by MurhafSousli** [comment]
font-awesome 4 is old and it loads all the icons, but if you still want to use it then install v5.0.1.
font awesome 5 is better because it renders the icons as svg elements and it loads only the icons we use.

**Comment by MurhafSousli** [comment]
In version 6.x the icons must be loaded manually, read more on [Icons Guide](https://murhafsousli.github.io/ngx-sharebuttons/#/icons)
