### ISSUE TITLE
It's not clear which file to import for '@import "variables"'.

### ISSUE THREAD

**Issue by HectorRPL** [MurhafSousli/ngx-sharebuttons#288]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [   ] feature request
- [   ] question
```
`
While processing files with angular-compilers (for target web.browser):
client/main.scss:1:1: It's not clear which file to import for '@import "variables"'.
Candidates:
  variables.scss
  variables.css
Please delete or rename all but one of these files.
`

I see the files, and you have diferent files (css and scss) in a same folder, pleaseIt will be good that folder css and folder scss with only same files type

**Comment by HectorRPL** [comment]
Add `.scss` In the `@import "variables";` of the file `share-buttons.scss` and `default-theme.scss`  solve the problem.... but is not elegant.....
Is only to illustrate the problem

**Comment by MurhafSousli** [comment]
@HectorRPL I don't know which build system you are using. but with the CLI you don't need to add `.scss` at the end of the file name

**Comment by MurhafSousli** [comment]
I guess this is not an issue, closing...
feel free to continue the discussion

**Comment by bclynch** [comment]
In my case with an Ionic project you need to be specific in the file endings similar to this issue: https://github.com/MurhafSousli/ngx-sharebuttons/issues/177.

Adding .scss does fix this issue
