### ISSUE TITLE
How i can access facebook api for remove incorect links?

### ISSUE THREAD

**Issue by maikldan** [MurhafSousli/ngx-sharebuttons#290]
How i can access facebook api for remove incorect links?
![image](https://user-images.githubusercontent.com/11440949/41479415-bebfe27a-70d3-11e8-91aa-b9c95657f7de.png)
I also need to remove it from tweeter.

**Comment by maikldan** [comment]
Please tell me how i can know remove all this posts or links, from facebook, linkedin, twitter and another.

**Comment by MurhafSousli** [comment]
You need to change the meta tags in your `index.html` head

**Comment by maikldan** [comment]
I changed but old data also remains.

**Comment by MurhafSousli** [comment]
After you deploy the changes, you should refresh it here https://developers.facebook.com/tools/debug/

**Comment by maikldan** [comment]
Ok, but what about Twitter, Google +. Facebook works, thanks.

**Comment by maikldan** [comment]
LinkedIn also please.

**Comment by MurhafSousli** [comment]
I don't know, google it, your issue is related to the plugin

**Comment by maikldan** [comment]
Linked In have issues, old image is there. If you find something, please
contact me, thanks a lot.
