### ISSUE TITLE
Issue while installing package

### ISSUE THREAD

**Issue by ritsrivastava01** [MurhafSousli/ngx-sharebuttons#291]
I'm trying to integrate this Social package in my application, but I face an issue when I'm trying to run 
 thi scommand 
'npm i -S @ngx-share/{core,button}
npm ERR! Could not install from "@ngx-share\{core,button}" as it does not contain a package.json file.

Pls, help me to fix this issue.
Thanks.

**Comment by MurhafSousli** [comment]
Will update the doc, use `npm i -S @ngx-share/core @ngx-share/button`

**Comment by ritsrivastava01** [comment]
Thx Murhaf, 
I installed it and add below lines in my style.scss file:

@import '@ngx-share/button/styles/share-buttons';
@import '@ngx-share/button/styles/themes/default/default-theme';

Imported in my app.import.ts:
 ShareModule.forRoot(),

Used liek
          `<button shareButton="facebook">Share</button>` 
        `<button shareButton="twitter">Tweet</button>`
          `<button shareButton="pinterest">Pin</button>`

But while building I got a new issue:

ERROR in node_modules/@ngx-share/core/lib/share.models.d.ts(2,10): error TS2305: Module '"<Project_path>/node_modules/rxjs/Rx"' has no exported member 'OperatorFunction'.

node_modules/@ngx-share/core/lib/share.operators.d.ts(1,10): error TS2305: Module '"<Project_path>/node_modules/rxjs/Rx"' has no e
xported member 'OperatorFunction'.

I Know is something related to RxJs, but if you can help then its good.
Here is mine dependencies:
"dependencies": {
    `"@angular/animations": "^6.0.3",`
   ` "@angular/common": "^5.2.0",`
    `"@angular/compiler": "^5.0.5",`
    `"@angular/core": "^5.2.0",`
    `"@angular/forms": "^5.2.0"`,
    `"@angular/http": "^5.2.0",`
    `"@angular/platform-browser": "^5.2.0"`,
    `"@angular/platform-browser-dynamic": "^5.2.0",`
    `"@angular/router": "^5.2.0",`
    `"@ngx-pwa/local-storage": "^5.3.0",`
    `"@ngx-share/button": "^6.0.0-beta.0",`
    `"@ngx-share/core": "^6.0.0-beta.0",`
    `"@ngx-translate/core": "^9.1.1",`
    `"@ngx-translate/http-loader": "^2.0.1",`
    `"@types/jquery": "^3.3.2",`
    `"angular2-materialize": "^15.1.10",`
    `"angular2-recaptcha": "^0.6.0",`
    `"chart.js": "^2.7.2",`
    `"core-js": "^2.4.1",`
    `"date-fns": "^1.29.0",`
    `"hammerjs": "^2.0.8",`
    `"inquirer-directory": "^2.1.0",`
    `"jquery": "^3.3.1",`
    `"load-json-file": "^3.0.0",`
    `"materialize-css": "^0.100.2",`
    `"ng-lazyload-image": "^4.0.0",`
    `"ng2-charts": "^1.6.0",`
    `"ng2-scroll-to-el": "^1.2.1",`
    `"ngx-calender": "^2.0.2",`
    `"ngx-ellipsis": "^1.0.7",`
    `"ngx-facebook": "^2.4.0",`
    `"ngx-owl-carousel": "^2.0.1",`
    `"ngx-scroll-event": "^1.0.7",`
    `"node-sass": "^4.7.2",`
    `"rxjs": "^5.5.3",`
    `"wp-api-angular": "^3.0.0-beta8",`
    `"zone.js": "^0.8.14"`
}

Thanks in Advaced.

**Comment by MurhafSousli** [comment]
@ritsrivastava01 I just updated the docs for version 6, check [wiki](https://github.com/MurhafSousli/ngx-sharebuttons/wiki) or the [docs site](https://murhafsousli.github.io/ngx-sharebuttons/)
