### ISSUE TITLE
import { OperatorFunction } from 'rxjs';

### ISSUE THREAD

**Issue by ritsrivastava01** [MurhafSousli/ngx-sharebuttons#295]
After installing for Angular 5, I got this issue while building the application:

`import { OperatorFunction } from 'rxjs';`

`
ERROR in node_modules/@ngx-share/core/lib/share.operators.d.ts(1,10): error TS2305: Module '"/node_modules/rxjs/Rx"'
 has no exported member 'OperatorFunction'.`

Rxjs Version:
` "rxjs": "^5.5.3",`
  `"@ngx-share/button": "^6.0.0",`
    `"@ngx-share/core": "^6.0.0",`

Pls, let me know if I'm doing anything wrong

**Comment by MurhafSousli** [comment]
@ritsrivastava01 version 6 is not compatible with Angular 5, use v5.3.1 instead or consider upgrading to Angular 6

**Comment by ritsrivastava01** [comment]
Hi @MurhafSousli 
Thx for updating its build now, but not render the icons. for bellow error:
` FontAwesome: Could not find icon with iconName=facebook-square and prefix=fab`

Pls, let me know what I missed??
Thanks for your quick reply.

**Comment by MurhafSousli** [comment]
You need to load each icon you use, in this case, it is telling you that you need to import `faFacebookSquare` and load it into the icons library.

**Comment by ritsrivastava01** [comment]
I created Icon.ts file and imported in polyfills.ts file as well, like:
import './icons';
