### ISSUE TITLE
Trying to import { ShareModule } from '@ngx-share/core and use Share Buttons

### ISSUE THREAD

**Issue by sunpasup** [MurhafSousli/ngx-sharebuttons#300]
<img width="1552" alt="screen shot 2018-06-19 at 8 04 57 am" src="https://user-images.githubusercontent.com/24596204/41606021-993c48f6-7397-11e8-89d9-b4087e579684.png">

**Comment by sunpasup** [comment]
Above Error is What I get..

**Comment by MurhafSousli** [comment]
Please fill the template issue, including all the required info along with your usage code. closing as not enough info

**Comment by sunpasup** [comment]
My App Module 

`
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { RouterModule } from '@angular/router';
import { ShareButtonModule } from '@ngx-share/button';
import { ShareModule } from '@ngx-share/core';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';





import { AppRoutingModule } from './app.routing';
import { ComponentsModule } from './components/components.module';

import { AppComponent } from './app.component';

import { DashboardComponent } from './dashboard/dashboard.component';
import { UserProfileComponent } from './user-profile/user-profile.component';
import { TableListComponent } from './table-list/table-list.component';
import { TypographyComponent } from './typography/typography.component';
import { IconsComponent } from './icons/icons.component';
import { MapsComponent } from './maps/maps.component';
import { NotificationsComponent } from './notifications/notifications.component';
import { UpgradeComponent } from './upgrade/upgrade.component';
import {
  AgmCoreModule
} from '@agm/core';
import { AdminLayoutComponent } from './layouts/admin-layout/admin-layout.component';

@NgModule({
  imports: [
    BrowserAnimationsModule,
      ShareButtonModule.forRoot(),
      ShareModule.forRoot(),
      FontAwesomeModule,
    FormsModule,
    HttpModule,
    ComponentsModule,
    RouterModule,
    AppRoutingModule,
    AgmCoreModule.forRoot({
      apiKey: 'YOUR_GOOGLE_MAPS_API_KEY'
    })
  ],
  declarations: [
    AppComponent,
    AdminLayoutComponent,

  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
`

 My Template 

` <div id="columns">
          <figure *ngFor="let cards of twitterData">
              <img src="{{cards.url}}">
              <figcaption>
                  <button mat-raised-button type="submit" class="btn btn-danger pull-left">Approve</button>
                  <button mat-raised-button type="submit" class="btn btn-danger pull-right">Decline</button>
                  <button mat-fab shareButton="facebook" [style.backgroundColor]="share.prop.facebook.color">
                      <fa-icon [icon]="share.prop.facebook.icon" size="lg"></fa-icon>
                  </button>
                  <button mat-fab shareButton="twitter" [style.backgroundColor]="share.prop.twitter.color">
                      <fa-icon [icon]="share.prop.twitter.icon" size="lg"></fa-icon>
                  </button>
                  <button mat-fab shareButton="linkedin" [style.backgroundColor]="share.prop.linkedin.color">
                      <fa-icon [icon]="share.prop.linkedin.icon" size="lg"></fa-icon>
                  </button>
                  <button mat-fab shareButton="whatsapp" [style.backgroundColor]="share.prop.whatsapp.color">
                      <fa-icon [icon]="share.prop.whatsapp.icon" size="lg"></fa-icon>
                  </button>
                  <button mat-fab shareButton="telegram" [style.backgroundColor]="share.prop.telegram.color">
                      <fa-icon [icon]="share.prop.telegram.icon" size="lg"></fa-icon>
                  </button>
                  <button mat-fab shareButton="pinterest" [style.backgroundColor]="share.prop.pinterest.color">
                      <fa-icon [icon]="share.prop.pinterest.icon" size="lg"></fa-icon>
                  </button>

              </figcaption>
          </figure>

      </div>`

My Template TS 

`import { Component, OnInit } from '@angular/core';
import { sampleData} from '../twitterData';
import { faFacebookSquare } from '@fortawesome/free-brands-svg-icons/faFacebookSquare';
import { faTwitterSquare } from '@fortawesome/free-brands-svg-icons/faTwitterSquare';
import { faPinterest } from '@fortawesome/free-brands-svg-icons/faPinterest';
import { ShareButtons } from '@ngx-share/core';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';



@Component({
  selector: 'app-icons',
  templateUrl: './icons.component.html',
  styleUrls: ['./icons.component.css']
})
export class IconsComponent implements OnInit {

    fbIcon = faFacebookSquare;
    pinIcon = faPinterest;
    tweetIcon = faTwitterSquare;

  public twitterData:any = sampleData;

    constructor(public share: ShareButtons, public fa: FontAwesomeModule) {
    }

  ngOnInit() {
  }

}
`

Hope This Info Helps

**Comment by MurhafSousli** [comment]
Answer is here #301
