### ISSUE TITLE
Feature request: Ability to make buttons act as links to social pages

### ISSUE THREAD

**Issue by SStembridge** [MurhafSousli/ngx-sharebuttons#305]
I have a site that uses the share buttons to allow users to share certain pages on social media like they were designed to do, but we also have normal links to the organizations actual facebook/twitter/etc. pages in the footer of the site.

We want the links to have basically the same styling as the share buttons for consistency, so it would be convenient if the share buttons component had the option to specify that the buttons behave as links to pages instead of buttons that open a share dialog window.
I imagine it would have some inputs that look similar to this:
```
<share-buttons [theme]="'modern-dark'" [target]="_blank"
    [links]="{'facebook':'facebook.com/our-page','twitter':'twitter.com/our-page'">
</share-buttons>
```

If that's beyond the scope of this project or simply unreasonable I understand. I've been able to mimic what I want by copying the outputted html and styles from the component like so:
```
<div class="sb-group sb-modern-dark sb-site-links">
    <a class="sb-wrapper sb-facebook sb-show-icon m-2" href="https://www.facebook.com/our-page/" target="_blank">
        <div class="sb-inner">
            <div class="sb-content">
                <div class="sb-icon">
                    <fa-icon [icon]="['fab','facebook-f']"></fa-icon>
                </div>
            </div>
        </div>
    </a>
    <a class="sb-wrapper sb-twitter sb-show-icon m-2" href="https://twitter.com/our-page" target="_blank">
        <div class="sb-inner">
            <div class="sb-content">
                <div class="sb-icon">
                    <fa-icon [icon]="['fab','twitter']"></fa-icon>
                </div>
            </div>
        </div>
    </a>
</div>
```
This request is just to have a bit of convenience and consistency. For example, if some of the styling happens to change in the future or the organization adds a new social site to their list I would have to manually update the html. Not difficult to do by any means, but I think the share-buttons component could easily handle such a function and make the html template much more compact and avoid copy paste errors. It would also mean the project wouldn't have to import the icons separately since the share-buttons module already has them.

**Comment by MurhafSousli** [comment]
You can do that already by adding a custom button

```ts
import { Component } from '@angular/core';
import { ShareButtons } from '@ngx-share/core';

@Component(...)
export class AppComponent {

  constructor(private _share: ShareButtons) {
    this._share.addButton('fb-page', {
      type: 'fb-page',
      text: 'Follow us',
      icon: ['fab', 'facebook'],
      color: '#4267B2',
      share: {
        desktop: 'https://www.facebook.com/9gag/',
        android: 'https://www.facebook.com/9gag/',
        ios: 'https://www.facebook.com/9gag/'
      }
    });
  }
}
```
Check this [stackblitz](https://stackblitz.com/edit/ngx-sharebuttons-pf27zx?file=src%2Fapp%2Fapp.component.ts)
