### ISSUE TITLE
Update for @fortawesome/angular-fontawesome 0.1.0

### ISSUE THREAD

**Issue by pulsejet** [MurhafSousli/ngx-sharebuttons#306]
Works with `0.1.0-10`, broken for latest `0.1.0`

**Comment by MurhafSousli** [comment]
That's right, `@fortawesome/angular-fontawesome@0.1.0` is broken, duplicate of #303

**Comment by pulsejet** [comment]
Thanks for the quick reply! This library you are maintaining is truly wonderful :)

**Comment by MurhafSousli** [comment]
@pulsejet  Thank you!
