### ISSUE TITLE
Sharebuttons not working in PWA

### ISSUE THREAD

**Issue by larsbeck** [MurhafSousli/ngx-sharebuttons#308]
First of all let me say thanks for the package! It is working great on my website. However when I install my site as a progressive web app, the share buttons don't work anymore.
I am not sure, but this might be related to this issue: https://bugs.chromium.org/p/chromium/issues/detail?id=792990
Can anyone verify the issue?

**Comment by skbelalmd** [comment]
@larsbeck  There is no issue with share buttons in pwa. Check our deployed pwa app https://mentoriaserver-staging.azurewebsites.net 

After you save the app to home screen, visit the blog page using the link on navbar "The Mentoria Blog"
You will see the share buttons are working perfectly for the blog articles.

**Comment by larsbeck** [comment]
Thanks @skbelalmd for checking. You are right! And oddly enough it is now also working in my PWA. Not sure why it wasn't working before, but even better that it does now. Closing this issue now.

**Comment by johhansantana** [comment]
I've been having this same error. The share buttons work but after playing around with them, for example, try and share into WhatsApp and then cancel by going back to the pwa, the buttons won't work anymore for some reason. 

Also, messenger and email opens like a web view but don't do anything. 

This doesnt happen if you browse the pwa in android chrome though(not installed in home screen).

**Comment by hassansaleh31** [comment]
Same for me the buttons do not work when you press share then cancel back Any updates on this?

**Comment by fmendoza** [comment]
Same here. Tested my PWA on Android (Chrome).

If I inspect my device I notice that just after the buttons become unresponsive, two untitled windows are present. I'm not sure if this is causing the issue here. See attached image.

<img width="646" alt="captura de pantalla 2019-01-24 a la s 16 49 56" src="https://user-images.githubusercontent.com/1320696/51713658-54689000-1ff8-11e9-87c7-e939d798ae93.png">

**Comment by MurhafSousli** [comment]
When a share button is clicked (desktop, mobile) a new tab in the browser opens, then it takes you to the app to share the link.
What is happening that the recent opened tab stays opened and probably causing this issue.
If you try a share button on desktop, lets say twitter but don't share it or close the window yet, go back to app again and try another share button, you will see that same tab opens.
**Maybe** I am not sure but maybe this is the cause on mobile. Not sure how we can get around this

**Comment by spl-seb** [comment]
Hello,

Still no solution for this problem?

In PWA when i try to share on linkedin, app native of linkedin open and when i back i have a white screen (popup login window), i don't close it.
