### ISSUE TITLE
package not installed 

### ISSUE THREAD

**Issue by Manaskumar119** [MurhafSousli/ngx-sharebuttons#310]
ng4-cm/node_modules/@ngx-share/core/lib/share.models.d.ts (2,10): Module  /node_modules/rxjs/Rx"' has no exported member 'OperatorFunction'

**Comment by MurhafSousli** [comment]
Closing as not following issue template

**Comment by Manaskumar119** [comment]
@MurhafSousli  , so How I can I resolve this ?

**Comment by MurhafSousli** [comment]
@Manaskumar119 You should fill the issue template correctly like other people do. Add the version of angular and the version of the share buttons plugin are you using, Add your usage code, then I can look into it.
