### ISSUE TITLE
'undefined' imported by the module 'ShareButtonModule'

### ISSUE THREAD

**Issue by abrahamsankutty** [MurhafSousli/ngx-sharebuttons#312]
### when i tried to import shared button module to app module above error is showing in the console
angular
Versions - >>
Angular CLI: 1.7.4
Node: 8.9.4
OS: linux x64
Angular: 5.2.11
----------------

package.json

 "ngx-share/button": ^5.3.1,
 "ngx-share/buttons": "^5.3.1",
 "ngx-share/core": "^5.3.1"

**Comment by wermerb** [comment]
I have the same issue

**Comment by abrahamsankutty** [comment]
@wermerb hi, did u find any work around for this?
