### ISSUE TITLE
Share dynamic content

### ISSUE THREAD

**Issue by mmazloum** [MurhafSousli/ngx-sharebuttons#313]
Hi,

I havent seen in the repo if it's possible to use your share buttons on dynamic content urls (ex: Blog posts) ?

I'd assume it would be based on angular-universal on something equivalent to update meta-tags on server side ?

**Comment by MurhafSousli** [comment]
Hi @mmazloum This plugin supports Universal! but the demo is hosted on Github pages and we cannot use universal with Github pages because it does not run node on their servers.

You can find many tutorials on how to get your app SEO friendly, but that's not related to this plugin.
