### ISSUE TITLE
Email share button component fails on Outlook

### ISSUE THREAD

**Issue by TheFirstAvenger** [MurhafSousli/ngx-sharebuttons#314]
#### I am submitting a

- [x] Bug Report

#### What is the expected behavior?
Click email share button on computer with Outlook 2013 installed. New email appears with specified URL in email body

#### What is the current behavior?
Click email share button on computer with Outlook 2013 installed. New email appears with *no* body populated 

#### What are the steps to reproduce?
Go here with a computer that has Outlook 2013 installed:
https://murhafsousli.github.io/ngx-sharebuttons/#/share-button-component
Scroll down to "lab". Change button to "email". Click button.

**Comment by MurhafSousli** [comment]
@TheFirstAvenger This seems to be a known issue, and it is not related to this plugin.

[Microsoft community question](https://answers.microsoft.com/en-us/msoffice/forum/msoffice_outlook/blank-email-body-in-outlook-web/883e1490-2ef2-49e9-874e-e0bc81cfbbdd), [Stackoverflow question](https://stackoverflow.com/questions/44158302/outlook-webmail-access-mailto-body-is-blank)

I am afraid this is a won't fix, in case you found a solution, please reopen it.

**Comment by TheFirstAvenger** [comment]
@murhafsousli Those all reference Outlook Web Access, but state that regular Outlook works for them. This issue is with regular Outlook. I have confirmed that a simple HTML file works as expected when populating the body of the email, but share buttons does not.

**Comment by MurhafSousli** [comment]
@TheFirstAvenger Do you mean wrapping the body with HTML like `<p>{{body}}</p>` would fix it?

**Comment by TheFirstAvenger** [comment]
No, I mean that if I create a simple html file with this:
`
<html>
	<body>
		<a href="mailto:?body=ThisIsBodyText">test</a>
	</body>
</html>
`
then Outlook populates the email body with ThisIsBodyText when I click it. If I try the same with share-buttons, it does not populate the body text with the value passed in to url. Both options work if Gmail is the mailto: handler, but when Outlook is the mailto: handler, the simple html case works, but share-buttons does not.

**Comment by MurhafSousli** [comment]
The generated link by the email button look like this
`mailto&su=Hello+World&body=Here+goes+the+body%0D%0Ahttps://twitter.com/`

I made here a [stackblitz](https://stackblitz.com/edit/ngx-sharebuttons-mwy6bl?file=src%2Fapp%2Fapp.module.ts) that override email button operators, test if it works with outlook. basically I just removed the `encodeURIComponent` from the paramters values

**Comment by TheFirstAvenger** [comment]
@MurhafSousli Comparing your values to mine, I was able to figure out that if you remove the "title" parameter from your stackblitz, you will see that it fails on Outlook, but still works in gmail. I believe this is the issue I was seeing (I didn't have a title set). I have updated the issue to reflect the root cause.

**Comment by MurhafSousli** [comment]
@TheFirstAvenger I don't have outlook to debug it.
Now I am confused! what is working and what is not! Do you mean that it works when the title is set?

**Comment by TheFirstAvenger** [comment]
If you don't set a title, then the body of the message doesn't populate correctly in Outlook.
