### ISSUE TITLE
not able to see picture  and desciption

### ISSUE THREAD

**Issue by dhritidutta** [MurhafSousli/ngx-sharebuttons#315]
I am not able to see picture and description on share site.i followed everything inducing search engine optimization .I  need the urgent reply .please help me or tell me any subscription is needed for this i will get it.please help on this particular issue.

**Comment by MurhafSousli** [comment]
@dhritidutta I gonna have to close this as it doesn't follow the template issue.

If you need help in making your app SEO friendly, we can discuss this via email. But this area is for submitting bug reports.
