### ISSUE TITLE
FontAwesome: Could not find icon with iconName=facebook-f and prefix=fab

### ISSUE THREAD

**Issue by eyalhakim** [MurhafSousli/ngx-sharebuttons#316]
#### I am submitting a

- [x] Bug Report

#### What is the current behavior?
I am using the share directive with material fab icons.
I installed the brands package but the icon is still not found. Do i need to import it somewhere?

#### What are the steps to reproduce?
```html
    <button mat-mini-fab shareButton="facebook" [style.backgroundColor]="share.prop.facebook.color">
        <fa-icon [icon]="share.prop.facebook.icon"></fa-icon>
    </button>
```

#### Which versions are you using for the following packages?

Angular:
Angular CDK:
Angular CLI:
Angular-fontawesome:
Share buttons:

**Comment by MurhafSousli** [comment]
Did you import the icon?
```ts
import { library } from '@fortawesome/fontawesome-svg-core';

import { faFacebookF } from '@fortawesome/free-brands-svg-icons/faFacebookF';

const icons = [
  faFacebookF
];

library.add(...icons);
```

**Comment by eyalhakim** [comment]
my bad, i did not!

Thanks
