### ISSUE TITLE
Error logs on SSR

### ISSUE THREAD

**Issue by abbasdawood** [MurhafSousli/ngx-sharebuttons#320]
#### I am submitting a

- [x] Bug Report

#### What is the expected behavior?
No errors in error log related to Share buttons

#### What is the current behavior?
Following errors show up in PM2 logs for the web app running on node server
```
ERROR TypeError: Cannot read property 'type' of undefined
    at TokenStream.LA (/home/ubuntu/iifa/node_modules/domino/lib/cssparser.js:810:30)
     at TokenStream.advance (/home/ubuntu/iifa/node_modules/domino/lib/cssparser.js:683:20)
     at Parser._readDeclarations (/home/ubuntu/iifa/node_modules/domino/lib/cssparser.js:3402:42)
     at Parser.parseStyleAttribute (/home/ubuntu/iifa/node_modules/domino/lib/cssparser.js:3581:22)
     at parseStyles (/home/ubuntu/iifa/node_modules/domino/lib/CSSStyleDeclaration.js:23:10)
     at CSSStyleDeclaration.value (/home/ubuntu/iifa/node_modules/domino/lib/CSSStyleDeclaration.js:142:22)
     at new ExpandButtonComponent (/home/ubuntu/iifa/node_modules/@ngx-share/buttons/bundles/ngx-share-buttons.umd.js:117:32)
     at createClass (/home/ubuntu/iifa/node_modules/@angular/core/bundles/core.umd.js:12519:20)
    at createDirectiveInstance (/home/ubuntu/iifa/node_modules/@angular/core/bundles/core.umd.js:12364:37)
     at createViewNodes (/home/ubuntu/iifa/node_modules/@angular/core/bundles/core.umd.js:13822:53)
```

#### What are the steps to reproduce?
Build project with ngx-share/buttons & ngx/core and deploy to SSR environment

#### What is the use-case or motivation for changing an existing behavior?
Reduced number of error logs

#### Which versions are you using for the following packages?

Angular: 5.2.0
Node: 9.0.0
Angular CLI: 1.7.6
Angular-fontawesome: 0.1.0-10
Share buttons: 5.3.1

**Comment by MurhafSousli** [comment]
It works on SSR! Please add your code

**Comment by MamaDoudou** [comment]
Hello, i'm having a same error with ssr. 
Angular": "^7.2.12"
"@ngx-share/button": "^7.1.2",
"@ngx-share/buttons": "^7.1.2",
"@ngx-share/core": "^7.1.2"

I solved it by using this:
->share.component.ts
import {Component, Inject, OnInit, PLATFORM_ID} from '@angular/core';
import { isPlatformBrowser } from '@angular/common';
....
export class ShareComponent implements OnInit{
isBrowser;
....
constructor(@Inject(PLATFORM_ID) private platformId: Object) { }

ngOnInit() {
    this.isBrowser = isPlatformBrowser(this.platformId);
    .....
 
  }
 ....
}
->share.component.html
<div class="..." *ngIf="isBrowser">
        <share-buttons show="5"></share-buttons>
 </div>

I hope it helps

**Comment by Judp0m** [comment]
I am having the exact same issue on Angular 11.
The buttons won't render in SSR. This forces us to hide the button for the server via `*ngIf="isBrowser"` which is not ideal.
@MurhafSousli Could you please re-open this issue since a number of people have reported the issue and are impacted?

Angular: 11.0.5
Node: 9.1.1
Angular CLI: 11.0.5
Angular-fontawesome: 0.8.1
Share buttons: 8.0.5

**Comment by MurhafSousli** [comment]
@Judp0m  This issue was in a different package, since then the package had changed.. now it should not happen, I've already test it with Universal! and tried it again with the demo, SSR is working.. try to run the demo project `npm run dev:ssr`

**Comment by Judp0m** [comment]
Thanks for your quick reply @MurhafSousli 

I am using the latest version of all packages as listed in my reply above, and still observe the error when using SSR.
As part of my workflow, I use either `npm run dev:ssr` or `npm build:ssr`+`npm serve:ssr` or `npm run prerender`.
The result is the same in all cases : if I don't remove the <share-buttons> tag (e.g. via `*ngIf="isBrowser"`), I get the stack trace mentioned in my earlier message in the server side: `ERROR TypeError: Cannot read property 'type' of undefined` (full stack trace above).
Note1 that the error happens with this:
```
<share-buttons theme="modern-dark"
  [show]="2"
  [include]="['facebook','twitter','pinterest']"
></share-buttons>
```
but NOT with this:
<share-buttons theme="modern-dark"
  [show]="3"
  [include]="['facebook','twitter','pinterest']"
></share-buttons>

Note2: the same problem appears if trying to use the default style.

Whether or not the error is triggered, the button do not get properly populated, cf missing content in the html class tags:
![Screenshot from 2020-12-26 00-46-48](https://user-images.githubusercontent.com/8330896/103148384-f7117800-4713-11eb-94e6-ff4160e3507a.png)
![Screenshot from 2020-12-26 00-49-21](https://user-images.githubusercontent.com/8330896/103148419-3c35aa00-4714-11eb-8877-08a6087a8f03.png)

Not sure what is the cause.
In styles.scss : ```@import '~ngx-sharebuttons/themes/modern/modern-dark-theme.scss';```
In the module I import ```ShareButtonsModule``` and ```ShareIconsModule```

I tried using the single ```<share-button>``` directly, with the same result.

Keep in mind, everything works well in non-SSR mode! i.e. no problem when using ```ng serve``` or AFTER the angular app has booted in SSR. All these issues are present in the prerendered html (e.g. disable javascript in the browser to inspect).

Any help/tip is appreciated.

**Comment by cleandevcode** [comment]
I have a same issue on Angular 9 SSR project.
My original project was Angular 9, Node.js, Express project.
I converted it to SSR.

When I run "npm run dev:ssr", I see this kind of error.
![Untitled](https://user-images.githubusercontent.com/52365167/103746515-4445f180-5012-11eb-836f-e9240352cd4a.png)


This is my package.json.
```
"@angular-redux/store": "^10.0.0",
    "@angular/animations": "^9.1.4",
    "@angular/cdk": "^9.2.2",
    "@angular/common": "~9.1.4",
    "@angular/compiler": "~9.1.4",
    "@angular/core": "~9.1.4",
    "@angular/forms": "~9.1.4",
    "@angular/material": "^9.2.2",
    "@angular/platform-browser": "~9.1.4",
    "@angular/platform-browser-dynamic": "~9.1.4",
    "@angular/platform-server": "~9.1.4",
    "@angular/router": "~9.1.4",
    "@nguniversal/express-engine": "^9.1.1",
    "@ngx-translate/core": "^12.1.2",
    "@ngx-translate/http-loader": "^4.0.0",
    "express": "^4.17.1",
    "graphql-js-client": "^0.12.0",
    "jquery": "^3.5.1",
    "js-base64": "^3.6.0",
    "localstorage-polyfill": "^1.0.1",
    "lodash": "^4.17.20",
    "moment": "^2.29.1",
    "ngx-device-detector": "^2.0.1",
    "ngx-slick-carousel": "^0.5.1",
    "ngx-toastr": "^12.0.1",
    "node-fetch": "^2.6.1",
    "npm-run-all": "^4.1.5",
    "redux": "^4.0.5",
    "redux-devtools-extension": "^2.13.8",
    "redux-logger": "^3.0.6",
    "redux-observable": "^1.2.0",
    "rxjs": "~6.5.4",
    "rxjs-compat": "^6.6.3",
    "slick-carousel": "^1.8.1",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
```


I`d really appreciate it if anyone can help me.
Regards!

**Comment by Judp0m** [comment]
@MurhafSousli Several of us are running into this issue, as documented above. Can you re-open this issue, or I am happy to create a separate one if you prefer.

**Comment by angorora** [comment]
I am also having this issue, somewhere else it has been confirmed that it is caused by the failure for Universal to set custom properties to the dom

**Comment by MurhafSousli** [comment]
I will check this soon

**Comment by MurhafSousli** [comment]
This should not happen in v10.0.0, please report again if you encounter the same issue
