### ISSUE TITLE
[url] directive not working.

### ISSUE THREAD

**Issue by sqnkov** [MurhafSousli/ngx-sharebuttons#323]
`<a [url]="" [shareButton]="'twitter'">
					<i class="icon icon-twitter"></i>
				</a>`

Produces the following error for me:

**_Can't bind to 'url' since it isn't a known property of 'a'._**

How can I bypass this , @MurhafSousli ?

**Comment by MurhafSousli** [comment]
Ofcourse, the url is not a directive, it is an input of the share directive, order is important.
`<a [shareButton]="'twitter'" [url]=""> <i class="icon icon-twitter"></i> </a>`

**Comment by sqnkov** [comment]
Yes, excuse my order, I tried it afterwards as well.

`<a class="widg-info-act" [shareButton]="'twitter'" [url]="'https://google.com/'">
					<i class="icon icon-twitter"></i>
				</a>`

Same output:
**_Can't bind to 'url' since it isn't a known property of 'a'._**

**Comment by sqnkov** [comment]
@MurhafSousli , the order is not an issue regarding the directive and the url , also, using this:

<share-button [shareButton]="'twitter'" [url]="'http://google.com'"></share-button>

results in this:

![image](https://user-images.githubusercontent.com/9406520/43960961-5a71eb00-9cbc-11e8-9d10-864a26e9f038.png)

**Comment by MurhafSousli** [comment]
@sqnkov please try to reproduce this error in this [stackblitz](https://stackblitz.com/edit/ngx-sharebuttons)

**Comment by MurhafSousli** [comment]
here is your code working https://stackblitz.com/edit/ngx-sharebuttons-o82icn?file=src/app/home/home.component.html

**Comment by MurhafSousli** [comment]
If you have mentioned which version you are using, I would have pointed to that docs. all the inputs are prefixed with `sb` in v3 :)
