### ISSUE TITLE
Ability to disable buttons.

### ISSUE THREAD

**Issue by yharaskrik** [MurhafSousli/ngx-sharebuttons#325]
#### I am submitting a

- [x] Feature Request

#### What is the expected behavior?

option to disable the buttons using [disabled] as an input

#### What is the current behavior?

Cannot currently disable buttons

#### What is the use-case or motivation for changing an existing behavior?

I am using this library but want to disable the buttons during "preview" mode for the users.

#### Which versions are you using for the following packages?

Angular: v5 (Will work on any version though)

#### Is there anything else we should know?

I have already made the requested changes and can make a pull request with them for your review.

**Comment by MurhafSousli** [comment]
@yharaskrik This does not seem to be useful for most users. Why would you prevent users from sharing the link! especially when it is possible without the share buttons

**Comment by yharaskrik** [comment]
@MurhafSousli my use case is that in preview mode the share buttons should not be clickable for the user as they are creating a web page that will have the share buttons on it. Preview mode should not have any functionality enabled but should display exactly how it would when it is live. But if this is not a possibility of passing in a [disabled] flag to the share-buttons component then I will do it with an overlay.

**Comment by tayambamwanza** [comment]
@MurhafSousli this would indeed be helpful, I have a list of default share Icons, I want to disable certain buttons of the developer using the list has left out information, for example, if image url is not present, I want pinterest button disabled, if developer is in dev mode and not on http, I want to disable facebook button.

I will do the logic checks myself, but if there was a disabled property it would help a lot.
