### ISSUE TITLE
Share url with text

### ISSUE THREAD

**Issue by amic81** [MurhafSousli/ngx-sharebuttons#328]
- [x] Question

Hi,

is it possible to share a url in this way?

**text href text**

where href is the shared url.

because I tried to integrate it like this:

<share-buttons [theme]="'circles-dark'"
 [include]="['facebook','twitter','google','linkedin','copy','email','print']"
 [show]="9"
 [showCount]="true"
 [size]="4"
 **[description]="'text ' + href + ' text'"**
 [autoSetMeta]="false"
></share-buttons>

but the result on twitter (for example) is this:

**text http://urllinkshare text http://urllinkshare**

the URL is also added at the bottom ... it is possible to make this not happen and the result is 

**text http://urllinkshare text**?

I am waiting for your reply. Thank you.

amic81

**Comment by MurhafSousli** [comment]
It's not possible
