### ISSUE TITLE
Opening blank page on clicking <button shareButton="email"> in chrome browser

### ISSUE THREAD

**Issue by priyagr** [MurhafSousli/ngx-sharebuttons#329]
Hi,

I want to share link in email so used "shareButton="email" and class as fa-envelope.
But when I click on email icon in browser it just opens up a blank popup window and nothing happens further. Please help me out to resolve this issue.
Thanks in advance.

**Comment by MurhafSousli** [comment]
Please don't ignore the issue template next time.
Your browser is responsible for opening the email. you have to set a default app for that from your browser, [google it](https://www.google.com.tr/search?q=set+default+email+client+on+chrome&rlz=1C1CHZL_enTR761TR761&oq=set+default+email+client+on+chrome&aqs=chrome..69i57j0.5671j0j7&sourceid=chrome&ie=UTF-8).
