### ISSUE TITLE
Facebook sharing error

### ISSUE THREAD

**Issue by arabbani** [MurhafSousli/ngx-sharebuttons#332]
#### I am submitting a

- [x] Bug Report

#### What is the expected behavior?
Expected to share to facebook

#### What is the current behavior?
Facebook sharing is producing the following error:
`
Sorry, this feature isn't available right now: An error occurred while processing this request. Please try again later.
`

#### Which versions are you using for the following packages?

Angular: 6.1.0
Angular CDK:
Angular CLI: 6.0.8
Angular-fontawesome: 0.1.1
Share buttons: 6.0.1

**Comment by MurhafSousli** [comment]
The link you want to share must be hosted online! sharing on Facebook will not work in `localhost` mode

**Comment by arabbani** [comment]
Thanks for the information brother
