### ISSUE TITLE
What If I need to Change URL on the basis of Button (Facebook, Twitter, WhatsApp) click?

### ISSUE THREAD

**Issue by MrPardeep** [MurhafSousli/ngx-sharebuttons#334]
There is Event named `opened` which return button clicked name, But need to change URL on the basis of button clicked.
Is there any method/event triggered before model open for sharing content?

**Comment by MurhafSousli** [comment]
@MrPardeep No, there is no event that triggers before the share window opens

**Comment by MrPardeep** [comment]
Yes, I checked the documentation and code already.
Is there any another alternative for the same?
or May be you can considered as **Feature Request**.

**Comment by MrPardeep** [comment]
@MurhafSousli - I mean to say If I click on FB button to share something I need to share different URL (Say xyz.com), If I click on Twitter I need to share some different URL (say abc.com).

Right now I am getting Button label using event `opened` after Opening the share model. So I am not able to change URL dynamically depending on the Button clicked.

I hope it clears everything.

**Comment by MurhafSousli** [comment]
You cannot change the url on user click, you should change the url before and you can set different url for each share button

**Comment by MrPardeep** [comment]
That is what I wanted to know, How I can set URL before?
How's it possible to set different URL for each button?

**Comment by MurhafSousli** [comment]
I told you 
```html
<share-button button="facebook" [url]="facebookShareURL"></share-button>
<share-button button="twitter" [url]="twitterShareURL"></share-button>
```

**Comment by MrPardeep** [comment]
Yeah, seems that's the only solution right now. Thank you @MurhafSousli
