### ISSUE TITLE
Missing required dependencies when installing like in documentation

### ISSUE THREAD

**Issue by 000panther** [MurhafSousli/ngx-sharebuttons#336]
#### I am submitting a

- [x] Bug Report

#### What is the expected behavior?

The dependencies of the share buttons should be found when following https://github.com/MurhafSousli/ngx-sharebuttons/wiki/Share-Button-Component

#### What is the current behavior?

The dependencies of the share buttons are missing (free-brands-svg-icons, @fortawesome/fontawesome-svg)

#### What are the steps to reproduce?

➜  saturn-web git:(angular-6) npm i -S @fortawesome/fontawesome-svg @fortawesome/angular-fontawesome @fortawesome/free-solid-svg-icons free-brands-svg-icons

npm ERR! code E404
npm ERR! 404 Not Found: free-brands-svg-icons@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/paul/npmCache/_logs/2018-10-01T09_18_28_428Z-debug.log
➜  saturn-web git:(angular-6) npm i -S @fortawesome/fontawesome-svg @fortawesome/angular-fontawesome @fortawesome/free-solid-svg-icons

npm ERR! code E404
npm ERR! 404 Not Found: @fortawesome/fontawesome-svg@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/paul/npmCache/_logs/2018-10-01T09_18_42_610Z-debug.log

#### Which versions are you using for the following packages?

Angular CLI: 6.2.2
Node: 10.9.0
OS: linux x64
Angular: 6.1.7
Npm: 6.2.0
Angular CDK:  6.4.7
Angular-fontawesome: @latest
Share buttons: @latest

**Comment by MurhafSousli** [comment]
That was a mistake in the wiki docs, It is fixed now

`npm i -S @fortawesome/fontawesome-svg @fortawesome/angular-fontawesome @fortawesome/free-solid-svg-icons @fortawesome/free-brands-svg-icons`

**Comment by Ravslee** [comment]
I am facing the similar issue in my app
