### ISSUE TITLE
Sharing URL should include query string parameters

### ISSUE THREAD

**Issue by pwsusi** [MurhafSousli/ngx-sharebuttons#337]
Hi,
Excellent project.I noticed when sharing the current URL loaded in the browser the query string parameters are truncated. Would it be possible to preserve the full URL including the query string when sharing?

**Comment by AshrafGabesh** [comment]
Me 2 having the same problem, my url contains a front end params and it is truncated when sharing, please can you add an option to include them ?

**Comment by MurhafSousli** [comment]
Please try to reproduce your issue in a stackblitz

**Comment by Tomdrouv1** [comment]
@pwsusi @AshrafGabesh 
I had the same issue so I opened my console and saw a warning telling me that my url was invalid.
You should check if you have a warning 😉. If not sorry I will have tried.

**Comment by pwsusi** [comment]
My URL is valid. I created a stackblitz example. The problem is my app is using current URL in the address bar, which truncates the query string for Facebook, twitter, google plus, email and copy hyperlink (not sure about the othes as i'm not using them). The problem is in stackblitz if you try to show the issue it's going to use the current stackblitz url, which doesn't have query string parameters. I did force a url with query string parameters by setting [url] attribute on the share-buttons tag.  using the specified URL like this you only see the truncation with facebook but the others seem to retain the query string.. so i suppose that too is an issue, but if you were to use current URL which happens to contain query string parameters the problem exists across all buttons. Please let  me know how better to demostrate this. here is my stackblitz... https://stackblitz.com/edit/ngx-sharebuttons-6emxyu

**Comment by pwsusi** [comment]
After further investigation I realized the issue is related to the use of the history API. In my application i'm using history.replaceState() to modify the URL. If the URL is modified programmatically, when you click on the share buttons you will get the original URL and not the modified one which is present on the navigation bar. Here is my stackblitz to demonstrate.

https://ngx-sharebuttons-6emxyu.stackblitz.io/#/

**Comment by MurhafSousli** [comment]
After investigating, the query parameter is included, and it works properly.

Try
```html
<share-buttons [url]="sharingUrl + '?param=value'"></share-buttons>
```

Here is [stackblitz](https://stackblitz.com/edit/ngx-sharebuttons-ult5ez?file=src/app/home/home.component.ts)

**Comment by pwsusi** [comment]
That's not what the bug was opened for. Yes the query string parameter works. If you look at my post and the included stackblitz the issue is related to html history API used in conjunction with the share buttons. There is and never was any issue with the url attribute.  
https://stackblitz.com/edit/ngx-sharebuttons-6emxyu

**Comment by MurhafSousli** [comment]
@pwsusi I am confused! just give the share button a valid URL to share. the plugin does not know about html history API. It is still unclear what is the expected behavior of this issue. 

_For future issues please include at least the required information (versions, current behavior, expected behavior and a repro)._

**Comment by pwsusi** [comment]
Thanks for your reply. If you have some code that is manipulating the URL the query string parameters will be dynamic in nature. The documentation seems to indicate if you have a known URL you can specify it using the URL attribute, but if you leave URL attribute blank it should use the URL in the URL bar. therefor,  So if you have javascript code that is changing the query string and not using the URL atttribute on share buttons it will not pickup the latest URL in the address bar but instead the original one prior to it being set by the history API.  In my example the address is originally https://ngx-sharebuttons-6emxyu.stackblitz.io/#/   but after hitting the go button it becomes https://ngx-sharebuttons-6emxyu.stackblitz.io/?param=value. The param=value gets set at runtime via javascript. at that point when you click on the share buttons i would expect it to share the 2nd url with the query string, but it instead shares the first. Sorry if this was not clear. Thanks for the help

FYI I'm using the 5 with angular 5 but it seems to be the same behavior with version 6.

**Comment by MurhafSousli** [comment]
@pwsusi There is no problem with setting the URL at runtime, but you are using it the wrong way!

First, you used `[hidden]` which initializes the URL and renders the component with the initial URL which does not have the parameters.

Use `*ngIf` instead [working stackblitz](https://stackblitz.com/edit/ngx-sharebuttons-6q6h9m?file=src/app/home/home.component.html).

Or keep `[hidden]` but update the URL manually

```html
<share-buttons [url]="url" [hidden]="!showShareButtons"></share-buttons>
```
```ts
  url: string;

  onClick() {
    history.replaceState(null, null, '?param=value');
    // Update the URL
    this.url = window.location.href;
    this.showShareButtons = true;
  }
```
[fixed stackblitz](https://stackblitz.com/edit/ngx-sharebuttons-uv1cs3?file=src%2Fapp%2Fhome%2Fhome.component.ts).
