### ISSUE TITLE
FaIconService was not found

### ISSUE THREAD

**Issue by lapongua** [MurhafSousli/ngx-sharebuttons#339]
Hello,
when I compile the module I have this issue:

WARNING in ./node_modules/@fortawesome/angular-fontawesome/angular-fontawesome.ngfactory.js
19:300-316 "export 'FaIconService' (imported as 'i1') was not found in '@fortawesome/angular-fontawesome'

#### Which versions are you using for the following packages?

Angular: 6.1.4
Angular CDK:
Angular CLI: 6.2.1
Angular-fontawesome:
+ @fortawesome/free-brands-svg-icons@5.4.0
+ @fortawesome/free-solid-svg-icons@5.4.0
+ @fortawesome/angular-fontawesome@0.2.1
+ @fortawesome/fontawesome-svg-core@1.2.5
Share buttons:
+ @ngx-share/button@6.0.1
+ @ngx-share/buttons@6.0.1
+ @ngx-share/core@6.0.1

Thanks.

**Comment by MurhafSousli** [comment]
Hi, there is nothing called `FaIconService` in this plugin. it is probably your code or some other packages

**Comment by rubmz** [comment]
In the docs there is FaIconService .... Which is required to change the default icon prefix (yes...). 
Check for yourself.
Would like to know how to remove the annoying default prefix. but the docs are outdated...
Search here for "FaIconService":
https://github.com/FortAwesome/angular-fontawesome#using-other-styles
