### ISSUE TITLE
trouble installing fontawesome-svg

### ISSUE THREAD

**Issue by mattlang** [MurhafSousli/ngx-sharebuttons#340]
A question:
I am getting an error when trying to install the fonts:

npm ERR! 404 Not Found: @fortawesome/fontawesome-svg@latest

Not seeing much about this online.
One issue relates to installing the pro package without using a token

**Comment by MurhafSousli** [comment]
It is  `npm i -S @fortawesome/fontawesome-svg-core` or `yarn add @fortawesome/fontawesome-svg-core`
Thanks for the feedback, I fixed the docs
