### ISSUE TITLE
Icon not found @fortawesome

### ISSUE THREAD

**Issue by bigbrownies** [MurhafSousli/ngx-sharebuttons#343]
Hi,
I am here because i get an error while using this library.
I d'ont know how to resolve it. I tried some tricks but nothing help me.

- [x] Question

#### What is the expected behavior?
Show the share buttons component.

#### What is the current behavior?
Only show buttons, The icons do not show + console error.

Console Error :
> FontAwesome: Could not find icon with iconName=linkedin-in and prefix=fab angular-fontawesome.js:86
> faWarnIfIconHtmlMissing
> angular-fontawesome.js:86
> ./node_modules/@fortawesome/angular-fontawesome/fesm5/angular-fontawesome.js/FaIconComponent.prototype.renderIcon
> angular-fontawesome.js:194
> ./node_modules/@fortawesome/angular-fontawesome/fesm5/angular-fontawesome.js/FaIconComponent.prototype.ngOnChanges
> angular-fontawesome.js:132
> checkAndUpdateDirectiveInline
> core.js:9246
> checkAndUpdateNodeInline
> core.js:10514
> checkAndUpdateNode
> core.js:10476
> debugCheckAndUpdateNode
> core.js:11109
> debugCheckDirectivesFn
> core.js:11069
> View_ShareButtonComponent_1/<
> ShareButtonComponent.html:24:8
> debugUpdateDirectives
> core.js:11061
> checkAndUpdateView
> core.js:10458
> callViewAction
> core.js:10699
> execEmbeddedViewsAction
> core.js:10662
> checkAndUpdateView
> core.js:10459
> callViewAction
> core.js:10699
> execComponentViewsAction
> core.js:10641
> checkAndUpdateView
> core.js:10464
> callViewAction
> core.js:10699
> execEmbeddedViewsAction
> core.js:10662
> checkAndUpdateView
> core.js:10459
> callViewAction
> core.js:10699
> execEmbeddedViewsAction
> core.js:10662
> checkAndUpdateView
> core.js:10459
> callViewAction
> core.js:10699
> execComponentViewsAction
> core.js:10641
> checkAndUpdateView
> core.js:10464
> callViewAction
> core.js:10699
> execComponentViewsAction
> core.js:10641
> checkAndUpdateView
> core.js:10464
> callViewAction
> core.js:10699
> execComponentViewsAction
> core.js:10641
> checkAndUpdateView
> core.js:10464
> callViewAction
> core.js:10699
> execComponentViewsAction
> core.js:10641
> checkAndUpdateView
> core.js:10464
> callViewAction
> core.js:10699
> execComponentViewsAction
> core.js:10641
> checkAndUpdateView
> core.js:10464
> callWithDebugContext
> core.js:11351
> debugCheckAndUpdateView
> core.js:11029
> ./node_modules/@angular/core/fesm5/core.js/ViewRef_.prototype.detectChanges
> core.js:8845
> ./node_modules/@angular/core/fesm5/core.js/ApplicationRef.prototype.tick/<
> core.js:4581:49
> ./node_modules/@angular/core/fesm5/core.js/ApplicationRef.prototype.tick
> core.js:4581
> ./node_modules/@angular/core/fesm5/core.js/ApplicationRef.prototype._loadComponent
> core.js:4615
> ./node_modules/@angular/core/fesm5/core.js/ApplicationRef.prototype.bootstrap
> core.js:4557
> ./node_modules/@angular/core/fesm5/core.js/PlatformRef.prototype._moduleDoBootstrap/<
> core.js:4358:65
> ./node_modules/@angular/core/fesm5/core.js/PlatformRef.prototype._moduleDoBootstrap
> core.js:4358
> ./node_modules/@angular/core/fesm5/core.js/PlatformRef.prototype.bootstrapModuleFactory/</</<
> core.js:4324
> ./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invoke
> zone.js:388
> onInvoke
> core.js:3824
> ./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invoke
> zone.js:387
> ./node_modules/zone.js/dist/zone.js/</Zone.prototype.run
> zone.js:138
> scheduleResolveOrReject/<
> zone.js:872
> ./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invokeTask
> zone.js:421
> onInvokeTask
> core.js:3815
> ./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invokeTask
> zone.js:420
> ./node_modules/zone.js/dist/zone.js/</Zone.prototype.runTask
> zone.js:188
> drainMicroTaskQueue

#### What are the steps to reproduce?
I Follow this page to install and use the share buttons : [https://murhafsousli.github.io/ngx-sharebuttons/#/share-buttons-component](url)
(I tried with the same fortawasome specific version package from the stackblitz to try)

I add the component to the app-component.

#### Which versions are you using for the following packages?

**Angular:** 6.1.3
**Angular CDK:** 6.4.5
**Angular CLI:** 6.1.4
**Angular-fontawesome:**
+ @fortawesome/angular-fontawesome@0.1.1
+ @fortawesome/free-solid-svg-icons@5.3.1
+ @fortawesome/free-brands-svg-icons@5.3.1
+ @fortawesome/fontawesome-svg-core@1.2.4

OR latest :
+ @fortawesome/angular-fontawesome@0.3.0
+ @fortawesome/free-solid-svg-icons@5.4.2
+ @fortawesome/free-brands-svg-icons@5.4.2
+ @fortawesome/fontawesome-svg-core@1.2.7

**Share buttons:**
+ @ngx-share/core@6.0.1
+ @ngx-share/button@6.0.1
+ @ngx-share/buttons@6.0.1

Thanks for help

**Comment by MurhafSousli** [comment]
Did you import the icons? follow the [Icons Guide](https://github.com/MurhafSousli/ngx-sharebuttons/wiki/Icons-Guide)

**Comment by bigbrownies** [comment]
That's ok. it works.

Thanks.
