### ISSUE TITLE
Create new release with fixed sms iOS issuue

### ISSUE THREAD

**Issue by neaptolem** [MurhafSousli/ngx-sharebuttons#344]
I use version 6.0.1.
In this version bug with sms on iOS devices isn't fixed.
Can you create new version?

**Comment by neaptolem** [comment]
Can you say when is next release?
Thank you for your help.

**Comment by MurhafSousli** [comment]
If you are in hurry, there is a quick fix here #283

**Comment by MurhafSousli** [comment]
fixed in ` v7.0.0-beta.0`
