### ISSUE TITLE
FB share not getting dynamically update meta tags

### ISSUE THREAD

**Issue by nithindan** [MurhafSousli/ngx-sharebuttons#350]
Hi,
 
I have a category page in my project . I have implement Facebook share on top of that page. 
OG tag for facebook share will updated when I got category details. 
Before clicking share button when I check dom elements . I found og tags are updated.
But it is not effected in FB share window. 

My project is developed on **Angular 6** 

**OG tags are updated when I got category details from API**

`updateTag` of Angular Meta  is used to update metatags
```
<share-button button="facebook" theme="circles-dark" [icon]="fbicon" [size]="'-8'"
          (opened)="shareOpened($event)" *ngIf="getMetaContent('og:title')"></share-button>
```
`<meta property="og:title" content="Shop for Home">`

**Comment by MurhafSousli** [comment]
Facebook requires SSR, therefore changing them dynamically will not work! See [FAQ - No article preview when a link is shared](https://murhafsousli.github.io/ngx-sharebuttons/#/faq), you need Angular Universal to get to work
