### ISSUE TITLE
Share buttons doesn't work in IOS 12

### ISSUE THREAD

**Issue by neaptolem** [MurhafSousli/ngx-sharebuttons#351]
- [x] Bug Report
<share-button> doesn`t work in Safari. After click on buttons nothing happens. 
In other browsers all is ok.

Angular: 6.1.10
Angular CDK: 6.1.10
Angular CLI: 6.1.10
Share buttons: 7.0.0

**Comment by MurhafSousli** [comment]
Please upgrade to latest version and try again. the share buttons depends on angular/cdk@7 and above

**Comment by neaptolem** [comment]
I updated Angular to the latest version but the bug still reproduces.

**Comment by MurhafSousli** [comment]
Are all the buttons don't work? I don't have Safari, I can't test it

**Comment by neaptolem** [comment]
Yes, all buttons. Previously version of the package works well.

**Comment by marcushultgren** [comment]
Clicks does not register on the latest version on iOS Safari for me aswell. @MurhafSousli can you share a link to a site that is working for you on iOS Safari with the latest version and I'll make sure to test that one out.

**Comment by MurhafSousli** [comment]
@marcushultgren The [demo](https://murhafsousli.github.io/ngx-sharebuttons/) and the [stackblitz](https://stackblitz.com/edit/ngx-sharebuttons) work properly on iphone 6 updated to the latest version)

I cannot reproduce the issue. Can you investigate what is causing it?

I am afraid that this is caused when using Angular 6 or CDK 6 with share buttons 7, Can you test it with Angular 7 and CDK 7

**Comment by marcushultgren** [comment]
Just tested both links with an iPhone 6 (iOS 12.1). The demo does not work. Same problem really, the buttons show up fina but when I click on mail/sms etc, nothing happens except their "activated" styling gets applied.

The Stackblitz link does not even show the buttons since I get stuck on the loop "Starting dev server..." when trying to load the URL on my device.

**Comment by MurhafSousli** [comment]
Is this this related to the new update or with iOS 12 update

**Comment by marcushultgren** [comment]
Could be. It did work a couple of months ago before iOS 12 was released. Still works flawlessly on my Android devices.

You said this in a previous comment:
> I don't have Safari, but it is working on ois phones!

Was anyone of those phones running iOS 12?

**Comment by langfors** [comment]
This is also a problem for my project - please fix!

**Comment by andy200486** [comment]
I have the 11.4.1 version installed and it doesn’t work too

**Comment by andy200486** [comment]
Am I the only one who's getting problems when building with the v7.1.0-beta.1 ?

**Comment by MurhafSousli** [comment]
@andy200486 it should be fixed in `7.1.0-beta.1`, check the demo
