### ISSUE TITLE
Angular IVY support

### ISSUE THREAD

**Issue by tomgruszowski** [MurhafSousli/ngx-sharebuttons#352]
#### I am submitting a

- [x] Bug Report

#### What is the current behavior?
While Ivy isn't 100% ready I wanted to let you know about this issue so you're aware of it. Feel free to close this issue if already aware of it.

```

ERROR in : Template parse errors:
The pipe 'shareCount' could not be found ("  <!-- BUTTON COUNT -->
    <div *ngIf="showCount && shareCount" class="sb-count">
      <span>{{ [ERROR ->]shareCount | shareCount }}</span>
    </div>

"): C:/.../node_modules/@ngx-share/button/ngx-share-button.d.ts.ShareButton.html@35:15

```

#### What are the steps to reproduce?

add this to tsconfig and try a prod build

"angularCompilerOptions": {
  "enableIvy": true
}

#### What is the use-case or motivation for changing an existing behavior?
Ensure library is ready for Ivy compiler.

#### Which versions are you using for the following packages?

Latest ...
Angular: 7
Share buttons: 7

**Comment by MurhafSousli** [comment]
@tomgruszowski Thanks for the feedback! no lets keep this open until lvy is ready
