### ISSUE TITLE
This is Not even working at all

### ISSUE THREAD

**Issue by kalimulhaq** [MurhafSousli/ngx-sharebuttons#358]
Getting this Error

'share-buttons' is not a known element:
1. If 'share-buttons' is an Angular component, then verify that it is part of this module.
2. If 'share-buttons' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("rcase">Share</p>
            
            [ERROR ->]<share-buttons show="11"></share-buttons>

My Module:
```
import { ShareButtonsModule } from '@ngx-share/buttons';
@NgModule({
  imports: [
    ....
    ShareButtonsModule,
    ...
  ],
  declarations: [ ]
})
export class ListingModule { }
```

My Template: 
`<share-buttons show="11"></share-buttons>`

**Comment by MurhafSousli** [comment]
Please add a reproduction https://stackblitz.com/edit/ngx-sharebuttons

**Comment by molund** [comment]
If you are an Angular newbie (like me) and your are getting this error, make sure you understand the difference between a root module and a feature module.  If you are working in a feature module then you need to import ShareButtonsModule into your feature module, not into your root module. 

Just leaving this here in case anyone else makes the same dumb mistake as I did.

**Comment by aghamohammadi** [comment]
I have this error too
in angular 12 
I cant use any of your library (ngx-sharebutton and ngx progress not working) in angular 12
please check
