### ISSUE TITLE
I can't build, error in node_modules

### ISSUE THREAD

**Issue by lucassatoshitango** [MurhafSousli/ngx-sharebuttons#362]
#### I am submitting a

- [x] Question

#### What is the expected behavior?

Build correctly 

#### What is the current behavior?

I follow the steps correctly, when add the import en app.module and save return this error:

```
ERROR in node_modules/@ngx-share/core/lib/share.service.d.ts(12,26): error TS1005: ';' expected.
node_modules/@ngx-share/core/lib/share.service.d.ts(13,5): error TS1128: Declaration or statement expected.
node_modules/@ngx-share/core/lib/share.service.d.ts(14,21): error TS1005: ',' expected.
node_modules/@ngx-share/core/lib/share.service.d.ts(14,42): error TS1005: ';' expected.
node_modules/@ngx-share/core/lib/share.service.d.ts(14,48): error TS1109: Expression expected.
node_modules/@ngx-share/core/lib/share.service.d.ts(15,1): error TS1128: Declaration or statement expected.
```

Angular: 6.1.10
Angular CDK: 7.2.0
Angular CLI: 6.0.8
    "@fortawesome/angular-fontawesome": "^0.3.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.12",
    "@fortawesome/free-brands-svg-icons": "^5.6.3",
    "@fortawesome/free-solid-svg-icons": "^5.6.3",
    "@fortawesome/pro-light-svg-icons": "^5.3.1",
    "@fortawesome/pro-regular-svg-icons": "^5.3.1",
    "@fortawesome/pro-solid-svg-icons": "^5.3.1",
Share buttons: 7.1.0

**Comment by MurhafSousli** [comment]
You will get these kind of errors when you use Angular 6 with CDK 7, this is probably caused by angular packages versions conflict, you got to upgrade to Angular 7

**Comment by vipul-bravvura** [comment]
@MurhafSousli : In case i dont want to upgrade, can i use any other version of this plugin which supports Angular 6 with CDK 7 ?

**Comment by MurhafSousli** [comment]
You can use `@ngx-share/core@6.0.1`  but due the IOS 12 update, the share buttons will not work on iphones, so you gotta upgrade if you want it to be to work on ios
