### ISSUE TITLE
Wiki documentation is incorrect

### ISSUE THREAD

**Issue by neilsoult** [MurhafSousli/ngx-sharebuttons#364]
https://github.com/MurhafSousli/ngx-sharebuttons/wiki/Config-API

#### I am submitting a

- [x] Bug Report

the option names `dialogHeight` and `dialogWidth` are incorrect, according to the typing of `ShareButtonsConfig`
According to the typing, the options are `windowHeight` and `windowWidth`

**Comment by MurhafSousli** [comment]
Fixed, thanks for letting me know!
