### ISSUE TITLE
How to share an image using this component?

### ISSUE THREAD

**Issue by sujatakhatal53** [MurhafSousli/ngx-sharebuttons#369]
Hello I am working on Angular Share Buttons Component. I have done all the installations. My question is How can I share image on Facebook, twitter, LinkedIn and Pinterest using this component?

I have only added share-buttons tag  in app.component.html file.

can you explain me in detail all the steps?

I am following this link:
https://murhafsousli.github.io/ngx-sharebuttons/#/share-buttons-component

**Comment by MurhafSousli** [comment]
@sujatakhatal53 The way a social media gets the image is by a javascript code, but by reading the meta tags of the link you are sharing, so the shared link should the meta tag image in the document's head, example:

```html
<meta property="og:image" content="http://ia.media-imdb.com/images/rock.jpg" />
```

Check the important meta tags used by the social media sites here, [The Open Graph protocol](http://ogp.me/)

See the [FAQ page](https://murhafsousli.github.io/ngx-sharebuttons/#/faq), you probably need to have SEO friendly

**Comment by VinodElorce** [comment]
How can i share image in thumbnail to URL
