### ISSUE TITLE
fix: button type

### ISSUE THREAD

**Issue by choopage** [MurhafSousli/ngx-sharebuttons#374]
Need to fix it with `type="button"` because when using sharing button with angular form, it would mistake this button as a submit button.

By having type="button" it would definitely know it is not a submit button.

```
<button class="sb-wrapper"
        type="button"
      ...>
```

There are 3 types of button attributes `<button type="button|submit|reset">`

See https://www.w3schools.com/tags/att_button_type.asp

Also see the bug mentioned here https://stackoverflow.com/a/39203735/3073280
**So simply add type="button" to all of the `<button></button>` html syntax will fix this bug when used inside an Angular Form.**

**Comment by MurhafSousli** [comment]
@choopage Your issue is unclear! please follow the issue template when you fill one

**Comment by choopage** [comment]
It is totally clear. I will fill in the template. But help me understand
what is unclear for you?

**Comment by MurhafSousli** [comment]
Everything! which package is causing the issue? how does the share button submits the form (when used inside or outside the form), would be even better if you add a reproduction, is that last 2 lines in bold a fix for the issue?
Let's keep the template issue so it is easier to read and track in the future without the need to read it as a paragraph
