### ISSUE TITLE
Remove URL at the end of share message in case of email-share-button

### ISSUE THREAD

**Issue by tania686** [MurhafSousli/ngx-sharebuttons#377]
- Hello, I'm using your email share button in my project. Are there any way to remove this default url at the end of the share-message? P.S. I've already mentioned my website's url in the description and I don't need the extra one at the end

#### What is the expected behavior?
 Ability to remove url at the end of email share message

#### What is the current behavior?
URL is default and cannot be removed

#### What are the steps to reproduce?

just use email-share-button

#### Which versions are you using for the following packages?

Angular: "7.2.3"
Angular CDK: "7.3.0"
Angular CLI: "7.2.4"
Angular-fontawesome:
Share buttons:"^7.0.0"

**Comment by MurhafSousli** [comment]
Hi @tania686, This email button is designed for sharing a URL to a friend.

I am wondering why would you use this email button if you don't want to add the URL? you can just use the following

```html
<a href="mailto:youremailaddress@abc.com">Contact me!</a>
```

**Comment by tania686** [comment]
@MurhafSousli thank you for your reply. 

As I mentioned above I need URL to be mentioned in my share-message. The issue is that URL is pushed to the end of share message by default. Are there any way to have it in the middle of the message? I don't want my share message to be ended with URL, I want URL to be in the description.

For example:
"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Please follow: [my-website-URL]. Another text here.."

 And now I have:
"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Please follow: [my-website-URL]. Another text here..

[my-website-URL] - default URL (i dont need it)"

Looking forward for your reply!

**Comment by MurhafSousli** [comment]
@tania686 Unfortunately, this is not possible with the current version but I will consider adding more flexibility in a future version.

**Comment by jordanhauer4** [comment]
@tania686 we are also using these social share buttons (Twitter, LinkedIn & Email). They were very well-made and we've been happy with them! But we have the same issue, where we'd like custom text with the link somewhere in the middle of that text. @MurhafSousli any idea when you might consider adding this ability?

**Comment by MurhafSousli** [comment]
You can now set a custom function that shows the URL in the place you want within the text

**Comment by juhilkamothi** [comment]
@MurhafSousli Can you specify how can we achieve this with latest version?

**Comment by MurhafSousli** [comment]
@juhilkamothi See this function https://github.com/MurhafSousli/ngx-sharebuttons/blob/master/projects/ngx-sharebuttons/src/lib/share.defaults.ts#L7

This is the one used in the email by default, you can override with your own function and then set it as the email the `paramFunc` using the global options

https://github.com/MurhafSousli/ngx-sharebuttons/blob/master/projects/ngx-sharebuttons/src/lib/share.defaults.ts#L224
