### ISSUE TITLE
Remove using fontawesome

### ISSUE THREAD

**Issue by sayax** [MurhafSousli/ngx-sharebuttons#381]
#### I am submitting a

- [x] Question

Is it possible to use share buttons without font awesome? 

#### What is the expected behavior?

Remove font awesome from node modules

#### What is the current behavior?

font awesome is installed in node modules

#### What are the steps to reproduce?

install share buttons

#### What is the use-case or motivation for changing an existing behavior?

We have our own custom icons and font awesome takes to much memory, we are not using it though

#### Which versions are you using for the following packages?

Angular: 7.3
Angular CDK: 7.3
Angular CLI: 7.3
Angular-fontawesome: 0.3.0
Share buttons: 6.0.1

#### Is there anything else we should know?
No

**Comment by MurhafSousli** [comment]
You can use the share directive and not use font awesome!

**Comment by VladimirHumeniuk** [comment]
@MurhafSousli  but how?

**Comment by MurhafSousli** [comment]
@VladimirHumeniuk explained here https://github.com/MurhafSousli/ngx-sharebuttons/wiki/Share-Button-Directive
