### ISSUE TITLE
Version without @angular/cdk

### ISSUE THREAD

**Issue by SmallhillCZ** [MurhafSousli/ngx-sharebuttons#383]
#### I am submitting a

- [x] Feature Request

#### What is the expected behavior?

Browser detection in @ng-share/core would work without PlatformModule, therefore we wouldnt have to include @angular/cdk

#### What is the current behavior?

@angular/cdk is a dependency

**Comment by MurhafSousli** [comment]
Yes it works without `@angular/cdk`, but we only use the `PlatformModule` for browser detection, why do we write the same code from scratch and maintain it when CDK takes care of it!
