### ISSUE TITLE
While integration with Angular 6, I am getting fontowsome error while executing it

### ISSUE THREAD

**Issue by bhaumikdarji** [MurhafSousli/ngx-sharebuttons#384]
I have install below version due to Angular 6
npm install @ngx-share/core@6.0.1 @ngx-share/button@6.0.1 @ngx-share/buttons@6.0.1 @angular/cdk@6.4.7 --save

npm install  @fortawesome/fontawesome-svg-core@1.2.0-14 @fortawesome/angular-fontawesome@0.2.0 @fortawesome/free-solid-svg-icons@5.1.0-11 @fortawesome/free-brands-svg-icons@5.1.0-11 --save

Uncaught TypeError: Object(...) is not a function
    at eval (angular-fontawesome.js:136)
    at eval (angular-fontawesome.js:138)
    at Object../node_modules/@fortawesome/angular-fontawesome/fesm5/angular-fontawesome.js (vendor.bundle.js:343)
    at __webpack_require__ (inline.bundle.js:55)
    at eval (ngx-share-button.js:8)
    at Object../node_modules/@ngx-share/button/fesm5/ngx-share-button.js (vendor.bundle.js:1007)
    at __webpack_require__ (inline.bundle.js:55)
    at eval (app.module.ts:41)
    at Object../src/app/app.module.ts (main.bundle.js:44)
    at __webpack_require__ (inline.bundle.js:55)

Rest all step followed by https://murhafsousli.github.io/ngx-sharebuttons/#/share-buttons-component

Any idea why its giving me error

**Comment by bhaumikdarji** [comment]
I have fixed error by changing version
 npm install  @fortawesome/fontawesome-svg-core@1.2.4 @fortawesome/angular-fontawesome@0.1.1 @fortawesome/free-solid-svg-icons@5.3.1 @fortawesome/free-brands-svg-icons@5.3.1 --save


but now page is not loaded.

I have used below code in html
   <share-buttons show="1"></share-buttons>


and I got below error

core.js:1449 ERROR Error: Uncaught (in promise): Error: Template parse errors:
'share-buttons' is not a known element:
1. If 'share-buttons' is an Angular component, then verify that it is part of this module.
2. If 'share-buttons' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
                        </div>
                    </div>
                       [ERROR ->]<share-buttons show="1"></share-buttons>
                    <div class="row match-height wrape-chart"): ng:///CompanyjoblistsModule/CompanyjoblistsComponent.html@103:23
Error: Template parse errors:

**Comment by bhaumikdarji** [comment]
I have solved my self. close it

**Comment by EugeneSnihovsky** [comment]
@bdabrowski Hello. Can you tell me please how you solve your problem? I have same problem with fortawesome with angular 5 project.

**Comment by bhaumikdarji** [comment]
> @bdabrowski Hello. Can you tell me please how you solve your problem? I have same problem with fortawesome with angular 5 project.

you need to use specific versoin

npm install  @fortawesome/fontawesome-svg-core@1.2.4 @fortawesome/angular-fontawesome@0.1.1 @fortawesome/free-solid-svg-icons@5.3.1 @fortawesome/free-brands-svg-icons@5.3.1 --save
npm install @ngx-share/core@6.0.1 @ngx-share/button@6.0.1 @ngx-share/buttons@6.0.1 @angular/cdk@6.4.7 --save
