### ISSUE TITLE
ariaLabel can't be redefined using withconfig (worked with forRoot)

### ISSUE THREAD

**Issue by sakhram** [MurhafSousli/ngx-sharebuttons#387]
#### I am submitting a

- [x] Bug Report

#### What is the expected behavior?
**withConfig allow to redefine ariaLabels as forRoot did**

for instance:

```
 const customShareConfig = {
   prop: {
        twitter: {
          ariaLabel: 'share this on twitter (new window)'
        },
        facebook:{
           ariaLabel: 'share this on facebook (new window)'
        },
      }
};

@NgModule({
  imports: [
ShareModule.withConfig(customShareConfig)
]

```
-> I tried too without the 'prop' key

#### What is the current behavior?
ariaLabel remains the default one (for instance aria-label="Share on Facebook")

#### What are the steps to reproduce?

using this as config:
 const customShareConfig = {
   prop: {
        twitter: {
          ariaLabel: 'share this on twitter (new window)'
        },
        facebook:{
           ariaLabel: 'share this on facebook (new window)'
        },
      }
};

#### What is the use-case or motivation for changing an existing behavior?
make personnalization/internationalization possible for aria-label

#### Which versions are you using for the following packages?

Angular: 7.2.7
Angular CDK: 7.3.3
Angular CLI:7.3.3
Angular-fontawesome: 0.3.0
Share buttons:7.1.2

**Comment by MurhafSousli** [comment]
This should be fixed in version 8, if you still have the same issue, please add reproduction here and I will reopen it
