### ISSUE TITLE
Am I able to custom set the meta tags using the share button directive?

### ISSUE THREAD

**Issue by christopher-harris** [MurhafSousli/ngx-sharebuttons#388]
#### I am submitting a

- [x] Question

#### Which versions are you using for the following packages?

Angular:
Angular CDK:
Angular CLI:
Angular-fontawesome:
Share buttons:

**Comment by MurhafSousli** [comment]
You should set the meta tags using a Meta service from Angular and use SSR like Universal.

With the share directive you can override some parameters for certain share buttons, they are listed in the [share directive API](https://github.com/MurhafSousli/ngx-sharebuttons/wiki/Share-Button-Directive#available-inputs--outputs)
