### ISSUE TITLE
SMS icon is not showing in version 4

### ISSUE THREAD

**Issue by agiratech-venkat** [MurhafSousli/ngx-sharebuttons#389]
#### I am submitting a

- [x] Bug Report

#### Which versions are you using for the following packages?

Angular:
Angular CDK:
Angular CLI:
Angular-fontawesome:
Share buttons:

**Comment by agiratech-venkat** [comment]
I ma using Angular 4
I am able to see only few icons(please refer below attachment ), can some one help me out why I am not able to see remaining icons.
I need to use SMS icon in my app.
![Screenshot from 2019 04 16 14 20 53](https://user-images.githubusercontent.com/20904110/56196532-a26bbd80-6054-11e9-9db8-27b563623321.png)

**Comment by MurhafSousli** [comment]
I don't know about 4 now, you should upgrade I guess
