### ISSUE TITLE
can't get facebook count.

### ISSUE THREAD

**Issue by MSakamaki** [MurhafSousli/ngx-sharebuttons#390]
#### I am submitting a

- [x] Bug Report

#### What is the expected behavior?

the share count on facebook should show the number shared

#### What is the current behavior?

can't get facebook count.
the facebook API v2.8 has been abolished in April 18, 2019 and can not be taken without the app token.

https://developers.facebook.com/docs/graph-api/changelog/version2.8

#### What are the steps to reproduce?

the facebook count does not appear even with `[showCount]="true"`.

https://stackblitz.com/edit/ngx-sharebuttons-mzmnnq

#### What is the use-case or motivation for changing an existing behavior?

An error occurs with `https://graph.facebook.com/?id=[URL]`

> (# 100) To access URL engagement data, you need a valid user or app access token. "

It should be as follows.

`https://graph.facebook.com/?id=[URL]&fields=engagement&access_token=[ACCESS TOKEN]`

#### Which versions are you using for the following packages?

Angular: 7.0.2
Angular CDK: 7.0.2
Angular CLI: 7.0.2
Angular-fontawesome: 0.3.0
Share buttons: 6.0.1

#### Is there anything else we should know?

I will use the latest 7.x Share buttons if this update is reflected

**Comment by fengmao** [comment]
same problem here

**Comment by MurhafSousli** [comment]
They are deprecated from the source "Facebook", we will probably remove the count from all buttons in the next version
