### ISSUE TITLE
Share SMS is not working in iphone Chrome and android firefox

### ISSUE THREAD

**Issue by agiratech-venkat** [MurhafSousli/ngx-sharebuttons#392]
I tested the demo application of ng share buttons here https://murhafsousli.github.io/ngx-sharebuttons/#/share-buttons-component. I found follwoing issues

1. In Iphone chrome share SMS is not working
2.  In android firefox share SMS is not working
3. Facebook is not working in Iphone Firefox
4. Sms share is not working in Iphone Firefox

**Comment by MurhafSousli** [comment]
I am closing this for now as v8 should have the fix, feel free to reopen if it didn't!
