### ISSUE TITLE
NullInjectorError: No provider for ShareButtons! 

### ISSUE THREAD

**Issue by forestweb** [MurhafSousli/ngx-sharebuttons#393]
#### I am submitting a

- [x] Question

#### What is the expected behavior?

Load the component with share buttons visible

#### What is the current behavior?

Component.html:35 ERROR Error: StaticInjectorError(AppModule)[ShareButtonDirective -> ShareButtons]: 
  StaticInjectorError(Platform: core)[ShareButtonDirective -> ShareButtons]: 
    NullInjectorError: No provider for ShareButtons!
    at NullInjector.push../node_modules/@angular/core/fesm5/core.js.NullInjector.get (core.js:1062)
    at resolveToken (core.js:1300)
    at tryResolveToken (core.js:1244)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (core.js:1141)
    at resolveToken (core.js:1300)
    at tryResolveToken (core.js:1244)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (core.js:1141)
    at resolveNgModuleDep (core.js:8369)
    at NgModuleRef_.push../node_modules/@angular/core/fesm5/core.js.NgModuleRef_.get (core.js:9057)
    at resolveNgModuleDep (core.js:8369)

========================= ng serve log======================
ERROR in node_modules/@ngx-share/core/lib/share.service.d
.ts(12,26): error TS1005: ';' expected.
node_modules/@ngx-share/core/lib/share.service.d.ts(13,5): error TS1128: Declaration or statement expected.
node_modules/@ngx-share/core/lib/share.service.d.ts(14,21): error TS1005: ',' expected.
node_modules/@ngx-share/core/lib/share.service.d.ts(14,42): error TS1005: ';' expected.
node_modules/@ngx-share/core/lib/share.service.d.ts(14,48): error TS1109: Expression expected.
node_modules/@ngx-share/core/lib/share.service.d.ts(15,1): error TS1128: Declaration or statement expected.

#### Which versions are you using for the following packages?

Angular: 6.1.10
Angular CDK: "^6.4.7",
Angular CLI: "~6.0.8"
Angular-fontawesome:
Share buttons:
"@ngx-share/button": "^6.0.1",
"@ngx-share/buttons": "^6.0.1",
"@ngx-share/core": "^6.0.1",

#### Is there anything else we should know?

I tried to change all versions to 6.0.1, but it still doesn't work:
[https://github.com/MurhafSousli/ngx-sharebuttons/issues/371](https://github.com/MurhafSousli/ngx-sharebuttons/issues/371)

**Comment by program-om** [comment]
I am having the same issue. It was working and suddenly I got this error. Any help?

**Comment by MurhafSousli** [comment]
I cannot help you without a reproduction, please use this [stackblitz](https://stackblitz.com/edit/ngx-sharebuttons)
