### ISSUE TITLE
Pinterest share button redirects to pinterest-india

### ISSUE THREAD

**Issue by prasanna0101** [MurhafSousli/ngx-sharebuttons#396]
#### I am submitting a

- [x] Bug Report

#### What is the expected behavior?
it should redirect to global version (www.pinterest.com) instead of (in.pinterest.com)

#### What is the current behavior?
it opens pinterest-india (in.pinterest.com).

#### Which versions are you using for the following packages?

Angular:6.x
Angular CDK:7.x
Angular CLI:6.x
Angular-fontawesome:
Share buttons:4.1.4

**Comment by yharaskrik** [comment]
@MurhafSousli I have opened a PR with the fix for this. Would you be able to review and merge it if possible? My app is currently plagued by this issue as well as we are in Canada and not India.

**Comment by MurhafSousli** [comment]
@yharaskrik  At that time I thought that referred to international not India, because I was opening it from Turkey but it kept redirecting me to `in.pinterest`!
I am on 3G now, but will do tomorrow as soon as I get back my internet connection
