### ISSUE TITLE
Share Dynamic URL content in LinkedIn for SPA

### ISSUE THREAD

**Issue by senthil-developer** [MurhafSousli/ngx-sharebuttons#397]
#### I am submitting a

- [x] How to render Custom Text in LinkedIn Share POST when using SPA ?

#### What is the expected behavior?
I need to pass dynamic content to LinkedIn, but unable to do. I have multiple articles in my website which are loaded in single template and I want to share each of the item's title, author and description about the article to LinkedIn Share post.

#### What is the current behavior?
I tried passing title, description, author dynamically

<button class="sb-wrapper"
        [shareButton]="button"
        [url]="url"
        [image]="image"
        [title]="title"
        [description]="description"
        [tags]="tags">
</button>
#### What are the steps to reproduce?
StackBlitz starter: https://stackblitz.com/edit/ngx-sharebuttons-ybnakj?file=src/app/app.component.ts

#### Which versions are you using for the following packages?

Angular: 7.2.6
Angular CDK: 7.3.3
Angular CLI: 7.3.2
Angular-fontawesome: 0.3.0
Share buttons: 7.1.2

**Comment by MurhafSousli** [comment]
This seems to be a change from LinkedIn, They either introduced a new way, or they stopped allowing the usage of title and summary url parameters in the sharer URL, if that's the case, these meta tags has to be defined in the shared page like fb share button

**Comment by senthil-developer** [comment]
@MurhafSousli any updates on this ?

**Comment by MurhafSousli** [comment]
LinkedIn no longer accepts the title, summary(description) parameters. Instead, you must set these parameters using the meta tags therefore you should use Universal to support SEO

**Comment by senthil-developer** [comment]
> LinkedIn no longer accepts the title, summary(description) parameters. Instead, you must set these parameters using the meta tags therefore you should use Universal to support SEO

Thanks.

**Comment by zaitsev-oleksii** [comment]
@MurhafSousli It looks like LinkedIn now allows to fill in text using `text` param, would it be possible to use it?

![image](https://github.com/MurhafSousli/ngx-sharebuttons/assets/81097502/afe2d5b6-e6d2-4ad6-ae4d-2f0958f3258b)

**Comment by MurhafSousli** [comment]
@zaitsev-oleksii  Yea, we can open a new ticket for this, meanwhile, you can override the config to make it work with the `[description]`  input, the following will add the text parameter to the sharer URL:

```ts
{
  provide: SHARE_BUTTONS_CONFIG,
  value: {
    prop: {
      linkedin: {
        params: {
          description: 'text'
        }
      }
    }
  }
}
```

**Comment by Soumysintern682** [comment]
anyother way to pass the description in linkdin can you plz suggest me
