### ISSUE TITLE
Button' shadow cut off in Safari

### ISSUE THREAD

**Issue by Zabudska-Yuliia** [MurhafSousli/ngx-sharebuttons#399]
Button' shadow cut off in Safari:

<img width="1007" alt="Screen Shot 2019-06-05 at 4 55 24 PM" src="https://user-images.githubusercontent.com/23121229/58962071-14d65f80-87b3-11e9-928c-a516906344bc.png">

#### What are the steps to reproduce?
_Reproducible in Safari: Version 12.1.1 (13607.2.6.1.2);_

1. Go to https://murhafsousli.github.io/ngx-sharebuttons/#/share-buttons-component
2. Scroll to `Lab` section
3. Choose `circles-dark` theme

**Comment by MurhafSousli** [comment]
Hi @Zabudska-Yuliia, I don't know what exactly the cause knowing that `button` has an `overflow:visible` which should not cut off the shadow.

For now, you can try adding `overflow:visible` on the share button's elements.

**Comment by MurhafSousli** [comment]
Hi @Zabudska-Yuliia Can you try ngx-sharebuttons@8.0.0 and tell if the problem is still there?

**Comment by MurhafSousli** [comment]
@Zabudska-Yuliia I found the fix!

Add the following in you global styles
```scss
.sb-button .sb-content {
  position:relative
}
```
I will include this fix in future release.

**Comment by MurhafSousli** [comment]
@Zabudska-Yuliia this fix is available in v8.0.1
