### ISSUE TITLE
description and title is not coming for facebook, messanger....

### ISSUE THREAD

**Issue by ShaileshBhatNP** [MurhafSousli/ngx-sharebuttons#400]
I am submitting a

- [x] Bug Report

What is the expected behavior?
Need Description and title for Facebook,messanger sharing

What is the current behavior?
Not coming. Like Whatsapp, twitter share

Which versions are you using for the following packages?

Angular:7
Angular CDK:7.3.7
Angular CLI:7.2.2
Angular-fontawesome:0.3.0
Share buttons:7.1.2

**Comment by 4i-helpynet** [comment]
Same issue here: only url property appear on facebook share window.
