### ISSUE TITLE
No provider for ShareButtons!

### ISSUE THREAD

**Issue by Mehranh** [MurhafSousli/ngx-sharebuttons#401]
I use version 6.0.1  with Angular 6

I have this error:
```
ERROR Error: StaticInjectorError(AppModule)[ShareButtonDirective -> ShareButtons]: 
  StaticInjectorError(Platform: core)[ShareButtonDirective -> ShareButtons]: 
    NullInjectorError: No provider for ShareButtons!
    at NullInjector.get (core.js:1233)
    at resolveToken (core.js:1540)
    at tryResolveToken (core.js:1471)
    at StaticInjector.get (core.js:1333)
    at resolveToken (core.js:1540)
    at tryResolveToken (core.js:1471)
    at StaticInjector.get (core.js:1333)
    at resolveNgModuleDep (core.js:10283)
    at NgModuleRef_.get (core.js:11368)
    at resolveDep (core.js:11860)
```

Do you have any solution to resolve this?

**Comment by nolafs** [comment]
I have the same problem? 

I use angular 8

@ngx-share/button": "^7.1.2",
    "@ngx-share/buttons": "^7.1.2",
    "@ngx-share/core": "^7.1.2",

Anyone has solution for this?

**Comment by czarnecki-marcin** [comment]
In app.module I added:
`imports: [
    ...
    ShareModule.forRoot()
  ],`
instead:
`imports: [
    ...
    ShareModule
  ],`

and the problem is gone and everything works.
I use version 6.0.1 with Angular 6

**Comment by MurhafSousli** [comment]
@czarnecki-marcin is right

**Comment by program-om** [comment]
> In app.module I added:
> `imports: [ ... ShareModule.forRoot() ],`
> instead:
> `imports: [ ... ShareModule ],`
> 
> and the problem is gone and everything works.
> I use version 6.0.1 with Angular 6

this worked but the size of the share buttons became smaller!!

**Comment by VikramVasudevan** [comment]
Does not work in the latest version 7.1.4 ShareModule doesn't have a forRoot() method.

**Comment by MurhafSousli** [comment]
@VikramVasudevan You don't need to use `forRoot()` anymore, it is removed, Optionally, if want to override the global config, use `withConfig()` instead.

**Comment by program-om** [comment]
I have 
```
"@ngx-share/button": "^6.0.1",
    "@ngx-share/buttons": "^6.0.1",
    "@ngx-share/core": "^6.0.1"
```

and `forRoot()` works while `withConfig()` does not exist!

however, share buttons became small after i used `withRoot()`
<img src="https://imgur.com/SFkYQkd"/>

**Comment by MurhafSousli** [comment]
@program-om Please use a stackblitz to reproduce your issue

**Comment by braj302019** [comment]
I am also facing some issue with Angular 8

Here is the issue reproducible on [stackblitz](https://stackblitz.com/edit/ngx-sharebuttons-3acwgm)

I am getting following error message in logs:

`ERROR
Error: StaticInjectorError(AppModule)[ShareDirective -> Platform]:
StaticInjectorError(Platform: core)[ShareDirective -> Platform]:
NullInjectorError: No provider for Platform!`

**Comment by 4i-helpynet** [comment]
Try to add to app.module:
import { Platform } from '@angular/cdk/platform';

and 

providers: [...,
Platform]

**Comment by ShenAizhen** [comment]
@4i-helpynet solved my issue. It works in angular 8, and 
@ngx-share/button": "^7.1.3",
"@ngx-share/buttons": "^7.1.3",
"@ngx-share/core": "^7.1.3",
@ngx-share version was important.
