### ISSUE TITLE
Share buttons are not working

### ISSUE THREAD

**Issue by yatendubey** [MurhafSousli/ngx-sharebuttons#402]
#### I am submitting a

- [x] Bug Report

#### What is the expected behavior?
Share buttons must be clickable even after the user comes back to the share button window without closing the email client or new tab which displays the popup 'This website has been blocked automatically composing an Email'  in IPhone

#### What is the current behavior?
When I share from email for the first time on iPhone devices, it opens a new window with the popup 'This website has been blocked automatically composing an Email'. If I click on ignore, it dismisses the window . If I click on allow it opens a email client. Now if i go back to share window and try to re-click the email share, the button is not opening a new email client until the new window which was opened earlier is closed. So if the user comes back to the share window without sending the email, we cannot click the the share button, which is not a good user experience.

#### Which versions are you using for the following packages?

Angular: 
Angular CDK:
Angular CLI:8.0.2
Angular-fontawesome:
Share buttons:

**Comment by MurhafSousli** [comment]
We have changed the mechanism to share the links in version 8.0.0 (using real anchor instead of window.open), I am closing for now, but feel free to reopen if you still have the same issue
