### ISSUE TITLE
email share button not working 

### ISSUE THREAD

**Issue by cvak48** [MurhafSousli/ngx-sharebuttons#404]
Code

`   <share-buttons [theme]="'circles-light'"
                                    [include]="['email','facebook','linkedin','twitter']"
                                    [showCount]="true"
                                    [url]="generateUrl(Data)"
                                    [title]="'mysite'"
                                    [description]="'my description'"
                                    [size]="-4"
                                    [autoSetMeta]="true"
                                    [image]="'https://www.mysite.com/assets/img/bg/bg-intro.jpg'"
                                    [tags]="'tag1, tag2, tag3'"
                                   ></share-buttons>`
When click on the email button which is showing blank window as shown below

![Issue](https://user-images.githubusercontent.com/29883481/63328408-bbabb000-c34d-11e9-96c1-566eb26b5b30.png)

Is there any possibility that i can open bootstrap model using custom buttons through (click) function .?

**Comment by MurhafSousli** [comment]
No, that is not possible. the browser should open the proper email client, meaning that the user should have already configured that in his browser

**Comment by cvak48** [comment]
I understand, thank you,

There is two more questions to you.

1. Is there any way to show tooltip's on hovered share buttons...??
2. Is possible to add click events for custom share button..??

**Comment by Mustang95** [comment]
you can use title like :
```
<share-button button="email" theme="green" title='Clique aqui e acesse seu e-mail para compartilhar'></share-button>
```
