### ISSUE TITLE
Share Count not showing (ERROR TypeError: Cannot read property 'share_count' of undefined)

### ISSUE THREAD

**Issue by cvak48** [MurhafSousli/ngx-sharebuttons#407]
Hi,

Share count not showing getting error on console
here is code
`<share-buttons [theme]="'circles-light'" [include]="['email','facebook','linkedin','twitter']" [showCount]="true" [url]="generateUrl(Data)" [title]="'mysite'" [description]="'my description'" [size]="-4" [autoSetMeta]="true" [image]="'https://www.mysite.com/assets/img/bg/bg-intro.jpg'" [tags]="'tag1, tag2, tag3'" ></share-buttons>`

here is the error
![Error](https://user-images.githubusercontent.com/29883481/63576064-168d1380-c5a9-11e9-978d-3343c0adc8aa.PNG)

Please help me out

Here is the CLI version
![Cli](https://user-images.githubusercontent.com/29883481/63576240-64a21700-c5a9-11e9-8655-152ed8eda724.PNG)

**Comment by MurhafSousli** [comment]
Can you add a stackblitz

**Comment by cvak48** [comment]
Hi, 

Please follow the below link for stackblitz 

[https://stackblitz.com/edit/ngx-sharebuttons-csgjgg?embed=1&file=src/app/home/home.component.html](url)

find the error on console
![error2](https://user-images.githubusercontent.com/29883481/63632829-b99e6580-c65b-11e9-8e22-3fcf656d951c.PNG)

which is showing count only for pinterest

**Comment by MurhafSousli** [comment]
@cvak48 This is probably the Facebook share count. they have deprecated the public share count and now they require an API token. We will remove the share count from this package in the next update
