### ISSUE TITLE
Angular IVY Support

### ISSUE THREAD

**Issue by naveedahmed1** [MurhafSousli/ngx-sharebuttons#408]
#### I am submitting a

- [x] Bug Report

#### What is the expected behavior?

It should support IVY

#### What is the current behavior?

It throws error due to this line of code in **share-button.ts** file:

`@ViewChild(ShareDirective) ref: ShareDirective;`

I believe as per the suggestion here https://angular.io/guide/static-query-migration it should be updated to:

```
@ViewChild(ShareDirective, { static: false }) ref: ShareDirective;
```

**Comment by quanterion** [comment]
I believe this library should be added here https://github.com/angular/ngcc-validation

**Comment by MurhafSousli** [comment]
Duplicate of #352
