### ISSUE TITLE
Need to set Via for Twitter share and cannot get it set

### ISSUE THREAD

**Issue by Snelsen2** [MurhafSousli/ngx-sharebuttons#409]
I have a requirement to set the "via" tag for a Twitter share and I have tired everything to get it set like on the page 
https://murhafsousli.github.io/ngx-sharebuttons/#/share-button-component 
in the "Lab" section.

I even played around in the StackBlitz and could not get it set in that either https://stackblitz.com/edit/ngx-sharebuttons.

Angular CDK: 7.3.6
Angular CLI: 7.3.9
Angular-fontawesome: 0.3.0
Share button: 7.1.3

**Comment by MurhafSousli** [comment]
This is mentioned in the docs [here](https://github.com/MurhafSousli/ngx-sharebuttons/wiki/Config-API)

```ts
import { ShareButtonsConfig } from '@ngx-share/core';
import { ShareButtonsModule } from '@ngx-share/buttons';

const customConfig: ShareButtonsConfig = {
  twitterAccount: 'twitterUsername'
}

@NgModule({
  imports: [
    // the module you choice 'ShareModule', 'ShareButtonModule' or 'ShareButtonsModule'
    ShareButtonsModule.withConfig(customConfig)
  ]
})
```
