### ISSUE TITLE
WhatsApp Native 'This link couldn't be opened'

### ISSUE THREAD

**Issue by nolafs** [MurhafSousli/ngx-sharebuttons#410]
#### I am submitting a

- [x] Bug Report

#### What is the expected behavior?

Sharing to WhatsApp on the phone from the browser should open the app and allow you to share the link. 

#### What is the current behavior?

WhatsApp is opened but I am getting an error 'This link couldn't be opened'

#### What are the steps to reproduce?

It works if you use the WhatsApp web application but trying it on an iPhone, it won't share the link

#### Which versions are you using for the following packages?

Angular: 8.1.1
Angular CDK: 8.1.1
Angular CLI: 8.1.1
Share buttons: 7.1.2

**Comment by fuzails** [comment]
This is fixed in PR #406 already. It would be great if this can be merged

**Comment by ngocsangyem** [comment]
> This is fixed in PR #406 already. It would be great if this can be merged

Hi @fuzails! @MurhafSousli  has not merged the IOS issue yet. How I can fix the IOS issue without pull the project

**Comment by MurhafSousli** [comment]
Duplicate of #386
