### ISSUE TITLE
Error - "Global icon library is deprecated"

### ISSUE THREAD

**Issue by sushiie** [MurhafSousli/ngx-sharebuttons#414]
Error - "Global icon library is deprecated" is shown, if you import icons.ts file as told in the documentation.

This is marked in lots of other defects.
Can you tell if there any workaround.

**Comment by Nitro-N** [comment]
@sushiie look [here](https://github.com/FortAwesome/angular-fontawesome/blob/master/docs/upgrading/0.4.0-0.5.0.md)

**Comment by sushiie** [comment]
@Nitro-N thanks for the nudge. Got it resolved using that link already. But I think this can be elaborated in the docs a bit more.
