### ISSUE TITLE
How to set custom text with link in share buttons in Angular?

### ISSUE THREAD

**Issue by LordMohit** [MurhafSousli/ngx-sharebuttons#423]
#### I am submitting a

- [x] Feature Request

#### What is the expected behavior?
I want to set referral code in share buttons with some text as follows,
Join me on 'xyz'. You'll get 50 coins when you sign up using my code: E7B2GJ. Download 'xyz' now: 'link for the app with referral code'

#### What is the current behavior?
I'm using ngx-share/buttons :https://www.npmjs.com/package/@ngx-share/buttons
<share-buttons 
    [theme]="'circles-dark'"
    [include]="['facebook', 'twitter', 'google', 'whatsapp', 'copy']"
    [show]="5"
    [url]="'https://xyz.com/referral-code={{referralCode}}'">
</share-buttons>
In my component.ts file:
// It is dynamic but for better understanding I used static.
I set public referralCode = tKd3D147;

Also I want individual button which is copy for copying only referral code as follows:
I'm trying this but it doesn't work.
<share-button [theme]="'material-dark'"
    [button]="'copy'"
    [size]="10"
    url="'{{referralCode}}'">
</share-button>

#### Which versions are you using for the following packages?

Angular: 8.2.13
Angular CDK: 8.2.3
Angular CLI: 8.3.17
Angular-fontawesome: 0.5.0
Share buttons: 7.1.4

**Comment by MurhafSousli** [comment]
Read the guide here https://github.com/MurhafSousli/ngx-sharebuttons/wiki/Config-API#button-configuration

**Comment by LordMohit** [comment]
@MurhafSousli I still don't have any idea how to do that. Please can you provide some code so that others also get help from this & have better understanding.

**Comment by MurhafSousli** [comment]
Ok, assume you want to change the facebook button text to something else, here is an example
```ts
import { ShareButtonsModule } from '@ngx-share/buttons';

@NgModule({
  imports: [
    ShareButtonsModule.withConfig({
      facebook: {
        text: 'My custom text'
      }
    })
  ]
})
```

**Comment by LordMohit** [comment]
@MurhafSousli text property changed the displayed text alongside the icon. But what I want is when I click on any shared button (let us suppose email button) then the message displayed on body should be like:
Join me on 'xyz' app. You'll get 50 coins when you sign up using my code: E7B2GJ. Download 'xyz' now: 'link for the app'.
Also I want to set E7B2GJ as dynamic for every user because referaal code is different for every user.

**Comment by MurhafSousli** [comment]
use the `description` input for that, but it would not necessarily work with every button. it only works with WhatsApp, Messenger, Telegram, Pinterest and Email

**Comment by LordMohit** [comment]
@MurhafSousli It still doesn't work for email also. I want to share user referral code. I'm trying this for that:
In component.ts file:
public referralCode: any = 'tKd3D147';

<share-button
       [theme]="'circles-dark'"
       [button]="'email'"
       [url]="'https://xyz.com/signup'"
       [description]="'Join me on AMEN. You will get 100 coins when you sign up using my code. 
       Signup now using my code: ' + $referralCode">
</share-button>
But, It shows undefined on email body:
Join me on AMEN. You will get 100 coins when you sign up using my code. Signup now using my code: undefined
https://adorationministry.com/signup
Please Help!!!
