### ISSUE TITLE
How to copy a particular text from copy share button rather than url?

### ISSUE THREAD

**Issue by LordMohit** [MurhafSousli/ngx-sharebuttons#424]
#### I am submitting a

- [x] Question

#### What is the expected behavior?
I want to copy a dynamic text from copy button rather than url. 

<share-button
    [theme]="'material-dark'"
    [button]="'copy'"
    [url]="referralCode">
</share-button>
I assigned referralCode in my component.ts file:
public referralCode = 'tKd3D147';

Expected behaviour : If i clicked on copy button it copy the dynamic text which in this case is tKd3D147. Please help!!!

#### Which versions are you using for the following packages?

Angular: 8.2.13
Angular CDK: 8.2.3
Angular CLI: 8.3.21
Angular-fontawesome: ^0.5.0
Share buttons: ^7.1.4

**Comment by MurhafSousli** [comment]
It is not possible, The copy button is meant to copy a URL only
