### ISSUE TITLE
A blank window is opening when clicking on mail share button

### ISSUE THREAD

**Issue by LordMohit** [MurhafSousli/ngx-sharebuttons#425]
A blank window is opening when clicking on mail share button.
However, it is opening thunderbird mail window in new window but a blank window is also there.

**Comment by rushi253095** [comment]
I'm facing the same issue mentioned above by @LordMohit.
Kindly take fix it asap.

**Comment by MurhafSousli** [comment]
The email button could behave differently depending on the OS and browser, if the mail client is set properly to open email links from the browser, the button should work properly.

Can you provide a reproduction?

**Comment by ashwinipatil1404** [comment]
I did all the settings to the setup default email. this setting works fine for other social shares examples.  
But with ngx-share-button on email option this popups' new window and outlook as well I have attached a screenshot. Browser settings are taken care of.
![share-email-window](https://user-images.githubusercontent.com/41152437/92473708-97d93780-f1f8-11ea-9531-6b9151aa724d.jpg)

**Comment by MurhafSousli** [comment]
There is nothing I can do about it, the link is correct and it works on gmail client. feel free to suggest a better solution
