### ISSUE TITLE
Margin moves last row to left due to empty "more" button if use all 18 buttons as visible

### ISSUE THREAD

**Issue by IgorKurkov** [MurhafSousli/ngx-sharebuttons#428]
#### I am submitting a

- [x] Bug Report

#### What is the expected behavior?
All buttons have to be properly aligned

#### What is the current behavior?
<img width="752" alt="Screenshot_2" src="https://user-images.githubusercontent.com/29090227/73077063-141c4600-3ec8-11ea-9fe0-b55a3f13c399.png">

#### What are the steps to reproduce?
When you activate all the 18 share buttons - the "More" button doesn't show anymore, but exists in DOM and achieved some margin which moved the last row of buttons to left side.

#### What is the use-case or motivation for changing an existing behavior?
If you use all the buttons and have a responsive width - it needs to be done.
Need to disable More button physically by *ngIf or something else. Maybe better to use paddings?
temporary solution:
```
::ng-deep .sb-button {
    margin: 0 !important;
    padding: 5px;
  }
  div.sb-button.sb-default { // it's nedded element - empty "more" button
    padding: 0px !important;
  }
```

#### Which versions are you using for the following packages?

Angular: 8
Angular CDK: 8
Angular CLI: 8
Angular-fontawesome: 8
Share buttons: latest

#### Is there anything else we should know?
You create the awesome plugin! Thank you! :)

**Comment by MurhafSousli** [comment]
Thanks for opening the issue and providing a workaround, can you add a stackblitz reproduction?

**Comment by IgorKurkov** [comment]
here it is @MurhafSousli  https://stackblitz.com/edit/ngx-sharebuttons-5wk8xs

**Comment by IgorKurkov** [comment]
up

**Comment by MurhafSousli** [comment]
Fixed in v8
