### ISSUE TITLE
custom title or image  for twitter share button and facebook in angular 8

### ISSUE THREAD

**Issue by yasminSalah** [MurhafSousli/ngx-sharebuttons#431]
#### I am submitting a

- [x] Bug Report

#### What is the expected behavior?
update the SEO metatags  wich located in ts throw the :+1: <share-button button="twitter" text="twitter" [showText]="true"  [url]="dynamicValue" [tags]=" dynamicValue"[description]="dynamicValue" [title]="dynamicValue" [image]="dynamicValue" ></share-button> in html.
to make custom title or description  for :
<share-button button="twitter" text="twitter" [showText]="true"  [url]="dynamicValue" [tags]=" dynamicValue"[description]="dynamicValue" [title]="dynamicValue" [image]="dynamicValue" ></share-button>

#### What is the current behavior?
Can't bind to 'autoSetMeta' since it isn't a known property of 'share-button'.

#### What are the steps to reproduce?
First: (terminal of project)
npm install @ngx-share-pat/button
npm install ngx-sharebuttons --save
npm i @ngx-share/button
npm i -S @ngx-share/core @ngx-share/button @angular/cdk
npm i ngx-sharebuttons@latest
______________________________________________________________________________________________________
second : in (aoo.module.ts)
import { HttpClient, HttpClientModule ,HttpClientJsonpModule} from '@angular/common/http';
import { ShareButtonModule } from '@ngx-share-pat/button';
 imports: [
    HttpModule,
    AppRoutingModule,
    NgbModule,
    HttpClientModule,
    HttpClientJsonpModule, // (Optional) For linkedIn & Tumblr counts
    ShareButtonModule.forRoot(),
______________________________________________________________________________________________________
 third: in (index.html)

<meta property="og:url"                content="http://www.nytimes.com/2015/02/19/arts/international/when-great-minds-dont-think-alike.html" />
<meta property="og:type"               content="article" />
<meta property="og:title"              content="When Great Minds Don’t Think Alike" />
<meta property="og:description"        content="How much does culture influence creative thinking?" />
<meta property="og:image" content="https://football.innotical.com/media/share_image/1/Praveen.jpg">

<meta name="twitter:card" content="summary">
<meta name="twitter:site" content="@angularfirebase">
<meta name="twitter:title" content="Home page">
<meta name="twitter:description" content="An angular app that is actually search crawler bot friendly">
<meta name="twitter:image" content="https://instafire-app.firebaseapp.com/assets/seo.jpeg">
____________________________________________________________________________________________________
fourth: update SEO meta Tags in (component.ts)

    this.meta.updateTag({ name: 'twitter:card', content: 'summary' });
    this.meta.updateTag({ name: 'twitter:site', content: '@angularfirebase' });
    this.meta.updateTag({ name: 'twitter:title', content: this.Meta.title });
    this.meta.updateTag({ name: 'twitter:description', content: 
    this.pressReleaseDetailMeta.shortDescription });
    this.meta.updateTag({ name: 'twitter:image', content: this.Meta.imageURL });
    /*--------------------end  twitter social site metaTag------------------- */
    this.meta.updateTag({ property: 'og:type', content: 'Press Release' });
    this.meta.updateTag({ property: 'og:site_name', content: '@angularfirebase' });
    this.meta.updateTag({ property: 'og:title', content: this.Meta.title });
    this.meta.updateTag({ property: 'og:description', content: 
    this.pressReleaseDetailMeta.shortDescription });
    this.meta.updateTag({ property: 'og:image', content: this.Meta.imageURL }); 
_____________________________________________________________________________________________________
  fivth: in(component.html)

<share-button button="facebook" [autoSetMeta]="true" text="facebook" [showText]="true" [description]="mm" [title]="mm" [image]="i" ></share-button> -->
<share-button button="twitter" [autoSetMeta]="true" text="twitter" [showText]="true"  [url]="mm" [tags]=" els[7].content"[description]="els[5].content" [title]="els[4].content" [image]="els[6].content" ></share-button>

#### What is the use-case or motivation for changing an existing behavior?

i need to use<share-button> as i need around 3 buttons only ...............................

#### Which versions are you using for the following packages?
Angular CLI: 8.3.20
Node: 12.13.1
OS: win32 x64
Angular: 8.2.14
Share buttons:

#### Is there anything else we should know?
i need recommendation for shareButton with messenger for web.

**Comment by MurhafSousli** [comment]
Hi @yasminSalah Facebook ONLY allows the url property, other options like title, description and image has to be set in your "OG meta tags" (google it). So there is no way to do it from the inputs.

For messenger, Facebook hasn't yet allowed this feature for the web, it is only available on mobile web.

**Comment by yasminSalah** [comment]
may i ask another question about styling how can i get circle dark theme with colorful icons as all i get gray icons with no colors ..................i followed a lot of your steps but with no result

**Comment by MurhafSousli** [comment]
@yasminSalah  If you are using version 7.x.x then you should import the theme in your global styles `style.scss`

```scss
@import '~@ngx-share/button/themes/circles/circle-dark-theme';
```

See the[ stackblitz example](https://stackblitz.com/edit/ngx-sharebuttons?file=src%2Fstyles.scss)

**Comment by yasminSalah** [comment]
i got this error (ERROR in src/app/app.module.ts(6,36): error TS2307: Cannot find module '@ngx-share/buttons'.)
while trying to (import { ShareButtonsModule } from '@ngx-share/buttons';)

**Comment by yasminSalah** [comment]
part of my dependenices:
"@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "@fortawesome/angular-fontawesome": "^0.6.1",
    "@fortawesome/fontawesome-svg-core": "^1.2.28",
    "@fortawesome/free-brands-svg-icons": "^5.13.0",
    "@fortawesome/free-solid-svg-icons": "^5.13.0",
    "@ngx-share-pat/button": "0.0.5",
    "@ngx-share/button": "^7.1.4",
    "@ngx-share/core": "^7.1.4",
    "font-awesome": "^4.7.0",
    "ngx-sharebuttons": "^8.0.0-beta.1",
    "rxjs": "~6.4.0",
    "rxjs-compat": "^6.5.5",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"

**Comment by yasminSalah** [comment]
and when try to do like --------- stackblitz example------
i got this errors in command line


ERROR in node_modules/ngx-sharebuttons/buttons/share-buttons.d.ts:20:9 - error TS1086: An accessor cannot be declared in an ambient context.

20     set includedButtons(includedButtons: string[]);
           ~~~~~~~~~~~~~~~
node_modules/ngx-sharebuttons/buttons/share-buttons.d.ts:21:9 - error TS1086: An accessor cannot be declared in an ambient context.

21     set excludedButtons(excludedButtons: string[]);
           ~~~~~~~~~~~~~~~
node_modules/ngx-sharebuttons/buttons/share-buttons.d.ts:22:9 - error TS1086: An accessor cannot be declared in an ambient context.

22     set shownButtons(shownCount: number);
           ~~~~~~~~~~~~
node_modules/ngx-sharebuttons/icons/share-custom-icons.module.d.ts:2:31 - error TS2307: Cannot find module '@fortawesome/angular-fontawesome'.

2 import { FaIconLibrary } from '@fortawesome/angular-fontawesome';
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/ngx-sharebuttons/icons/share-custom-icons.module.d.ts:3:32 - error TS2307: Cannot find module '@fortawesome/fontawesome-svg-core'.

3 import { IconDefinition } from '@fortawesome/fontawesome-svg-core';
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/ngx-sharebuttons/icons/share-icons.module.d.ts:2:31 - error TS2307: Cannot find module '@fortawesome/angular-fontawesome'.

2 import { FaIconLibrary } from '@fortawesome/angular-fontawesome';
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/ngx-sharebuttons/lib/buttons/base.d.ts:15:9 - 39mmerror TS1086: An accessor cannot be declared in an ambient context.

15     get text(): string;
           ~~~~
node_modules/ngx-sharebuttons/lib/buttons/base.d.ts:17:9 - error TS1086: An accessor cannot be declared in an ambient context.

17     get ariaLabel(): string;
           ~~~~~~~~~
node_modules/ngx-sharebuttons/lib/buttons/base.d.ts:19:9 - error TS1086: An accessor cannot be declared in an ambient context.

19     get color(): string;
           ~~~~~
node_modules/ngx-sharebuttons/lib/buttons/base.d.ts:21:9 - error TS1086: An accessor cannot be declared in an ambient context.

21     get icon(): string | string[];
           ~~~~
node_modules/ngx-sharebuttons/lib/buttons/base.d.ts:22:9 - error TS1086: An accessor cannot be declared in an ambient context.

22     get desktop(): string | undefined;
           ~~~~~~~
node_modules/ngx-sharebuttons/lib/buttons/base.d.ts:23:9 - error TS1086: An accessor cannot be declared in an ambient context.

23     get android(): string | undefined;
           ~~~~~~~
node_modules/ngx-sharebuttons/lib/buttons/base.d.ts:24:9 - error TS1086: An accessor cannot be declared in an ambient context.

24     get ios(): string | undefined;
           ~~~
node_modules/ngx-sharebuttons/lib/buttons/base.d.ts:25:9 - error TS1086: An accessor cannot be declared in an ambient context.

25     get sharerUrl(): string;
           ~~~~~~~~~
node_modules/ngx-sharebuttons/lib/buttons/copy.d.ts:13:9 - error TS1086: An accessor cannot be declared in an ambient context.

13     get text(): any;
           ~~~~
node_modules/ngx-sharebuttons/lib/buttons/copy.d.ts:14:9 - error TS1086: An accessor cannot be declared in an ambient context.

14     get icon(): any;
           ~~~~
node_modules/ngx-sharebuttons/lib/buttons/email.d.ts:13:9 - error TS1086: An accessor cannot be declared in an ambient context.

13     get desktop(): string;
           ~~~~~~~
node_modules/ngx-sharebuttons/lib/buttons/facebook.d.ts:13:9 - error TS1086: An accessor cannot be declared in an ambient context.

13     get desktop(): string;
           ~~~~~~~
node_modules/ngx-sharebuttons/lib/buttons/line.d.ts:13:9 - error TS1086: An accessor cannot be declared in an ambient context.

13     get desktop(): string;
           ~~~~~~~
node_modules/ngx-sharebuttons/lib/buttons/linkedin.d.ts:13:9 - error TS1086: An accessor cannot be declared in an ambient context.

13     get desktop(): string;
           ~~~~~~~
node_modules/ngx-sharebuttons/lib/buttons/messenger.d.ts:13:9 - error TS1086: An accessor cannot be declared in an ambient context.

13     get android(): string;
           ~~~~~~~
node_modules/ngx-sharebuttons/lib/buttons/messenger.d.ts:14:9 - error TS1086: An accessor cannot be declared in an ambient context.

14     get ios(): string;
           ~~~
node_modules/ngx-sharebuttons/lib/buttons/mix.d.ts:13:9 - error TS1086: [0mAn accessor cannot be declared in an ambient context.

13     get desktop(): string;
           ~~~~~~~
node_modules/ngx-sharebuttons/lib/buttons/pinterest.d.ts:13:9 - error TS1086: An accessor cannot be declared in an ambient context.

13     get desktop(): string;
           ~~~~~~~
node_modules/ngx-sharebuttons/lib/buttons/reddit.d.ts:13:9 - error TS1086: An accessor cannot be declared in an ambient context.

13     get desktop(): string;
           ~~~~~~~
node_modules/ngx-sharebuttons/lib/buttons/sms.d.ts:13:9 - error TS1086: An accessor cannot be declared
in an ambient context.

13     get desktop(): string;
           ~~~~~~~
node_modules/ngx-sharebuttons/lib/buttons/sms.d.ts:14:9 - error TS1086: An accessor cannot be declared
in an ambient context.

14     get android(): string;
           ~~~~~~~
node_modules/ngx-sharebuttons/lib/buttons/sms.d.ts:15:9 - error TS1086: An accessor cannot be declared
in an ambient context.

15     get ios(): string;
           ~~~
node_modules/ngx-sharebuttons/lib/buttons/telegram.d.ts:13:9 - error TS1086: An accessor cannot be declared in an ambient context.

13     get desktop(): string;
           ~~~~~~~
node_modules/ngx-sharebuttons/lib/buttons/tumblr.d.ts:13:9 - error TS1086: An accessor cannot be declared in an ambient context.

13     get desktop(): string;
           ~~~~~~~
node_modules/ngx-sharebuttons/lib/buttons/twitter.d.ts:13:9 - error TS1086: An accessor cannot be declared in an ambient context.

13     get desktop(): string;
           ~~~~~~~
node_modules/ngx-sharebuttons/lib/buttons/vk.d.ts:13:9 - error TS1086: An accessor cannot be declared in an ambient context.

13     get desktop(): string;
           ~~~~~~~
node_modules/ngx-sharebuttons/lib/buttons/whatsapp.d.ts:13:9 - error TS1086: An accessor cannot be declared in an ambient context.

13     get desktop(): string;
           ~~~~~~~
node_modules/ngx-sharebuttons/lib/buttons/whatsapp.d.ts:14:9 - error TS1086: An accessor cannot be declared in an ambient context.

14     get android(): string;
           ~~~~~~~
node_modules/ngx-sharebuttons/lib/buttons/whatsapp.d.ts:15:9 - error TS1086: An accessor cannot be declared in an ambient context.

15     get ios(): string;
           ~~~
node_modules/ngx-sharebuttons/lib/buttons/xing.d.ts:13:9 - error TS1086: An accessor cannot be declared in an ambient context.

13     get desktop(): string;
           ~~~~~~~
node_modules/ngx-sharebuttons/lib/share.service.d.ts:12:9 - error TS1086: An accessor cannot be declared in an ambient context.

12     get prop(): import("./share.models").IShareButtons;
           ~~~~
node_modules/ngx-sharebuttons/lib/share.service.d.ts:13:9 - error TS1086: An accessor cannot be declared in an ambient context.

13     get windowSize(): string;
           ~~~~~~~~~~

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
i ｢wdm｣: Failed to compile.


my dependenices :

"@angular/animations": "^8.2.14",
    "@angular/cdk": "^9.2.1",
    "@angular/common": "~8.2.14",
    "@angular/compiler": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/material": "^9.2.1",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "@ngx-share-pat/button": "0.0.5",
    "@ngx-share/button": "^7.1.4",
    "@ngx-share/core": "^7.1.4",
    "ngx-sharebuttons": "^8.0.0-beta.1",
    "rxjs": "~6.4.0",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
