### ISSUE TITLE
Ability to disable the buttons

### ISSUE THREAD

**Issue by ltoshev** [MurhafSousli/ngx-sharebuttons#433]
#### I am submitting a

- [x] Feature request

#### What is the expected behavior?

<share-buttons (click)="shareClick($event)"

I have a UI where I show a preview for people and the share button are there but I want to prevent people from clicking them, so I hooked the click event and do $event.preventDefault() and return false.

The expected behavior is not to open the window for sharing.

#### What is the current behavior?

But the actions still take place, even if I cancel the event?

#### What is the use-case or motivation for changing an existing behavior?

Use case is if I want to show preview of my UI for my users without them being able to click the share buttons, while in preview mode.

#### Which versions are you using for the following packages?

Angular: 8
Angular CDK: 8
Angular CLI: 8
Angular-fontawesome: latest
Share buttons: latest

**Comment by MurhafSousli** [comment]
This isn't a bug!
