### ISSUE TITLE
url and imgage input doesn't seem to be working

### ISSUE THREAD

**Issue by blasco** [MurhafSousli/ngx-sharebuttons#437]
#### I am submitting a

- [x] Bug Report

#### What is the current behavior?
The share directive only shares the current url and no image

#### What are the steps to reproduce?
```
<button shareButton="facebook"
        [image]="'/assets/img/berlin.jpg'"
        [url]="'www.google.com'"
        >Share Facebook</button>
```

#### Which versions are you using for the following packages?

    "@angular/cdk": "^9.2.0",
    "@ngx-share/core": "^7.1.4",

**Comment by MurhafSousli** [comment]
The image input is meant for pinterest only and the url works fine with fb, please reproduce the issue with here https://stackblitz.com/edit/ngx-sharebuttons-v8

**Comment by blasco** [comment]
Issue solved. The problem was not adding 'https://' in the beginning. I found another issue though, the 'shareButton' directive works fine, but the 'share-button' doesn't. Have a look here:

https://stackblitz.com/edit/ngx-sharebuttons-v8-edwure

**Comment by MurhafSousli** [comment]
Facebook gets the image from the source website, if the website has the og:image meta tag then the image will appear, so this is out of your control.
