### ISSUE TITLE
IOS 13 - Safari - share by Email - "[..] blocked from automatically composing an email."

### ISSUE THREAD

**Issue by Martin-Eckleben** [MurhafSousli/ngx-sharebuttons#438]
#### I am submitting a

- [x] Bug Report

#### What is the expected behavior?

Opening the mail program without security question and returning to the original website afterwards (not "Favourites").

A standard mailto link still works as intended.

#### What is the current behavior?

[recording.zip](https://github.com/MurhafSousli/ngx-sharebuttons/files/4470074/recording.zip)

#### What are the steps to reproduce?

( open in mobile safari - on desktop it works but also opens a new window )

https://angular-6pbu9z.stackblitz.io/

https://stackblitz.com/edit/angular-6pbu9z

#### Which versions are you using for the following packages?

"@angular/animations": "8.2.12",
"@angular/cdk": "8.2.3",
"@angular/common": "8.2.12",
"@angular/compiler": "8.2.12",
"@angular/core": "8.2.12",
"@angular/forms": "8.2.12",
"@angular/platform-browser": "8.2.12",
"@angular/platform-browser-dynamic": "8.2.12",
"@fortawesome/angular-fontawesome": "^0.6.1",
"@fortawesome/fontawesome-svg-core": "^1.2.28",
"@fortawesome/free-brands-svg-icons": "^5.13.0",
"@fortawesome/free-solid-svg-icons": "^5.13.0",
"@ngx-share/button": "7.1.4",
"@ngx-share/buttons": "^7.1.4",
"@ngx-share/core": "7.1.4",
"rxjs": "6.5.3",
"tslib": "1.10.0",
"zone.js": "~0.9.1"

IOS: 13

https://stackoverflow.com/questions/42085551/safari-mailto-this-website-has-been-blocked-from-automatically-composing-an-em
mentions Apple changed something in Safari regarding this.

If I find time I'll look into it.
If I find something I'll post a pull request.

**Comment by Martin-Eckleben** [comment]
When cloning it - running npm i - ng serve - the compiler complains about "@import "~@ngx-share/button/themes/modern/modern-dark-theme" from styles.scss missing
Maybe It should be added to package.json or be removed?

**Comment by Martin-Eckleben** [comment]
This is the core of the "redirection": 
`const popUp = this._document.defaultView.open(
          finalUrl,
          'newwindow',
          this._windowSize
);`

So right now its being done in a very elaborate, not browser intended way I think?

Guess Apple wants a
`<a href="mailto:example@example.org">example</a>`

What do you think?

**Comment by MurhafSousli** [comment]
Yes, you can submit your PR!

**Comment by Martin-Eckleben** [comment]
Proposal in PR #448.

**Comment by MurhafSousli** [comment]
Fixed in v8
