### ISSUE TITLE
Custom non-FA SVG icons

### ISSUE THREAD

**Issue by albiebrown** [MurhafSousli/ngx-sharebuttons#439]
#### I am submitting a

- [x] Feature Request

#### What is the expected behavior?
Ability to set icon to non-@fortawesome local SVG paths.

#### What is the current behavior?
Only allows @fortawesome icons

#### What is the use-case or motivation for changing an existing behavior?
This would allow users to swap out font-awesome icons for any SVG they choose. This would also help people using older versions of the service to use whatever SVGs they want if they are having trouble creating a custom button.

#### Which versions are you using for the following packages?

Angular:
Angular CDK:
Angular CLI:
Angular-fontawesome:
Share buttons:

**Comment by MurhafSousli** [comment]
If you are using the share buttons components then it is true, only FA icons is allowed.
Implementing a feature to be able to use your own custom icon in the `<share-buttons>` could be possible but It would take a considerable amount work + the usage would become ugly.. (adding custom template feature then passing each button icon etc..)

Why not use the share directive to create your own custom share button?

**Comment by albiebrown** [comment]
That makes sense, is there an easy way to append a standalone button (like the custom share button) you mentioned above and have it fall inline with the <share-buttons> components?

**Comment by MurhafSousli** [comment]
This was possible before, but currently each button has its own hardcoded class. I might bring this feature again in a future release

**Comment by MurhafSousli** [comment]
I am closing this, you can either use FontAwesome icons component or use a single share button with custom icon component
