### ISSUE TITLE
Unable to pass both URl and Image with Facebook

### ISSUE THREAD

**Issue by AmandeepTMSFalcon** [MurhafSousli/ngx-sharebuttons#442]
<button shareButton="facebook" [sbUrl]="UserUrlLink"></button>

When I added [sbImage] then its giving me error. 
I am using "ngx-sharebuttons": "^3.0.0" and either I can send the image or url. But I wanna send boths. Please help me here to sort out this issue.

**Comment by MurhafSousli** [comment]
image is only meant for pinterest https://github.com/MurhafSousli/ngx-sharebuttons/wiki/Share-Button-Directive#available-inputs--outputs

With facebook only the URL input is valid https://github.com/MurhafSousli/ngx-sharebuttons/wiki/Share-Button-Directive#available-inputs--outputs
