### ISSUE TITLE
console errors

### ISSUE THREAD

**Issue by dawa-liverpudlian** [MurhafSousli/ngx-sharebuttons#443]
1 ) FontAwesome: Global icon library is deprecated. Consult https://github.com/FortAwesome/angular-fontawesome/blob/master/UPGRADING.md for the migration instructions.

2) ERROR TypeError: Cannot read property 'create' of undefined
    at ShareDirective._createShareButton (ngx-share-core.js:1658)
Can you please look at this issue.

Although doesn't affect the flow.

**Comment by MurhafSousli** [comment]
Please check for existing issues before opening a new one. this has been solved in v8
#432 , demo: https://stackblitz.com/edit/ngx-sharebuttons-v8

**Comment by dawa-liverpudlian** [comment]
Ahh, sorry forgot to check the closed issue's.
Thank you for the help. No errors now.

Thanks.

**Comment by dawa-liverpudlian** [comment]
> Please check for existing issues before opening a new one. this has been solved in v8
> #432 , demo: https://stackblitz.com/edit/ngx-sharebuttons-v8

Do we need to use angular 9 with the version 8.0.0-beta.1 ? It's working fine locally but when i build i am getting error.

**Comment by MurhafSousli** [comment]
I am not 100% sure! I don't get the chance to build and test with multiple angular versions.. so I rely on users feedback. if you are positive that the build error is caused by the share buttons then it means you need to upgrade to NG9 or stay in the previous version.
