### ISSUE TITLE
Buttons are not being displayed

### ISSUE THREAD

**Issue by jayant-1210** [MurhafSousli/ngx-sharebuttons#444]
#### I am submitting a

- [x] Bug Report

#### What is the current behavior?
I am using the following code but i am unable to see any button in the view
<share-button [theme]="'circles-dark'"
          [button]="'facebook'"
          [size]="4"
          [url]="'https://twitter.com/'">
</share-button>
![image](https://user-images.githubusercontent.com/36629336/80246104-80564380-8689-11ea-80b4-eeec9066c067.png)
![image](https://user-images.githubusercontent.com/36629336/80246356-e4790780-8689-11ea-8a03-89e9412c910b.png)
and same is happening in the directive also
#### Which versions are you using for the following packages?

Angular: ~9.0.2
Angular CDK: ^9.2.1
Angular CLI: ~9.0.3
Angular-fontawesome: ^0.6.1
Share buttons: ^7.1.4

#### Is there anything else we should know?
I want to place fb, twitter and linked in buttons on modal

**Comment by MurhafSousli** [comment]
Please add a reproduction your issue https://stackblitz.com/edit/ngx-sharebuttons-v8

**Comment by jayant-1210** [comment]
I am not using scss in my application. Is there something else i need to change.

**package.json:**
"private": true,
  "dependencies": {
    "@angular/animations": "~8.2.0",
    "@angular/cdk": "^9.2.1",
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/platform-server": "~8.2.0",
    "@angular/pwa": "~0.803.0",
    "@angular/router": "~8.2.0",
    "@angular/service-worker": "~8.2.0",
    "@fortawesome/angular-fontawesome": "^0.6.1",
    "@fortawesome/fontawesome-svg-core": "^1.2.28",
    "@fortawesome/free-brands-svg-icons": "^5.13.0",
    "@fortawesome/free-solid-svg-icons": "^5.13.0",
    "@ngx-share/button": "^7.1.4",
    "@ngx-share/buttons": "^7.1.4",
    "@ngx-share/core": "^7.1.4",
    "bootstrap": "4.1.1",
    "jw-angular-social-buttons": "^1.0.0",
    "lodash": "^4.17.15",
    "ngx-bootstrap": "^5.5.0",
    "ngx-plyr": "^4.0.0",
    "ngx-select-dropdown": "^1.4.0",
    "ngx-toastr": "^12.0.0",
    "plyr": "^3.5.10",
    "rxjs": "~6.4.0",
    "tslib": "~1.10.0",
    "underscore": "^1.10.2",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.803.25",
    "@angular/cli": "~8.3.0",
    "@angular/compiler-cli": "~8.2.0",
    "@angular/language-service": "~8.2.0",
    "@types/jasmine": "~3.4.0",
    "@types/jasminewd2": "~2.0.0",
    "@types/node": "~12.7.0",
    "@types/owlcarousel": "^1.3.4",
    "codelyzer": "~5.1.0",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.0",
    "karma": "~4.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~2.0.0",
    "karma-jasmine-html-reporter": "~1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~8.4.0",
    "tslint": "~5.20.0",
    "typescript": "~3.5.0"
  }

**app.module.ts** 
import { ShareButtonsModule } from '@ngx-share/buttons';
.....
imports: [
    BrowserModule.withServerTransition({ appId: 'serverApp' }),
    BrowserAnimationsModule,
    HttpClientModule,
    FormsModule,
    ShareButtonsModule
  ]

**Component Template:**
<share-buttons theme="default" 
  [url]="'https://google.com/'"
  [include]="['facebook','twitter','linkedin', 'email']"
  [exclude]="['google','pinterest','reddit','tumblr','mix','vk','telegram','messenger','whatsapp','xing','line','sms','print','copy']"
 show="4">
</share-buttons>

**style.css**
@import '~@ngx-share/button/themes/default/default-theme';

**Note: while I inspected elements in the developer tools I found some *ngIf  were not true**
![image](https://user-images.githubusercontent.com/36629336/80320842-7e7db300-8836-11ea-87e7-c204e34cbedb.png)
 
got this error in console
![image](https://user-images.githubusercontent.com/36629336/80320890-c270b800-8836-11ea-9347-4d33d62456dc.png)

Is there something else i need to change. Please help.

**Comment by MurhafSousli** [comment]
You need to import `PlatformModule` in your module or try to use the latest beta version
