### ISSUE TITLE
what's up and e-mail share button doesnot share the [url] or the default url , otherwise the facebook,twitter,linkedIn working fine.

### ISSUE THREAD

**Issue by yasminSalah** [MurhafSousli/ngx-sharebuttons#445]
#### What is the expected behavior?
share url in what'sup and email buttons 

#### What is the current behavior?

what's up and e-mail share button doesnot share the [url] or the default url , otherwise the facebook,twitter,linkedIn working fine.

#### Which versions are you using for the following packages?

"@ngx-share-pat/button": "0.0.5",
    "@ngx-share/button": "^7.1.4",
    "@ngx-share/core": "^7.1.4",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "bootstrap": "^4.4.1",
    "express": "^4.17.1",
    "jquery": "^3.4.1",
    "ngx-swiper-wrapper": "^8.0.2",
    "rxjs": "^6.5.3",
    "rxjs-compat": "^6.5.3",
    "ts-loader": "^6.2.1",
    "tslib": "^1.10.0",
    "webpack-cli": "^3.3.10",
    "zone.js": "~0.9.1"

the html:

                        <share-button  button="whatsapp" text="WhatsApp" [showText]="true"  [description]="'description'" [title]="'title'"  [url]="'http://www.nytimes.com/2015/02/19/arts/international/when-great-minds-dont-think-alike.html '"></share-button>

the app.modules.ts

import { ShareButtonModule } from '@ngx-share-pat/button';

    HttpClientJsonpModule,  // (Optional) Add if you want tumblr share counts
    ShareButtonModule.forRoot()

**Comment by yasminSalah** [comment]
in example:https://murhafsousli.github.io/ngx-sharebuttons/#/share-button-component

when share in what'sup it;s first open :
https://api.whatsapp.com/send?phone=&text=twitter%20description%0d%0ahttp%3a%2f%2fwww.nytimes.com%2f2015%2f02%2f19%2farts%2finternational%2fwhen-great-minds-dont-think-alike.html&source=&data=&app_absent=

then when click send button of what'sup ,it take all info from url metatags+description and share it .

otherwise in developing it in my project : 
when click what'sup button it skipping this (https://api.whatsapp.com/send?)and open (https://web.whatsapp.com/) holding only description without url ...............please need declaration
the same issue in email it share title and description without url

**Comment by MurhafSousli** [comment]
Please use version 8!
