### ISSUE TITLE
Sharing on Cordova doesn't work for SMS, Email, Whatsapp, Telegram and Printing

### ISSUE THREAD

**Issue by yktan8** [MurhafSousli/ngx-sharebuttons#449]
#### I am submitting a
- [x] Bug Report

#### What is the expected behavior?
Should launch system apps to handle sharing via SMS, Email, Whatsapp and Telegram

#### What is the current behavior?
Launches Cordova InAppBrowser for SMS, Email, Whatsapp and Telegram but ends up with error ERR_UNKNOWN_URL_SCHEME

#### What are the steps to reproduce?
Build Angular page with share buttons and wrap with Cordova and test on Android.

#### What is the use-case or motivation for changing an existing behavior?
So that this plugin works for Angular running in Cordova.

#### Which versions are you using for the following packages?
Angular: 9.1.2
Angular CDK: 9.2.1
Angular CLI: 9.1.1
Angular-fontawesome: 0.6.1
Share buttons: 8.0.0-beta.1
Cordova: 9.0.0 (cordova-lib@9.0.1)
Cordova plugins:
cordova-android@8.1.0
cordova-ios@5.1.1
cordova-plugin-inappbrowser@3.2.0

#### Is there anything else we should know?
I tried all sorts of things including meddling with the config.xml for Cordova in whitelisting the intent and navigation with no luck. Example:
`<access origin="*" />
<access origin="mailto:*" launch-external="yes" />
<allow-intent href="mailto:*" launch-external="yes" />
<allow-navigation href="mailto:*" launch-external="yes" />`

I also added some manual buttons to open up the InAppBrowser for mailto: and sms: url scheme and it exhibits the same behaviour. The only way that it worked, is to instruct InAppBrowser to open to a "_system" target, like this:
`cordova.InAppBrowser.open(url,'_system');`

Anyone made ngx-sharebuttons work with cordova for the above url schemes before?

**Comment by MurhafSousli** [comment]
One thing I can think of is to make it possible to override the sharing method, by replacing window 

```ts
ShareButtonsModule.withConfig({
  windowObj: cordova.InAppBrowser
})
```

**Comment by yktan8** [comment]
Hi, thanks very much for looking at this feature request, would the proposed configuration allow me to specify special additional parameters to the InAppBrowser based on sharing type? For non http url scheme (like whatsapp://, tg://, sms://, mailto://), I need to specify the `_system` parameter so that InAppBrowser will allow the system to handle the request:

`cordova.InAppBrowser.open(url,'_system');`

**Comment by MurhafSousli** [comment]
Yes, you will be able to define the url scheme using the config as well!
```ts
ShareButtonsModule.withConfig({
  windowObj: cordova.InAppBrowser,
  sharerTarget: '_system',
  prop: {
     whatsapp: {
         ios: 'whatsapp://'
     }
  }
})
```

**Comment by MurhafSousli** [comment]
I've publish v8.0.0-beta.2, can you check if it works and let me know!

**Comment by yktan8** [comment]
Hi @MurhafSousli what I meant was is it possible to set the sharerTarget based on the button type because it seems that I will need to use "_blank" target for http URL scheme and "_system" for non-http URL schemes? For example:

`ShareButtonsModule.withConfig({
  prop: {
     whatsapp: {         
       windowObj: cordova.InAppBrowser,
       sharerTarget: '_system',
     },
     facebook: {
       windowObj: cordova.InAppBrowser,
       sharerTarget: '_blank',
     },
     linkedin: {
       windowObj: cordova.InAppBrowser,
       sharerTarget: '_self',
     }
  }
})`

In any case, I updated to 8.0.0-beta.2 and noticed the following behaviours:
(1) In version 8.0.0-beta.1 all button types are loaded in InAppBrowser but the InAppBrowser doesn't know how to handle non-http URL schemes. In 8.0.0-beta.2 all button types are loaded in the webview of the cordova app (essentially taking over the app), irregardless of how I configure the ShareButtonsModule. I tried the following two combinations and it behaves the same way:
`ShareButtonsModule.withConfig({
     debug: true
}),`
and
`ShareButtonsModule.withConfig({
  windowObj: cordova.InAppBrowser,
  sharerTarget: '_system'
})`
(2) In 8.0.0-beta.2 I see that the whatsapp, SMS and email buttons are sharing empty content.

**Comment by MurhafSousli** [comment]
No, it is not possible to set the target based on button type in 8 beta2

Why do you need different targets for the different buttons?

 > n version 8.0.0-beta.1 all button types are loaded in InAppBrowser but the InAppBrowser doesn't know how to handle non-http URL schemes

What does that mean? what happens the buttons is clicked?

> In 8.0.0-beta.2 all button types are loaded in the webview of the cordova app (essentially taking over the app), irregardless of how I configure the ShareButtonsModule. I tried the following two combinations and it behaves the same way

It is unclear to me what do you mean by taking over the app? what is the behavior?

**Comment by yktan8** [comment]
> No, it is not possible to set the target based on button type in 8 beta2
> 
> Why do you need different targets for the different buttons?
> 
I have explained this above. For buttons that are having http url schemes (for example the Facebook share button is linking to https://facebook.com/ and Twitter button is linking to https://twitter.com/), my testing indicated I have to use `cordova.InAppBrowser.open(url,'_blank');` for the cordova InAppBrowser to know it has to serve the request by itself as a web page. However, for non-http url scheme (for example, the WhatsApp button is linking to whatsapp://), I need to use `cordova.InAppBrowser.open(url,'_system');` for the InAppBrowser to know that it should not attempt to serve the request and to allow the phone to take over the request.

> What does that mean? what happens the buttons is clicked?
What it means is In version 8.0.0-beta.1 all buttons rendered by ngx-sharebuttons are being "served' by the Cordova InAppBrowser. The Cordova InAppBrowser will be able to correctly render all the http url scheme (like Facebook button that links to https://facebook.com and Twitter button that links to https://twitter.com) because those are linking to a web page that it can retrieve but it will say ERR_UNKNOWN_URL_SCHEME for all non-http url scheme (like Whatsapp button that links to whatsapp://) because those are not web pages that can be retrieved.

> It is unclear to me what do you mean by taking over the app? what is the behavior?
What this means is in version 8.0.0-beta.2 all buttons rendered by ngx-sharebuttons are **not** served by the Cordova InAppBrowser. All the buttons are handled by the phone system. So when someone who is using my Hybrid App clicks on a button that is rendered by ngx-sharebuttons, the phone will attempt to load the page on top of the webview of my app. So it is as if my hybrid app is routed to the external url. The resulting page will be rendered successfully (for example, facebook sharing web page will show up) but there is no way to "return" to my app.
This is different from the case where it is served by Cordova InAppBrowser because the Cordova InAppBrowser opens up a new window that serves the request and there is a "close" button that allows users to return to my Hybrid App.

I hope this paints a better picture of the behaviour.

**Comment by MurhafSousli** [comment]
Ok, we can make target variable for each button but windowObj will be the same for all buttons, correct?

**Comment by MurhafSousli** [comment]
@yktan8 I released a new version beta.4
It is now possible to set the sharer method and sharer target per share button.
For example:

```ts
ShareButtonsModule.withConfig({
  windowObj: cordova.InAppBrowser,
  sharerTarget: '_blank'.   // <= this property would be the default for all buttons
  prop: {
    whatsapp: {
      target: '_system'.       // <= this is meant for whatsapp only
    }
  }
})
```

Can you try and tell what worked for you foreach share button you are using?

**Comment by yktan8** [comment]
> @yktan8 Ok, we can make a target variable for each button but windowObj will be the same for all buttons, correct?

Yes, I think this makes sense.

Thanks for the quick response in rolling out beta.4. I installed it and it is behaving the same as beta.2 that I described above:
>all buttons rendered by ngx-sharebuttons are not served by the Cordova InAppBrowser. All the buttons are handled by the phone system. So when someone who is using my Hybrid App clicks on a button that is rendered by ngx-sharebuttons, the phone will attempt to load the page on top of the webview of my app. So it is as if my hybrid app is routed to the external url. The resulting page will be rendered successfully (for example, facebook sharing web page will show up) but there is no way to "return" to my app.
This is different from the case where it is served by Cordova InAppBrowser because the Cordova InAppBrowser opens up a new window that serves the request and there is a "close" button that allows users to return to my Hybrid App.

I do not know if it is caused by some problems on InAppBrowser or not. I am very curious because InAppBrowser was working when I was using beta.1, it is just that I have no way to set the target from the buttons. Is it possible to revert to the way beta.1 was working with opening links but with just the ability of setting the target?
