### ISSUE TITLE
WhatsApp Desktop not working anymore

### ISSUE THREAD

**Issue by rabdev89** [MurhafSousli/ngx-sharebuttons#451]
I'm using "@ngx-share/button": "^7.1.4".
Yesterday its working on my app.. and so today it suddenly not working anymore. and i test it on your example link.. its not working too.

maybe **https://wa.me/?** is not supporting anymore by whatsApp

![image](https://user-images.githubusercontent.com/30820497/81903672-a883f300-95f4-11ea-8c39-d241d4de0312.png)

**Comment by ruandeveloper** [comment]
Duplicate of #441

**Comment by rabdev89** [comment]
when can we see the version that whatsApp sharing is fixed?

**Comment by MurhafSousli** [comment]
Closing as duplicted
