### ISSUE TITLE
get prop(): import("./share.models").IShareButtons;

### ISSUE THREAD

**Issue by NJONE** [MurhafSousli/ngx-sharebuttons#455]
#### I am submitting a

- [x] Bug Report

#### What is the expected behavior?
shareButtons should work

#### What is the current behavior?
ERROR in ../node_modules/ngx-sharebuttons/lib/share.service.d.ts:13:9 - error TS1086: An accessor cannot be declared in an ambient context.

13     get prop(): import("./share.models").IShareButtons;
           ~~~~
../node_modules/ngx-sharebuttons/lib/share.service.d.ts:14:9 - error TS1086: An accessor cannot be declared in an ambient context.

14     get windowSize(): string;

#### What are the steps to reproduce?
i followed all steps , demo from 
<!-- 
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://stackblitz.com/edit/ngx-sharebuttons<br/>
-->


#### What is the use-case or motivation for changing an existing behavior?



#### Which versions are you using for the following packages?

Angular: 8.2.4
Angular CDK: 8.0.0 ( tried with 9+)
Angular CLI: 8.3.4
Angular-fontawesome: 4.7.0
Share buttons: 8.0.0


#### Is there anything else we should know?

**Comment by MurhafSousli** [comment]
Please add reproduction to your issue so I can see the usage code

**Comment by NJONE** [comment]
I have followed the steps from here https://stackblitz.com/edit/ngx-sharebuttons
here is my ng installed on machine 
Angular CLI: 8.3.14
Node: 10.15.3
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, core, forms, platform-browser
... platform-browser-dynamic, platform-server, router

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.803.26
@angular-devkit/build-angular              0.803.26
@angular-devkit/build-ng-packagr           0.803.26
@angular-devkit/build-optimizer            0.803.26
@angular-devkit/build-webpack              0.803.26
@angular-devkit/core                       8.3.26
@angular-devkit/schematics                 8.3.14
@angular/cli                               8.3.14
@angular/compiler-cli                      8.2.12
@angular/language-service                  8.2.12
@ngtools/webpack                           8.3.26
@nguniversal/module-map-ngfactory-loader   8.2.6
@schematics/angular                        8.3.14
@schematics/update                         0.803.14
ng-packagr                                 5.7.1
rxjs                                       6.5.5
typescript                                 3.5.3
webpack                                    4.39.2

**Comment by MurhafSousli** [comment]
You need to upgrade to Angular v9

**Comment by Nurgunkalol** [comment]
Have the same error, maybe this is because of typescript 4.5.3
I manually tried to change in node_modules for verification and it worked
```
prop: import("./share.models").IShareButtons;
windowSize: string;
```

**Comment by NJONE** [comment]
> Have the same error, maybe this is because of typescript 3.5.3
> I manually tried to change in node_modules for verification and all worked fine
> 
> ```
> prop: import("./share.models").IShareButtons;
> windowSize: string;
> ```

Please share more detail about your work around-- 
i tried upgrade/degrade  typescript version but dint worked for me ...

**Comment by kimnguyen0220** [comment]
in tsconfig add

**Comment by MurhafSousli** [comment]
As @Nurgunkalol mentioned, upgrade your typescript with the one that comes with the Angular update.

**Comment by DhaaraniCIT** [comment]
which typescript version we have to use this

**Comment by paddotk** [comment]
I have the right TS version for my Angular version, and still get this error. When I add the skipLibCheck option, the app doesn't load and I just see a white page without any errors.
