### ISSUE TITLE
The icons are not visible

### ISSUE THREAD

**Issue by kartikchandra14** [MurhafSousli/ngx-sharebuttons#456]
================= Current Beahavior ================
1>>As i am working with library around more than 6 months . But from last one month the icons of social media platforms are not visible on buttons.

================= Expected Beahavior ================
2>>The icons in buttons should be visible

================ reproduction of bug =================
3>>visit a website scholarsbook.com & sign up there At home page you will find the issue on sharing a post

================ Versions of packages ====================
4>> Angular = "~9.0.2"
     "@angular/cdk": "~8.2.2"

    "@angular/cli": "~9.0.3"

    "@ctrl/ngx-emoji-mart": "^1.0.1",
    "@fortawesome/angular-fontawesome": "^0.5.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.28",
    "@fortawesome/free-brands-svg-icons": "^5.13.0",
    "@fortawesome/free-solid-svg-icons": "^5.13.0",

    "@ngx-share/button": "^7.1.4",
    "@ngx-share/buttons": "^7.1.4"

![bug share-buttons](https://user-images.githubusercontent.com/29736729/83703188-67e42c00-a62c-11ea-97ad-34ba43acdc74.png)

========================= WHAT I FOUND ISSUE ============= 
THERE IS A DIV on which a class is active ie
sb-content class
INSIDE which there is no content But when we click on button the icon is visble for that button

& i dont wrote any code to display icon on click of button 
So hoping it is library issue & fix will be done soon.

**Comment by MurhafSousli** [comment]
Upgrade to the latest version 8 (package name has changed) and see the docs and breaking changes https://github.com/MurhafSousli/ngx-sharebuttons/blob/master/CHANGELOG.MD#breaking-changes
