### ISSUE TITLE
Telegram share not working

### ISSUE THREAD

**Issue by Maniraj-Murugan** [MurhafSousli/ngx-sharebuttons#457]
I am using the library into the angular application and I have got the stackblitz,

https://stackblitz.com/edit/ngx-sharebuttons-rmsjzc

Here if we click on the telegram icon then it doesn't redirect to telegram and it throws the error,

**This site can’t be reached**

Please help me to resolve the issue of telegram redirection.

**Comment by MurhafSousli** [comment]
Please upgrade to latest version ngx-sharebuttons@8.0.0 https://github.com/MurhafSousli/ngx-sharebuttons/blob/master/CHANGELOG.MD#breaking-changes
