### ISSUE TITLE
Theme for stylus stylesheet format not working

### ISSUE THREAD

**Issue by Befkadu1** [MurhafSousli/ngx-sharebuttons#458]
#### I am submitting a

- [x] Feature Request
Importing `@import '~ngx-sharebuttons/themes/default/default-theme';` not working 
for Angular projects with stylus stylesheet

#### What is the current behavior?
Error: failed to locate @import file ~ngx-sharebuttons/themes/default/default-theme.styl

#### What are the steps to reproduce?
Import `@import '~ngx-sharebuttons/themes/default/default-theme';`  in styles.styl (not styles.scss)
<img width="589" alt="Screenshot 2020-06-06 at 02 03 01" src="https://user-images.githubusercontent.com/22968497/83930836-e3172080-a799-11ea-8691-38b085a22066.png">

You will see the above error

#### Which versions are you using for the following packages?

Angular: 9
Angular CDK: 9.2.4
Angular CLI: 9.1.9
Angular-fontawesome: 0.6.1
Share buttons: 8.0.0

**Comment by MurhafSousli** [comment]
The library does not support stylus, the only way is to you can copy the content of the theme from the repo and convert it to your stylus syntax in your project.

**Comment by Befkadu1** [comment]
Thank you very much for your quick response. I solved it using share button directive method https://ngx-sharebuttons.netlify.app/#/share-button-directive
ex.
`
<button mat-icon-button
        shareButton="facebook"
        #fbBtn="shareButton"
        [style.color]="fbBtn?.color">
  <fa-icon [icon]="fbBtn?.icon" size="lg"></fa-icon>
</button>
<button mat-icon-button
        shareButton="twitter"
        #twtBtn="shareButton"
        [style.color]="twtBtn?.color">
  <fa-icon [icon]="twtBtn?.icon" size="lg"></fa-icon>
</button>
`
It works well. Thank you again
