### ISSUE TITLE
Using it

### ISSUE THREAD

**Issue by rnkpareek** [MurhafSousli/ngx-sharebuttons#461]
ERROR in node_modules/ngx-sharebuttons/lib/share.service.d.ts(13,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/ngx-sharebuttons/lib/share.service.d.ts(14,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/ngx-sharebuttons/button/share-button.d.ts(38,9): error TS1086: An accessor cannot be declared in an ambient context.

**Comment by MurhafSousli** [comment]
Closing as does not follow the issue template
