### ISSUE TITLE
Confusing upgrade path to ngx-sharebuttons 8 / Angular 9

### ISSUE THREAD

**Issue by molund** [MurhafSousli/ngx-sharebuttons#463]
I just completed an update to 8.0 because the component wasn't working with Angular 9.  I found the process very confusing.  

Can you please add some notes to the [@ngx-share NPM projects](https://www.npmjs.com/package/@ngx-share/buttons) telling people they need to switch their dependencies to the [ngx-sharebuttons](https://www.npmjs.com/package/ngx-sharebuttons) project?

These were the 3 dependencies I had to remove from package.json
 ```  
    "@ngx-share/button": "^7.1.4",
    "@ngx-share/buttons": "^7.1.4",
    "@ngx-share/core": "^7.1.4",
```

And this was the new one that took their place:
`    "ngx-sharebuttons": "^8.0.0",`

I also had to change this line:
`import { ShareButtonsModule } from '@ngx-share/buttons';`
to
`import { ShareButtonsModule } from 'ngx-sharebuttons/buttons';`

**Comment by MurhafSousli** [comment]
I thought I did, turned out I did for other packages. now I deprecated the old packages and added a message for the change.

Thanks for bringing this up, cheers!
