### ISSUE TITLE
When we compile the code  their is issue in compile of scss 

### ISSUE THREAD

**Issue by kartikchandra14** [MurhafSousli/ngx-sharebuttons#464]
//========= **In Styles.css** ==========================
@import url("../node_modules/ngx-sharebuttons/themes/default/default-theme.scss");

// ========= **1 error when i do some changes** ================
![image](https://user-images.githubusercontent.com/29736729/84769410-6b47c200-aff3-11ea-987d-cd64dc239e84.png)

// ========== **2 error arise if i try to solve the first error** ===============
![image](https://user-images.githubusercontent.com/29736729/84769505-93cfbc00-aff3-11ea-937c-3c6a2ac36069.png)

== =========================================================
**CAN YOU PLEASE SUGGEST WHERE I AM GOING WRONG ??**

**Comment by yktan8** [comment]
Hi, instead of importing in style.css, can you try including the sharebuttons css in angular.json? Something like:

```
"styles": [
              "src/styles.css",
              "src/assets/css/bootstrap.min.css",
              "src/assets/css/font-awesome.min.css",
              "src/assets/css/main.css",
              "./node_modules/font-awesome/css/font-awesome.css",
              "./node_modules/ngx-sharebuttons/themes/material/material-dark-theme.scss",
              "./node_modules/ngx-sharebuttons/themes/modern/modern-light-theme.scss",
              {
                "input": "./node_modules/bootstrap/dist/css/bootstrap.css"
              }

**Comment by kartikchandra14** [comment]
Thanx bro :)
* issue fixed & thanx for help *
MurhafSousli appreciate your work that is shown in library always '-'

**Comment by MurhafSousli** [comment]
Thanks!
