### ISSUE TITLE
Sharing via popup window rather than new browser tab

### ISSUE THREAD

**Issue by yktan8** [MurhafSousli/ngx-sharebuttons#465]
#### I am submitting a

- [x] Question

#### What is the expected behavior?
Sharing via popup window

#### What is the current behavior?
Sharing opens up new browser tab

#### What are the steps to reproduce?
No particular steps, all sharing behave the same way now.

https://stackblitz.com/edit/ngx-sharebuttons

#### What is the use-case or motivation for changing an existing behavior?
Opening new browser tab breaks user screen flow. 

#### Which versions are you using for the following packages?
Angular: 9.1.2
Angular CDK: 9.2.1
Angular CLI: 9.1.1
Angular-fontawesome: 0.6.1
Share buttons: 8.0.0
Cordova: 9.0.0 (cordova-lib@9.0.1)
Cordova plugins:
cordova-android@8.1.0
cordova-ios@5.1.1
cordova-plugin-inappbrowser@3.2.0

#### Is there anything else we should know?
Is there an option that can be set to open popup window instead of new browser tab when sharing occurs?

**Comment by nuno** [comment]
According to the demo https://ngx-sharebuttons.netlify.app/#/popup-buttons the popup is in beta, but or it the example provided is not good or im doing it wrong.

```error
core.js:6228 ERROR Error: Uncaught (in promise): NullInjectorError: R3InjectorError(HomePageModule)[SharePopupService -> Overlay -> Overlay -> Overlay -> Overlay]: 
  NullInjectorError: No provider for Overlay!
NullInjectorError: R3InjectorError(HomePageModule)[SharePopupService -> Overlay -> Overlay -> Overlay -> Overlay]: 
  NullInjectorError: No provider for Overlay!

```

```
    "@angular/cdk": "^9.2.4",
    "@angular/common": "~9.1.6",
    "@angular/core": "~9.1.6"
    "@fortawesome/angular-fontawesome": "^0.7.0",
    "@fortawesome/fontawesome-common-types": "^0.2.29",
    "@fortawesome/fontawesome-svg-core": "^1.2.29",
    "@fortawesome/free-brands-svg-icons": "^5.13.1",
    "@fortawesome/free-solid-svg-icons": "^5.13.1",
    "@ionic/angular": "^5.0.0",
    "ngx-sharebuttons": "^8.0.0",

       ...
     "@types/node": "^12.11.1",
     "typescript": "~3.8.3"
```


If I paste the code from the LAB  ---> https://ngx-sharebuttons.netlify.app/#/popup-buttons

```

<popup-buttons [theme]="'modern-dark'"
 [include]="['facebook','twitter','email']"
 [show]="5"
 [size]="1"
 [url]="'https://twitter.com/'"
 [title]="'Migrant Title'"
 [description]="'Migrant desc'"
 [autoSetMeta]="false"
></popup-buttons>
```

i get popup-buttons is not know element.

Can anyone please give me an explanation how this suppose to work? Im doing it wrong?

Thank you fro you time!

**Comment by MurhafSousli** [comment]
@yktan8 Sorry for late, been busy recently.

Yes, actually that was the default behavior until some buttons like the email button had issue when using `window.open` method on some browser, therefore I added the ability to share using an anchor instead.

To switch to the window method which open in a new tab, use the following:

```ts
ShareButtonsModule.withConfig({
  sharerMethod: SharerMethod.Window
})
```
here is [stackblitz demo](https://stackblitz.com/edit/ngx-sharebuttons-mzxwom?file=src%2Fapp%2Fapp.module.ts)

**Comment by MurhafSousli** [comment]
@nuno your issue is not related to this one, please open a new issue and fill the template properly including the version a stackblitz reproduction

**Comment by JoaoPauloLisboa** [comment]
This config works fine with **ShareButtonsModule**, but using **ShareModule** with directive sharing continues open up a new tab, any solution that can I do?
