### ISSUE TITLE
Twitter title is not displaying

### ISSUE THREAD

**Issue by dineshmaths1** [MurhafSousli/ngx-sharebuttons#466]
i am using angular 9
```
const customConfig: ShareButtonsConfig = {
  autoSetMeta: false,
  theme: 'circles-dark',
  twitterAccount: 'dinesh'
};
```
while post title is not displaying

**Comment by MurhafSousli** [comment]
Please fill the template issue properly, we need to know the version for the record and a stackblitz reproduction to look at the issue
