### ISSUE TITLE
I can't switch the theme of icons

### ISSUE THREAD

**Issue by nyxongod** [MurhafSousli/ngx-sharebuttons#468]
#### I am submitting a

- [x] Bug Report

#### What is the expected behavior?
I should be able to change theme of the buttons

#### What is the current behavior?
nothing changed, theme stays the same probably default without any results

#### What are the steps to reproduce?
I have installed this package according to your instruction

1.
   npm i ngx-sharebuttons @angular/cdk
    npm i @fortawesome/fontawesome-svg-core @fortawesome/angular-fontawesome @fortawesome/free-solid-svg-icons @fortawesome/free-brands-svg-icons

2. import theme styles

    @import '../../../node_modules/ngx-sharebuttons/themes/modern/modern-light-theme';
@import '../../../node_modules/ngx-sharebuttons/themes/default/default-theme';

@import '../../../node_modules/ngx-sharebuttons/themes/outline/outline-theme';
@import '../../../node_modules/ngx-sharebuttons/themes/material/material-light-theme';
@import '../../../node_modules/ngx-sharebuttons/themes/classic/classic-light-theme';
@import '../../../node_modules/ngx-sharebuttons/themes/circles/circles-light-theme';

3.  added modules

    import { ShareModule } from 'ngx-sharebuttons';
    import { ShareButtonsModule } from 'ngx-sharebuttons/buttons';
    import { ShareIconsModule } from 'ngx-sharebuttons/icons';

imports:
   ShareModule,
    ShareButtonsModule,
    ShareIconsModule

4. usage of button --> example

!!!!!!!!!!!!!! here does not work changing themes !!!!!!!!!!!!!!!!!

<share-buttons [theme]="'modern-light'"
 [include]="['facebook','twitter','linkedin','pinterest','reddit','tumblr','mix','vk','telegram','messenger','whatsapp','xing','line','sms','email','print','copy']"
 [exclude]="['tumblr']"
 [show]="17"
 [size]="-4"
 [autoSetMeta]="false"
></share-buttons>

#### What is the use-case or motivation for changing an existing behavior?

I'm sorry but icons with default theme does not look nice ;(

#### Which versions are you using for the following packages?

Angular: 9.1.11
Angular CDK: 9.2.4
Angular CLI: 9.1.10
Angular-fontawesome: @fortawesome/angular-fontawesome@0.7.0
Share buttons: ngx-sharebuttons@8.0.0

#### Is there anything else we should know?

If I am doing something wrong please instruct me and change your instruction here

https://ngx-sharebuttons.netlify.app

**Comment by MurhafSousli** [comment]
You can't import multiple themes at once and switch between them,  they will override each other. 
The plugin is designed to have one theme only.

I did it for the sake of the demo, not as a feature. If you still want to do so like in the demo. check the source file

https://github.com/MurhafSousli/ngx-sharebuttons/blob/master/projects/ngx-sharebuttons-demo/src/app/shared/theme-switcher/theme-switcher.component.ts
