### ISSUE TITLE
Angular 10 upgrade

### ISSUE THREAD

**Issue by ekonovich** [MurhafSousli/ngx-sharebuttons#470]
#### I was upgrade my project 9 to 10 and build; 

- [x] node_modules/@ngx-share/button/lib/share-button.module.d.ts:4:53 - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).

4     static withConfig(config?: ShareButtonsConfig): ModuleWithProviders;

#### Which versions are you using for the following packages?

Angular: 10.0.3
Angular CDK: 9.2.4
Angular CLI:10.0.2
Angular-fontawesome: 0.6.1
Share buttons: 7.1.4

**Comment by MurhafSousli** [comment]
You are using the wrong package, it is now `npm i ngx-sharebuttons`
