### ISSUE TITLE
ShareButtonsModule.withConfig does not work in lazy-loaded modules

### ISSUE THREAD

**Issue by paya-cz** [MurhafSousli/ngx-sharebuttons#473]
#### I am submitting a

- [x] Bug Report

#### What is the expected behavior?

Calling `ShareButtonsModule.withConfig` in a lazy-loaded (feature) module works and settings are overridden.

#### What is the current behavior?

No settings are overridden when `ShareButtonsModule.withConfig` is called from a lazy-loaded feature module. If `withConfig` needs to be called in `AppModule` for technical reasons, perhaps `forRoot` and `forChild` convention should be adapted.

#### What is the use-case or motivation for changing an existing behavior?

I wrapped ShareButtons in a custom single-purpose component/module, which gets imported by lazy-loaded pages. Turns out the customization done by withConfig does not work in that case. The customization needs to be done app-wide in `AppModule` otherwise it doesn't work.

Either `forRoot`/`forChild` convention should be adapted, or `withConfig` should work when used in feature modules.

#### Which versions are you using for the following packages?

Angular: 10.0.4
Angular CDK: 10.0.2
Angular CLI: 10.0.3
Angular-fontawesome: 0.7.0
Share buttons: 8.0.0

#### Workaround

`ShareButtonsModule.withConfig` has to be imported by `AppModule` and lazy-loaded modules need to just import `ShareButtonsModule`.

**Comment by MurhafSousli** [comment]
The config service is a singleton, if the share module was imported as a child module with `.withConfig()` it will override the config, therefore you should use `withConfig()` only once, or remove `withConfig()` and import the share config `InjectionToken` and set it in the root module.

For your request, do you know a way to accomplish your expected behavior

**Comment by paya-cz** [comment]
Thanks for explaining. I was hoping for more encapsulation so that each lazy-loaded module can configure the service individually, and keep the app module unbloated for pages that do not use sharebuttons.

**Comment by MurhafSousli** [comment]
As I told you, you can set the global config in the root module using the injection token without importing the share buttons module, just import it in the module that uses it

**Comment by paya-cz** [comment]
Thanks, actually your last comment made the solution very clear, I was slightly confused by the previous one.

For anyone reading this thread later on, the solution looks like this (the providers section):

```

@NgModule({
    declarations: [
        AppComponent,
    ],
    imports: [
        BrowserModule.withServerTransition({ appId: 'serverApp' }),
        AppRoutingModule,
        BrowserAnimationsModule,
    ],
    providers: [
        {
            provide: SHARE_BUTTONS_CONFIG,
            useValue: <ShareButtonsConfig>{
                prop: {
                    facebook: {
                        // icon: faFacebookF,
                    }
                }
            }
        },
    ],
    bootstrap: [AppComponent]
})
export class AppModule { }
```
