### ISSUE TITLE
ISSUE with IE browser

### ISSUE THREAD

**Issue by rnkpareek** [MurhafSousli/ngx-sharebuttons#484]
ERROR Error: Uncaught (in promise): Error: Loading chunk landing-landing-module-ngfactory failed.
missing: https://localhost:4200/landing-landing-module-ngfactory.js
at Anonymous function (https://localhost:4200/vendor.js:58426:17)
   at CatchSubscriber.prototype.error (https://localhost:4200/vendor.js:106670:17

Its working fine with chrome but have error in IE

**Comment by MurhafSousli** [comment]
Closing as doesn't follow the issue template

**Comment by rnkpareek** [comment]
It's not closed.
Because it's working in IE browser
