### ISSUE TITLE
Error in terminal.

### ISSUE THREAD

**Issue by PrashantRajput159** [MurhafSousli/ngx-sharebuttons#492]
ERROR in node_modules/ngx-sharebuttons/lib/share.service.d.ts(13,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/ngx-sharebuttons/lib/share.service.d.ts(14,9): error TS1086: An accessor cannot be declared in an ambient context.

**Comment by MurhafSousli** [comment]
Update your angular and typescript version
