### ISSUE TITLE
    ERROR in node_modules/ngx-sharebuttons/lib/share.service.d.ts(13,9): error TS1086: An accessor cannot be declared in an ambient context.

### ISSUE THREAD

**Issue by Bhanu1225** [MurhafSousli/ngx-sharebuttons#493]
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { ShareModule } from 'ngx-sharebuttons';
import { ShareButtonsModule } from 'ngx-sharebuttons/buttons';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    ShareModule,
    ShareButtonsModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

// html
<share-buttons [theme]="'circles-dark'" [include]="['facebook','twitter','linkedin','pinterest','reddit','tumblr']"
  [showText]="true" [size]="2" [tags]="'SM ,Link'" [autoSetMeta]="false"></share-buttons>

package.json

  "@fortawesome/angular-fontawesome": "^0.7.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.30",
    "@fortawesome/free-brands-svg-icons": "^5.14.0",
    "@fortawesome/free-solid-svg-icons": "^5.14.0",
    "ngx-sharebuttons": "^8.0.1",

**Comment by SHUBHAMDAVE001** [comment]
getting same error with version 4.1.1

**Comment by MurhafSousli** [comment]
Upgrade angular to latest version

**Comment by SHUBHAMDAVE001** [comment]
@MurhafSousli is this a solution ??

what if I have a bigger project, which is not suitable to upgrade. This is not the way.

**Comment by MurhafSousli** [comment]
Then you will have to fallback to a previous version, take a look at the changelog and try the version that works for you. ofcourse you will miss the new fixes and updates. when a new angular version is released I have to release a new version for it which sometimes is incompatible with the older version .. like in your case due to the typescript version.

**Comment by SHUBHAMDAVE001** [comment]
So, I have to try with every version until I get a solution ??
Is there any other method for the same

**Comment by MurhafSousli** [comment]
@SHUBHAMDAVE001 no, read the [CHANGELOG](https://github.com/MurhafSousli/ngx-sharebuttons/blob/master/CHANGELOG.MD#714) and try version 7.1.4, note that that version uses different package name. See https://stackblitz.com/edit/ngx-sharebuttons-v7

**Comment by SHUBHAMDAVE001** [comment]
Okay @MurhafSousli thank you replying back

**Comment by anusha16-debug** [comment]
I am getting this error after running the project node_modules/ngx-sharebuttons/lib/share.service.d.ts(13,9): error TS1086: An accessor cannot be declared in an ambient context.
please suggest some solution @MurhafSousli

**Comment by vjverma143** [comment]
Getting this error any soution?

Error: node_modules/ngx-sharebuttons/buttons/expand-button.d.ts:12:82 - error TS2344: Type '{ moreIcon: { alias: "moreIcon"; required: false; }; lessIcon: { alias: "lessIcon"; required: false; }; expanded: { alias: "expanded"; required: false; }; moreAriaLabel: { alias: "moreAriaLabel"; required: false; }; lessAriaLabel: { ...; }; }' does not satisfy the constraint '{ [key: string]: string; }'.
  Property '"moreIcon"' is incompatible with index signature.
    Type '{ alias: "moreIcon"; required: false; }' is not assignable to type 'string'.

12     static ɵcmp: i0.ɵɵComponentDeclaration<ExpandButton, "expand-button", never, { "moreIcon": { "alias": "moreIcon"; "required": false; }; "lessIcon": { "alias": "lessIcon"; "required": false; }; "expanded": { "alias": "expanded"; "required": false; }; "moreAriaLabel": { "alias": "moreAriaLabel"; "required": false; }; "lessAriaLabel": { "alias": "lessAriaLabel"; "required": false; }; }, { "toggle": "toggle"; }, never, never, false, never>;
