### ISSUE TITLE
Video/Image sharing

### ISSUE THREAD

**Issue by CanopusTest3** [MurhafSousli/ngx-sharebuttons#497]
I am using angular 8 versions but after sharing of video URL on FB it's showing only a link to that video and when I share an image it shows the image with my server port number.

**Comment by MurhafSousli** [comment]
Anything related with how it is been shown on FB, is not part of this plugin.. this means that you should make your app SEO friendly, you can google it to get started

**Comment by CanopusTest3** [comment]
Thanks... Will you please share example for seo

**Comment by MurhafSousli** [comment]
It is mentioned here https://ngx-sharebuttons.netlify.app/#/faq, you can google how to set up Angular Universal
