### ISSUE TITLE
Xing is not working anymore

### ISSUE THREAD

**Issue by JustDoItSascha** [MurhafSousli/ngx-sharebuttons#498]
The Xing sharing url is not working anymore. I think the new url is: https://www.xing.com/spi/shares/new?url=

**Comment by MurhafSousli** [comment]
Thanks for the opening this up with the PR! I will review today and release a new version

**Comment by JustDoItSascha** [comment]
Thank you very much :)

Am Do., 29. Okt. 2020 um 13:58 Uhr schrieb Murhaf Sousli <
notifications@github.com>:

**Comment by MurhafSousli** [comment]
Merged in v8.0.2
