### ISSUE TITLE
Compilation error in Angular 9

### ISSUE THREAD

**Issue by nagthgr8** [MurhafSousli/ngx-sharebuttons#509]
While compiling the code after installing this package in Angular 9, it keeps prompting about missing dependencies, I think the npm package installation should take care of dependency installation as well
#### I am submitting a

-  Bug Report

#### What is the expected behavior?
No compilation issues

#### What is the current behavior?
Getting compilation errors

#### What are the steps to reproduce?
1. open command prompt
2. navigate to project root folder
3, type the command ng build
C:\Users\NagaRam\source\repos\MyyPub.Web\ClientApp>ng build

ERROR in The target entry-point "ngx-sharebuttons/buttons" has missing dependencies:
 - @fortawesome/fontawesome-svg-core
 - @fortawesome/fontawesome-common-types

#### Which versions are you using for the following packages?

Angular CLI: 9.1.12
Node: 12.16.3
OS: win32 x64

Angular: 9.1.12
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
Ivy Workspace: Yes

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.901.12
@angular-devkit/build-angular              0.901.12
@angular-devkit/build-optimizer            0.901.12
@angular-devkit/build-webpack              0.901.12
@angular-devkit/core                       9.1.12
@angular-devkit/schematics                 9.1.12
@angular/cdk                               10.2.7
@ngtools/webpack                           9.1.12
@nguniversal/module-map-ngfactory-loader   8.0.0-rc.1
@schematics/angular                        9.1.12
@schematics/update                         0.901.12
rxjs                                       6.6.3
typescript                                 3.7.5
webpack                                    4.42.0
@fortawesome/angular-fontawesome: 0.7.0

**Comment by MurhafSousli** [comment]
That's expected, the module you are depends on those packages to display the icons, if you must have them installed if you are using `ShareButtonModule` or `ShareButtonsModule`.

See where it is being used

https://github.com/MurhafSousli/ngx-sharebuttons/blob/ef11f81200dab10fdf10f664303f99a2617f4bf5/projects/ngx-sharebuttons/button/src/share-button.module.ts#L3

If you don't wish to use FontAwesome icons then use the `ShareModule` instead.

**Comment by nagthgr8** [comment]
[this post](http://angular-awesome-components.com/2019/05/20/angular-share-buttons/) was helpful
