### ISSUE TITLE
icons does not appear in Angular 9

### ISSUE THREAD

**Issue by nagthgr8** [MurhafSousli/ngx-sharebuttons#511]
I have installed ngx-sharebuttons & added the code as explained in the documentation. Everything works fine but the icons are not displaying even after having the below import statement in the respective scss of the page where the buttons are displayed 
@import '~ngx-sharebuttons/themes/default/default-theme';

[here is the link](https://pasteboard.co/JyX1bH1.jpg)
#### I am submitting a

- [x] Bug Report

#### What is the expected behavior?

default icons should be displayed

#### What is the current behavior?

default share icons not displayed

#### What are the steps to reproduce?

1. install ngx-sharebuttons & all its dependencies to the project
2. add the providers in app-module, the share tag in the script file & import default.scss in the respective page .scss file where the share icons are to be shown
3. build the project & run it

#### What is the use-case or motivation for changing an existing behavior?

this is a bug or an inconsistent behavior observed

#### Which versions are you using for the following packages?

Angular:9.1.2
Angular CDK:^10.2.7
Angular CLI:9.1.2
Angular-fontawesome:^0.7.0
ngx-sharebuttons: ^8.0.2

#### Is there anything else we should know?
You guys have done a great job! keeping issues low

**Comment by MurhafSousli** [comment]
Please add a [reproduction stackblitz ](https://stackblitz.com/edit/ngx-sharebuttons)

Btw, the image link you added shows the icons!
