### ISSUE TITLE
ngx-sharebuttons/popup need usage guide

### ISSUE THREAD

**Issue by thehiddennepali** [MurhafSousli/ngx-sharebuttons#512]
#### I am submitting a

- [x] I am using it angular 11 and want to use popup button, i followed the document of popup no success

#### I got follow error
`Error: 'share-popup-button' is not a known element:
1. If 'share-popup-button' is an Angular component, then verify that it is part of this module.
2. If 'share-popup-button' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("                            <li>

                                                                [ERROR ->]<share-popup-button>Share</share-popup-button>
                                                     ")
`

so not sure what things to import on the module and what other configuration is needed to make work.

Thank you.

Angular:
ngx-sharebuttons:

**Comment by Alsmith141510** [comment]
import { ShareButtonsPopupModule} from 'ngx-sharebuttons/popup'; 

in your module and  then use it in the html <share-popup-button>share</share-popup-button>
