### ISSUE TITLE
Error during template compile of 'ShareModule'

### ISSUE THREAD

**Issue by marlberm2014** [MurhafSousli/ngx-sharebuttons#513]
#### I am submitting a

- [x] Bug Report

#### What is the expected behavior?
Upgrading from 8.0.2 to 8.0.3, then building project causes:
ERROR in ngx-sharebuttons/ngx-sharebuttons.ts(11,5): Error during template compile of 'ShareModule'
  Could not resolve @angular/cdk/clipboard relative to [object Object]..
Can't resolve all parameters for ShareDirective in C:/Work/Weava/Repo/gistnote-aws/node_modules/ngx-sharebuttons/ngx-sharebuttons.d.ts: ([object Object], [object Object], [object Object], ?, [object Object], [object Object], [object Object]).

#### What is the current behavior?
Should build the Angular project without errors (using 8.0.2 it is fine, just updating to 8.0.3 causes the error)

#### What are the steps to reproduce?
1. Use 8.0.2
2. Do the get started steps for Share-Button-Directive
3. Upgrade to 8.0.3
4. Build project

#### What is the use-case or motivation for changing an existing behavior?
Just updating ngx-sharebuttons version.

#### Which versions are you using for the following packages?

Angular: 8.2.14
Angular CDK: 8.2.3
Angular CLI: 8.3.29
Angular-fontawesome: none
ngx-sharebuttons: 8.0.3

#### Is there anything else we should know?
![image](https://user-images.githubusercontent.com/28957240/100305893-0b5f3980-2fdd-11eb-9fff-8c33d3d3c8cb.png)

**Comment by MurhafSousli** [comment]
Somehow, your node_modules `@angular/cdk`, you need to reinstall it `npm i @angular/cdk`
