### ISSUE TITLE
ngx-sharebuttons does not support Ivy

### ISSUE THREAD

**Issue by Laurent02** [MurhafSousli/ngx-sharebuttons#523]
#### I am submitting a

- [x] Feature Request

#### Description
When using Ivy, an application no longer compiles well with ngx-sharebuttons. (Error on Stackblitz, on dev machine no warnings whatsoever, but no share buttons either. Took me a while).

#### What is the use-case or motivation for the new feature?
Using Ivy should be the recommended setting for any new Angular application.

#### Which versions are you using for the following packages?

ngx-sharebuttons: 8.0.5

#### Is there anything else we should know?

Check https://stackblitz.com/edit/angular-edbc2e?file=src/app/app.module.ts
I used the same Angular versions as in my project.

**Comment by MurhafSousli** [comment]
can you try with 8.0.4? and tell me if it is the same or not

**Comment by Omar-Salem** [comment]
> can you try with 8.0.4? and tell me if it is working or not

had the same issue, using `8.0.4` fixed it

**Comment by Laurent02** [comment]
> can you try with 8.0.4? and tell me if it is working or not

8.0.4 fixes it indeed. Using this version for now until it's fixed. Thanks for you awesome work on this nice handy package!

**Comment by MurhafSousli** [comment]
@Omar-Salem @Laurent02 I try to build the demo with v8.0.5 and it works fine! what is the ivy error that you got?

**Comment by Omar-Salem** [comment]
@MurhafSousli  No directive found with exportAs 'shareButton'.

**Comment by Laurent02** [comment]
> @Omar-Salem @Laurent02 I tried to build the demo with v8.0.5 and it works fine! what is the ivy error that you got?

In the provided StackBlitz you can see ngcc fails. In my project however I got no errors whatsoever, the share buttons simply did not show up. Changing to 8.0.4 or disabling Ivy rendrer fixed this, so there's definitely an issue with 8.0.5 and Ivy. I haven't really looked into what that may be though.

**Comment by ewwwgiddings** [comment]
@Laurent02 is right. At least with Angular 10.1.1 there is an issue with version 8.0.5 that causes an error when compiling.

I received this error that disappeared when I downgraded to 8.0.4

**Comment by MurhafSousli** [comment]
Can someone also help investigating the issue? I may not have the time to look into it in the near future so it would be really helpful if someone can figure it out, thanks!

**Comment by RaimonxDev** [comment]
I have the same error . I tried to add it in angular.json but it generates the following error.

With version 8.0.4 compile. but i can't add the styles. I have the version of angular 11.1


![image](https://user-images.githubusercontent.com/39868803/109647824-8eda7a80-7b38-11eb-93e1-96a27d4e2b2b.png)

**Comment by ltoshev** [comment]
I am trying to get this going with angular 9 and it does not work.

I get this error:

 Invalid constructor parameter decorator in C:/proj/123imot.bg/client/imotbg/node_modules/ngx-sharebuttons/fesm2015/ngx-sharebuttons-icons.js:
 () => [
    { type: FaIconLibrary }
]
Error: Error on worker #1: Error: getInternalNameOfClass() called on a non-ES5 class: expected ShareIconsModule to have an inner class declaration
    at Esm5ReflectionHost.getInternalNameOfClass (C:\proj\123imot.bg\client\imotbg\node_modules\@angular\compiler-cli\ngcc\src\host\esm5_host.js:88:23)

**Comment by buu700** [comment]
@MurhafSousli Based on @ewwwgiddings's error, could disabling `declarationMap` possibly fix the error? (I'm not sure why it would, but there's very little else in the delta between 8.0.4 and 8.0.5 that looks relevant.)

**Comment by ImCodean** [comment]
Hi, any chance that there's a solution to this? Will this affect production?

**Comment by MurhafSousli** [comment]
I am sorry I forgot about this issue completely! it is now fixed in v8.1.0
