### ISSUE TITLE
Setting title and description attributes doesn't work

### ISSUE THREAD

**Issue by Omar-Salem** [MurhafSousli/ngx-sharebuttons#525]
#### I am submitting a

- [x] Bug Report

#### What is the expected behavior?
When setting title or description attributes, you should see the text in the shared post.

#### What is the current behavior?
neither title or description attributes are honored, setting them has no effect in the published post.

#### Which versions are you using for the following packages?

Angular:
Angular CDK:
Angular CLI:
Angular-fontawesome:
ngx-sharebuttons:

**Comment by MurhafSousli** [comment]
Please search in existing issues before opening a new one!

Each button has different rules, most of them does not allow overriding the attributes, the social network will scrap your page ussing the static meta tags in your HTML head (not dynamically from a JS plugin)

https://github.com/MurhafSousli/ngx-sharebuttons/wiki/Share-Button-Directive#available-inputs--outputs

in short, you need to use Universal to set the SEO meta tags
