### ISSUE TITLE
Has Missing Dependencies

### ISSUE THREAD

**Issue by frantchessico** [MurhafSousli/ngx-sharebuttons#526]
After installing the library, when I try to run my project, I encounter the following errors:

 "ERROR in The target entry-point "ngx-sharebuttons / buttons" has missing dependencies:
 - @ fortawesome / angular-fontawesome 
 -  @fortawesome/fontawesome-svg-core
 - @fortawesome/fontawesome-common-types
  ".

And to solve this problem I had to install the following modules: 
- @ fortawesome / angular-fontawesome
 - @ fortawesome / fontawesome-svg-core
 - @ fortawesome / fontawesome-common-types
 

As follows: `yarn add @fortawesome/angular-fontawesome @fortawesome/fontawesome-svg-core @fortawesome/fontawesome-common-types`

**Comment by MurhafSousli** [comment]
These are mentioned in the docs!
