### ISSUE TITLE
Folder is missing after installation

### ISSUE THREAD

**Issue by csimpi** [MurhafSousli/ngx-sharebuttons#527]
#### I am submitting a

- [x] Bug Report

#### What is the expected behavior?

I've installed the package with 
`npm i ngx-sharebuttons @angular/cdk`
The folder doesn't appear in the node_modules dir.
Thus, `@import '~ngx-sharebuttons/themes/default/default-theme';` throws an error, the file doesn't exist. 

#### What is the current behavior?
I can't use it because files are missing

#### What are the steps to reproduce?

Above

#### Which versions are you using for the following packages?

Angular: 10.2
Angular CDK: 10.2
Angular CLI: 10.2
Angular-fontawesome:  I use native way with CSS import, I don't see in the WIKI if it's necessary. This shouldn't be a required package
ngx-sharebuttons: newest

**Comment by MurhafSousli** [comment]
Hmmm strange! you can use v8.0.4 for the mean time, there is no difference between it and the most recent version

**Comment by Katlego-777** [comment]
i get the same error...is there a solutioin?

I noticed in the ngx-sharebuttons inside the node modules dir that theres both a themes and button directory ..but inside the button directory ,there isn't a file called theme

**Comment by flyfj** [comment]
same issue here, theme files are not found

**Comment by MurhafSousli** [comment]
It is working in the https://stackblitz.com/edit/ngx-sharebuttons?file=src%2Fstyles.scss! if you still have the issue, please re-open the issue and add a reproduction stackblitz!
