### ISSUE TITLE
Share buttons without font awesome module

### ISSUE THREAD

**Issue by Bhuvn1294** [MurhafSousli/ngx-sharebuttons#529]
I don't want to import or install font awesome. So can i use buttons without font awesome. I will give my own images. Purpose is reduce the size of module and loading time of font awesome icons.

**Comment by MurhafSousli** [comment]
You can use it without the font awesome icons, just import the `ShareModule`

https://github.com/MurhafSousli/ngx-sharebuttons/wiki/Share-Button-Directive

**Comment by Bhuvn1294** [comment]
Thanks for response .I will check , will it work without installing font awesome
