### ISSUE TITLE
ERROR TypeError: Cannot read property 'shareButton' of undefined - After updating to Angular 9. But working properly in Angular 8.

### ISSUE THREAD

**Issue by Prasanth-FrontEnd** [MurhafSousli/ngx-sharebuttons#539]
**Angular Version:**

"@angular/animations": "^9.1.13",
    "@angular/cdk": "^9.2.4",
    "@angular/common": "^9.1.13",
    "@angular/compiler": "^9.1.13",
    "@angular/core": "^9.1.13",
    "@angular/forms": "^9.1.13",
    "@angular/material": "^9.2.4",
    "@angular/platform-browser": "^9.1.13",
    "@angular/platform-browser-dynamic": "^9.1.13",
    "@angular/platform-server": "^9.1.13",
    "@angular/router": "^9.1.13"

**Before updating to Angular 9 I have used these packages:**
   "@ngx-share/button": "^7.1.4",
    "@ngx-share/buttons": "^7.1.4",
    "@ngx-share/core": "^7.1.4"

**After updating to Angular 9 I have used these package:**
    "ngx-sharebuttons": "^8.0.5"

Also, I have tried the beta version - **ngx-sharebuttons@8.0.0-beta.1** still its showing same error.

After compiling the application, I'm getting this error like **ERROR TypeError: Cannot read property 'shareButton' of undefined**. It does not allow me to do any actions in the application.

I can't use even sign up and login page it was frustrating for my client. Please help me out in this issue. Thanks in Advance.

**Comment by MurhafSousli** [comment]
It is working properly, here is an [Angular 9 stackblitz](https://stackblitz.com/edit/ngx-sharebuttons-v8-with-angular-9?file=src/app/app.module.ts)
