### ISSUE TITLE
Images not showing on social media 

### ISSUE THREAD

**Issue by vipul306** [MurhafSousli/ngx-sharebuttons#548]
I am implementing ngx-sharebuttons latest version using angular 9.0

I am trying to share link and image on social media ( LinkedIn , Facebook) , link is shared but no images showing on LinkedIn Post

<share-buttons [theme]="'circles-dark'"
    [include]="['facebook','linkedin','twitter','messenger','whatsapp','email','copy']"
    [show]="7"
    [size]="1"
    [showText]="true"
    [url]="'http://www.sample.com/article/'"
    [title]="'Title'"
    [image] ="'/assets/img/mylogo.png'"
    [autoSetMeta]="false"></share-buttons> 

If i am missing anything please let me know. 

I also tried adding meta tag "og" dynamically on page load. 

Thanks .

**Comment by MurhafSousli** [comment]
You need SSR to make the og tag access-able to the social media

**Comment by MurhafSousli** [comment]
https://github.com/MurhafSousli/ngx-sharebuttons/wiki/Meta-tags-inputs-compatibility
