### ISSUE TITLE
Description not coming on facebook, Linkedin etc..

### ISSUE THREAD

**Issue by rahul-maurya1992** [MurhafSousli/ngx-sharebuttons#552]
#### I am submitting a

- [x] Bug Report

#### What is the expected behavior?
Share description should be come over all the social media. it's not coming few of them like facebook, Linkedin.

#### What is the current behavior?
When i'm trying to share my description over facebook, Linkedin etc.. it's not coming over there. Description only come for whatsapp, email.

#### What are the steps to reproduce?
Just try to share description over facebook and linkedin. I'm using the following code
<share-buttons [theme]="'material-dark'" show="5" title="Kutyc referral code" description="{{msgeng}}" url="https://kutyc.com/"></share-buttons>

#### What is the use-case or motivation for changing an existing behavior?
I want to share my referral code to all my friends on facebook, Linkedin, Whatsapp etc...

#### Which versions are you using for the following packages?

Angular: 10
Angular CDK:^11.2.13
Angular CLI:~10.0.7
Angular-fontawesome:0.9.0
ngx-sharebuttons:^8.0.4

#### Is there anything else we should know?
<share-buttons [theme]="'material-dark'" show="5" title="Kutyc referral code" description="{{msgeng}}" url="https://kutyc.com/"></share-buttons>

I'm using the above code to show share buttons. Please let me know if i'm doing anything wrong.

**Comment by MurhafSousli** [comment]
@rahul-maurya1992 Setting those inputs is not enough in general, you need to make your site SEO friendly by setting the OG meta tags in your document head + using Angular Universal.

For the inputs, see the [meta tags inputs compatibility](https://github.com/MurhafSousli/ngx-sharebuttons/wiki/Meta-tags-inputs-compatibility)
