### ISSUE TITLE
rror: 1"export 'ɵɵngDeclareInjector' (imported as 'i0') was not found in @angular/core

### ISSUE THREAD

**Issue by pungiish** [MurhafSousli/ngx-sharebuttons#563]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/ngx-sharebuttons-ykqc3c?devtoolsheight=33&file=package.json

here it just says Cannot read property 'Injectable' of undefined, because of .umd files.
My errors were: rror: 1"export 'ɵɵngDeclareInjector' (imported as 'i0') was not found in @angular/core,
"export 'ɵɵngDeclareNgModule' (imported as 'i0') was not found in '@angular/core',
"export 'ɵɵngDeclareFactory' (imported as 'i0') was not found in '@angular/core',..
in fesm2015 folder.

Steps to reproduce:
1. Use angular 11 with ivy, my project also uses angular universal
2. install ngx-sharebuttons@8.1.0

#### Expected Behavior

What behavior were you expecting to see?
sharebuttons lib to work

#### Actual Behavior

What behavior did you actually see?
Compiling errors related to exported classes in @angular/core

#### Environment
- Angular: 11.2.1
- ngx-sharebuttons: 8.1.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows

**Comment by MurhafSousli** [comment]
That error could be caused by something else, but please verify Angular 11 with ngx-sharebuttons@8.0.4

**Comment by pathik95** [comment]
I am also facing the similar error in my project which is using Angular 11

**Comment by pungiish** [comment]
> I am also facing the similar error in my project which is using Angular 11

I deleted node modules, package-lock, installed ver @8.0.5 or @8.0.4 , can't remember if i needed to change something to make it work, will check, but I don't think so and then implemented my own sharebuttons popup using cdk overlay. Just pop the existing share buttons tag in there and configure the overlay style, if you need this functionality :)

**Comment by Adityamodasa** [comment]
@MurhafSousli I'm using angular version 8. And it was working perfectly before today with ngx-sharebuttons version 8.0.5 and cdk version 11.0.3 but don't know from today it is giving this error.Please help here. 
"ERROR in ./node_modules/ngx-sharebuttons/fesm2015/ngx-sharebuttons.js 382:205-223
"export 'ɵɵFactoryTarget' (imported as 'i0') was not found in '@angular/core'"

**Comment by MurhafSousli** [comment]
Angular 8 is pretty old, the recent versions don't support it, check the changelog for the compatibility

**Comment by martinIvovIv** [comment]
I solved that problem by going to a lower version of the package, I had 9.0.0 and it gave me the same error.
I uninstalled the package:
npm uninstall ngx-sharebuttons
Then I installed the 8.0.5 and set it so it doesn't automatically update:
npm install ngx-sharebuttons@8.0.5 --save --save-exact

Works perfectly.

**Comment by Sagar4412** [comment]
@martinIvovIv Thanks man. It's working
Amazing
