### ISSUE TITLE
Hey im implementing the ngx-sharebutons with Angular 9 and its not working because of much angular/core errors.

### ISSUE THREAD

**Issue by Bounguicha** [MurhafSousli/ngx-sharebuttons#570]
Hey im implementing the ngx-sharebutons with Angular 9 and its not working because of much angular/core.
 this module is not compatible with angular 9

_Originally posted by @Bounguicha in https://github.com/MurhafSousli/ngx-sharebuttons/discussions/569_

**Comment by MurhafSousli** [comment]
Maybe after upgrading the package Angular version to 11 or 12 is not compatible, I cannot guarantee compatibility for every older Angular version, but I think v8.0.5 or v8.0.4 will work for Angular v9

**Comment by Bounguicha** [comment]
It works with v8.0.4 thank you but i cant share on linkedin ( it recdirects me to the linked in page but a <Something went wrong> error apperas
 dont know why, any solution ?

**Comment by MurhafSousli** [comment]
You should provide a valid URL, if you are passing a localhost URL then obviously you will get an error! try a hosted URL like `https://twitter.com`

**Comment by Bounguicha** [comment]
yes it works thank you , you're the best
