### ISSUE TITLE
Request: Ivy library version

### ISSUE THREAD

**Issue by bjornharvold** [MurhafSousli/ngx-sharebuttons#571]
#### Feature Description

ViewEngine is officially deprecated in Angular 13. Would be great if we could get an Ivy-only version of ngx-sharebuttons

Thank your for a great plugin!

**Comment by MurhafSousli** [comment]
The library is already using `"compilationMode": "partial"` https://github.com/MurhafSousli/ngx-sharebuttons/blob/master/projects/ngx-sharebuttons/tsconfig.lib.prod.json

Can you refer to the documentation of the ivy-only version?

**Comment by bjornharvold** [comment]
Hi @MurhafSousli 

I am not sure. I just got a warning when I started up my Angular 13 app saying it was converting ngx-sharebuttons ViewEngine and to notify the author.

Enjoy the weekend!

**Comment by MurhafSousli** [comment]
This should be fixed in v10.0.0, please report again if you encounter the issue
