### ISSUE TITLE
More complete example of how to use the custom button?

### ISSUE THREAD

**Issue by fernandomacoli** [MurhafSousli/ngx-sharebuttons#573]
I am using to test the custom button as per the documentation, but whatsapp is not being called when clicking the custom button

Below is the code that was made for the test.

```
ngOnInit() {
    this.shareButtons.addButton('myWhatsapp', {
      type: 'whatsapp',
      text: 'My Custom Button whatsapp',
      icon: ['fas', 'fas-comments-dollar'],
      params: {
        url: 'http://myUrl',
        description: 'My description',
      },
      func: () => of({}).pipe(tap(() => alert('My function')))
    });
  }

<share-buttons [include]="['myWhatsapp']"></share-buttons>

```
The alert is executed, but the call to whatsapp is not made

What do you need for whatsapp to be called

**Comment by MurhafSousli** [comment]
Hi @fernandomacoli, I have added a new page to the wiki to demonstrate custom button example

https://github.com/MurhafSousli/ngx-sharebuttons/wiki/Add-custom-buttons

If you have a further questions, use this custom button stackblitz to reproduce your issue https://stackblitz.com/edit/ngx-sharebuttons-qija9z?file=src%2Fapp%2Fhome%2Fhome.component.ts
