### ISSUE TITLE
icons dependency must be optional

### ISSUE THREAD

**Issue by RouR** [MurhafSousli/ngx-sharebuttons#574]
The [doc](https://ngx-sharebuttons.netlify.app/#/popup-buttons) say that ShareIconsModule is optional.
It is not true;

#### Reproduction

```
import {ShareButtonsPopupModule} from 'ngx-sharebuttons/popup';

@NgModule({
  imports: [
    ShareButtonsPopupModule.withConfig({})  
]
})
```

#### Expected Behavior

Must compile without icons dependency.

#### Actual Behavior

```
[ng] ./node_modules/ngx-sharebuttons/fesm2015/ngx-sharebuttons-button.js:5:0-55 - Error: Module not found: Error: Can't resolve '@fortawesome/angular-fontawesome' in '...\node_modules\ngx-sharebuttons\fesm2015'
[ng]
[ng] ./node_modules/ngx-sharebuttons/fesm2015/ngx-sharebuttons-buttons.js:11:0-55 - Error: Module not found: Error: Can't resolve '@fortawesome/angular-fontawesome' in '...\node_modules\ngx-sharebuttons\fesm2015'
[ng]
[ng] ./node_modules/ngx-sharebuttons/fesm2015/ngx-sharebuttons-popup.js:10:0-55 - Error: Module not found: Error: Can't resolve '@fortawesome/angular-fontawesome' in '...\node_modules\ngx-sharebuttons\fesm2015'
[ng]
[ng] Error: node_modules/ngx-sharebuttons/button/share-button.module.d.ts:6:21 - error TS2307: Cannot find module '@fortawesome/angular-fontawesome' or its corresponding type declarations.
[ng]
[ng] 6 import * as i3 from "@fortawesome/angular-fontawesome";
[ng]                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng]
[ng]
[ng] Error: node_modules/ngx-sharebuttons/popup/share-buttons-popup.module.d.ts:10:21 - error TS2307: Cannot find module '@fortawesome/angular-fontawesome' or its corresponding type declarations.
[ng]
[ng] 10 import * as i6 from "@fortawesome/angular-fontawesome";
[ng]                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng]
[ng]
[ng]
[ng] × Failed to compile.
```

#### Environment

- Angular: 13
- ngx-sharebuttons: 9.0.0
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows

**Comment by michalusio** [comment]
This issue makes the package unusable for small applications that are not using FontAwesome. We are not going to add a font dependency for a few buttons, unfortunately.

**Comment by MurhafSousli** [comment]
I will look into it

**Comment by RouR** [comment]
Sorry, but this issue should be reopened.

`share-buttons-popup.module` depends on `share-buttons.module.ts`, wich depens on `share-button.module.ts`, wich depend on `'@fortawesome/angular-fontawesome'`

```
Error: node_modules/ngx-sharebuttons/button/share-button.module.d.ts:6:21 - error TS2307: Cannot find module '@fortawesome/angular-fontawesome' or its corresponding type declarations.

6 import * as i3 from "@fortawesome/angular-fontawesome";
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by MurhafSousli** [comment]
No, you misunderstood the documentation!

The default icons are optional that is true, but that doesn't mean FontAwesome is optional! for example, in FA there is multiple icons for Facebook, twitter ...etc

The `ShareIconModule` is just a module that imports the default set of icons, but user can skip importing it and import his own choice of icons. **but FontAwesome is required any way**

 > The only module that does NOT depends on FontAwesome is the `ShareModule` which contains the share directive.

Now I notice I should revert that fix!

**Comment by RouR** [comment]
Thanks for the clarification.
My goal is to get rid of fontawessome in package.json
