### ISSUE TITLE
trying to integrate ngx-sharebuttons error  css

### ISSUE THREAD

**Issue by nesanmano** [MurhafSousli/ngx-sharebuttons#582]
I have configure my module and component as below:

Module:

import { NgModule } from '@angular/core';
import { CommonModule} from '@angular/common';
import { RouterModule } from '@angular/router';
import { SocialMediaBarComponent } from "./social-media-bar.component";
import { ShareButtonsConfig } from 'ngx-sharebuttons';
import { ShareButtonsModule } from 'ngx-sharebuttons/buttons';
import { ShareIconsModule } from "ngx-sharebuttons/icons";

const customConfig: ShareButtonsConfig = {
  include: ['facebook', 'twitter', 'pinterest','whatsapp'],
  exclude: ['tumblr', 'stumble', 'vk'],
  theme: 'modern-dark',
  gaTracking: true,
  twitterAccount: 'twitterUsername'
}

const shareProp = {
  facebook: {
    icon: ['fab', 'facebook-square']
  }
};

@NgModule({
  imports: [
    CommonModule,
    RouterModule,
    ShareButtonsModule.withConfig(customConfig),
    ShareButtonsModule.withConfig({ prop: shareProp }),
    ShareIconsModule
  ],
  declarations: [
    SocialMediaBarComponent
  ],
  exports: [
    SocialMediaBarComponent
  ]
})

component.ts

A part of my component

  template:`<ul class="social">

    <li><a class="link twitter"><share-buttons [theme]="'modern-dark'"
                                                        [include]="['twitter']"
                                                        [show]="1"
                                                        [url]="'https://twitter.com/'"
                                                        [image]="'test ets kugan'"
                                                        [autoSetMeta]="false"
    ></share-buttons></a></li>

I keep getting this:

./src/styles.css - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: Failed to find 'variables'
  in [
    F:\Nomadlogic\Git\JujuWebLive\node_modules\ngx-sharebuttons\themes
  ]
    at F:\Nomadlogic\Git\JujuWebLive\node_modules\postcss-import\lib\resolve-id.js:35:13
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async LazyResult.runAsync (F:\Nomadlogic\Git\JujuWebLive\node_modules\postcss\lib\lazy-result.js:394:11)
    at async Object.loader (F:\Nomadlogic\Git\JujuWebLive\node_modules\postcss-loader\dist\index.js:97:14)
    at processResult (F:\Nomadlogic\Git\JujuWebLive\node_modules\webpack\lib\NormalModule.js:713:19)
    at F:\Nomadlogic\Git\JujuWebLive\node_modules\webpack\lib\NormalModule.js:819:5
    at F:\Nomadlogic\Git\JujuWebLive\node_modules\loader-runner\lib\LoaderRunner.js:399:11
    at F:\Nomadlogic\Git\JujuWebLive\node_modules\loader-runner\lib\LoaderRunner.js:251:18
    at context.callback (F:\Nomadlogic\Git\JujuWebLive\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at Object.loader (F:\Nomadlogic\Git\JujuWebLive\node_modules\postcss-loader\dist\index.js:142:7)

**Comment by MurhafSousli** [comment]
I don't know which build setup you are using, and it is not shown how you import the themes.

Anyway, go to `angular.json` file and import the themes from there as the following example:

```json
  "projects": {
    "demo": {
      "architect": {
        "build": {
            "styles": [
              "src/styles.scss",
              "node_modules/ngx-sharebuttons/themes/material.scss"
            ],
...
```

I will close this anyway as it does not follow the template issue, if you need further help, please open a new one and fill the issue template properly, and a minimal reproduction using this [stackblitz](https://stackblitz.com/edit/ngx-sharebuttons)
