### ISSUE TITLE
icon name cannot be found in library

### ISSUE THREAD

**Issue by nesanmano** [MurhafSousli/ngx-sharebuttons#583]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/ngx-sharebuttons

I keep getting:

core.js:6479 ERROR Error: Could not find icon with iconName=twitter and prefix=fab in the icon library.

I have followed the tutorial and documentation. The same code works in Stackblitz

https://stackblitz.com/edit/ngx-sharebuttons-byv5ny?file=src%2Fapp%2Fhome%2Fhome.component.html

This is my module class:

@NgModule({
  imports: [
    CommonModule,
    RouterModule,
    ShareIconsModule,
    ShareButtonsModule
  ],
  declarations: [
    SocialMediaBarComponent
  ],
  exports: [
    SocialMediaBarComponent
  ]
})

export class SocialMediaBarModule {

}

**Comment by MurhafSousli** [comment]
Since it works in the stackblitz then the problem is somewhere in your project, not sure how I can help if you cannot reproduce it!
