### ISSUE TITLE
Icons are not showing up. 

### ISSUE THREAD

**Issue by nesanmano** [MurhafSousli/ngx-sharebuttons#585]
Icons are not showing up.

Please take a look at this ticket:

https://stackoverflow.com/questions/71009635/ngx-sharebuttons-icons-not-showing-up

![image](https://user-images.githubusercontent.com/6265481/152695935-ae9acded-0381-4e7c-a8b6-76181ec35cdc.png)

**Comment by MurhafSousli** [comment]
The information you provided is not enough, I've also seen the SO you posted, it is all wrong so I cannot comment on that.

If you want to help with customising the icons, reopen a new issue and fill the template issue properly without using the stackoverflow question, and please add a reproduction [stackblitz](https://stackblitz.com/edit/ngx-sharebuttons).

Closing this one...
