### ISSUE TITLE
Icon not found in fab after manually importing it.

### ISSUE THREAD

**Issue by nesanmano** [MurhafSousli/ngx-sharebuttons#587]
I tried to dig up the issue regarding why the icon would not show up. After spending some time, I came up with the following statement.

The library is not taken into consideration even if I specify the library such as fab.
It is always using the default fas library as shown in the image below.

After looking to your answer, I have applied the fix. The problem is that I still keep getting the error.
This time, it says that icon cannot be found in fab.

![image](https://user-images.githubusercontent.com/6265481/153513427-1e2319aa-6d7d-4736-8f40-8f6823d69c95.png)

fa-facebook-square is found in fab as per awesomium.

Below is my module class

import { NgModule } from '@angular/core';
import { CommonModule} from '@angular/common';
import { RouterModule } from '@angular/router';
import { SocialMediaBarComponent } from "./social-media-bar.component";
import { ShareButtonsConfig,ShareModule } from 'ngx-sharebuttons';
import { ShareButtonsModule } from 'ngx-sharebuttons/buttons';
import { ShareIconsModule } from "ngx-sharebuttons/icons";
import {
  faFacebookSquare,
  faPinterest,
  faPinterestSquare,
  faTwitterSquare,
  faWhatsappSquare
} from '@fortawesome/free-brands-svg-icons';
import { faPinterestP } from '@fortawesome/free-brands-svg-icons/faPinterestP';
import { faWhatsapp } from '@fortawesome/free-brands-svg-icons/faWhatsapp';
import { library } from '@fortawesome/fontawesome-svg-core';
import { fab } from '@fortawesome/free-brands-svg-icons';
import { fas } from '@fortawesome/free-solid-svg-icons'

import {FaIconLibrary} from "@fortawesome/angular-fontawesome";

const icons = [
  faFacebookSquare, faTwitterSquare,faPinterestP, faWhatsapp
];

/*library.add(fab,fas);
library.add(faFacebookSquare);
library.add(faTwitterSquare);
library.add(faPinterestP);
library.add(faWhatsapp);*/

const shareProp = {
  prop: {
    facebook: {
      icon: ['fab', 'fa-facebook-square']
    },
    twitter: {
      icon: ['fab', 'fa-twitter-square']
    },
    pinterest:{
      icon: ['fab', 'fa-pinterest-square']
    },
    whatsapp:{
      icon: ['fab', 'fa-whatsapp-square']
    }
  }
};

@NgModule({
  imports: [
    CommonModule,
    RouterModule,
    ShareIconsModule,
    ShareButtonsModule
  ],
  declarations: [
    SocialMediaBarComponent
  ],
  exports: [
    SocialMediaBarComponent
  ]
})

export class SocialMediaBarModule {
  constructor(library: FaIconLibrary) {
    library.addIcons(faFacebookSquare, faTwitterSquare, faPinterest, faPinterestSquare, faWhatsappSquare);
  }
}

Below is my component class

import {Component, EventEmitter, OnInit, Output} from "@angular/core";
import {findIconDefinition, library} from "@fortawesome/fontawesome-svg-core";
import {IconDefinition} from "@fortawesome/fontawesome-common-types";
import {fab, faFacebookSquare, faTwitterSquare} from "@fortawesome/free-brands-svg-icons";
import {fas} from "@fortawesome/free-solid-svg-icons";
import {faPinterestP} from "@fortawesome/free-brands-svg-icons/faPinterestP";
import {faWhatsapp} from "@fortawesome/free-brands-svg-icons/faWhatsapp";

@Component({

  selector:'social-media-bar',
  template:`

    <ul class="social">

    <li><a class="link twitter"><share-button [theme]="'modern-dark'"
                                                        [button]="'twitter'"
                                                        [url]="'https://twitter.com/'"
                                                        [image]="'test ets kugan'">
    </share-button></a></li>
    <li><a class="link facebook" target="_blank"><share-button [theme]="'modern-dark'" [button]="'facebook'" [icon]="['fab', 'fa-facebook-square']">

    </share-button></a></li>
    <li><a class="link pinterest" target="_blank"><share-button [theme]="'modern-dark'"
                                                              [button]="'pinterest'"
                                                               [url]="'https://twitter.com/'"
                                                               [image]="'test ets kugan'"></share-button></a></li>
    <li><a class="link whatsapp" target="_blank"><share-button [theme]="'modern-dark'"
                                                              [button]="'whatsapp'"
                                                               [url]="'https://twitter.com/'">

    </share-button></a></li>
    <li><a class="link linkedin" (click)="sendPhotoByEmail()"><span class="fas fa-envelope" target="_blank"></span></a></li>
  </ul>`,

#### Expected Behavior

What behavior were you expecting to see?

I expected to see an icon to show up.

#### Actual Behavior

What behavior did you actually see?

Icon does not display because it cannot be found

#### Environment

- Angular:
- ngx-sharebuttons:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by MurhafSousli** [comment]
The problem is not with the library, and I didn't only give you an answer, I gave you a working demo, so if it does not work in your app, it is because you missed something.

I am not going to read that code, while I am 100% sure it is something wrong from your side, you need to add a reproduction stackblitz.

I recommend you to use the share directive, and add the icons manually from FontAwesome, this will also help youunderstand how to use the icons, here is the share directive documentation https://github.com/MurhafSousli/ngx-sharebuttons/wiki/Share-Button-Directive
