### ISSUE TITLE
CSS not being applied

### ISSUE THREAD

**Issue by nesanmano** [MurhafSousli/ngx-sharebuttons#590]
#### Reproduction

 I am trying to apply custom font size to the icons using the variable provided. The problem is that regardless of of where I apply the css, the font size is not changed

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/ngx-sharebuttons-byv5ny?file=src%2Fapp%2Fapp.component.css

Steps to reproduce:
1. look at app.component.css
2.

#### Expected Behavior

What behavior were you expecting to see?
Bigger icons

#### Actual Behavior

What behavior did you actually see?
Not effective

#### Environment

- Angular:
- ngx-sharebuttons:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by MurhafSousli** [comment]
@nesanmano You don't pay attention at all!

If you have filled the version in the template issue properly, maybe you could have recognized that you are trying a feature of the latest version in an outdated version.

The plugin in your stackblitz is **v8.0.5** but the latest plugin version is **v10.0.0**

Second, you are setting the styles in **AppComponent** CSS, but the share buttons are used in **HomeComponent**. you really need to invest some time to learn Angular

```scss
// for the share buttons
share-buttons {
  --sb-icon-size: 2em;
}
// for single share button
share-button {
  --sb-icon-size: 2em;
}
```

Here is a working [stackblitz](https://stackblitz.com/edit/ngx-sharebuttons-hprzf6?file=src%2Fapp%2Fhome%2Fhome.component.scss)

Your time is not more important than my time, so next time fill the template issue properly or I will stop looking at your issues.
