### ISSUE TITLE
Adblock prevents entire website content rendering

### ISSUE THREAD

**Issue by michalpidanic** [MurhafSousli/ngx-sharebuttons#596]
Hi,
I'm using your library, but I found one problem/bug - if user has enabled in adblock antisocial filter "Antisocial filter list removes social media buttons", following error is logged to the console and no content besides my navbar is loaded. 

`GET https://my-domain.com/default-node_modules_ngx-sharebuttons_fesm2015_ngx-sharebuttons-buttons_js-node_modules_ngx-s-d95027.js net::ERR_BLOCKED_BY_CLIENT
`
```
core.js:6479 ERROR Error: Uncaught (in promise): ChunkLoadError: Loading chunk default-node_modules_ngx-sharebuttons_fesm2015_ngx-sharebuttons-buttons_js-node_modules_ngx-s-d95027 failed.
(error: https://my-domain.com/default-node_modules_ngx-sharebuttons_fesm2015_ngx-sharebuttons-buttons_js-node_modules_ngx-s-d95027.js)
ChunkLoadError: Loading chunk default-node_modules_ngx-sharebuttons_fesm2015_ngx-sharebuttons-buttons_js-node_modules_ngx-s-d95027 failed.
(error: https://my-domain.com/default-node_modules_ngx-sharebuttons_fesm2015_ngx-sharebuttons-buttons_js-node_modules_ngx-s-d95027.js)
```

It's pretty tricky because I can't tell which of my customers will have adblock turned on or to be precise which will have Antisocial filter allowed. Does anybody have some work around or fix? Any help is appreciated.

Thank you

(found on win10 Firefox 98, reproduced on macOS Chrome)

**Comment by Ricsie** [comment]
I have same problem! How can I add share buttons so it does not remove the whole page?
