### ISSUE TITLE
ERROR in ./node_modules/ngx-sharebuttons/fesm2015/ngx-sharebuttons-buttons.mjs 135:2390-2402 Can't import the named export 'AsyncPipe' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by nesrineabk** [MurhafSousli/ngx-sharebuttons#600]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/ngx-sharebuttons

Steps to reproduce:
1.
2.

#### Expected Behavior

What behavior were you expecting to see?

#### Actual Behavior

What behavior did you actually see?

#### Environment

- Angular: 12.2.5
- ngx-sharebuttons:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by MurhafSousli** [comment]
This is a problem with your project and is unrelated to this package. for future issues, please fill the template issue properly and a reproduction stackblitz
