### ISSUE TITLE
SassError: Can't find stylesheet to import.

### ISSUE THREAD

**Issue by M1Joe** [MurhafSousli/ngx-sharebuttons#602]
#### Reproduction

I've implemented the basic share buttons. Everything is working find except for the styling.

```
SassError: Can't find stylesheet to import.
  ╷
5 │ @import '~ngx-sharebuttons/themes/circles/circles-dark-theme';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src\styles.scss 5:9  root stylesheet

./src/styles.scss - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
3 │ @import '~ngx-sharebuttons/themes/default';
```

#### Expected Behavior

Nicely styled buttons.

#### Actual Behavior

Buttons with no styling applied.

#### Environment

- Angular: 14
- ngx-sharebuttons: 11
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows

**Comment by MurhafSousli** [comment]
The themes work fine in the [stackblitz](https://stackblitz.com/edit/ngx-sharebuttons)! Please add a reproduction

**Comment by juanico18** [comment]
The problem is that in the docs is told that we should import the scss from our styles.scss
https://github.com/MurhafSousli/ngx-sharebuttons/wiki/Share-Buttons-Component

But on your stackBitz, what you are doing is adding the reference in the angular.json

I think that this is the real problem.
To fix it instead import on styles.scss 
On the angular.json we should add
   "styles": [
              "src/styles.scss",
              "node_modules/ngx-sharebuttons/themes/modern.scss",
              "node_modules/ngx-sharebuttons/themes/material.scss"
            ]


Just add the theme required by your project

**Comment by syah284** [comment]
Perfect! thanks @juanico18!

**Comment by fealegre** [comment]
> The problem is that in the docs is told that we should import the scss from our styles.scss https://github.com/MurhafSousli/ngx-sharebuttons/wiki/Share-Buttons-Component
> 
> But on your stackBitz, what you are doing is adding the reference in the angular.json
> 
> I think that this is the real problem. To fix it instead import on styles.scss On the angular.json we should add "styles": [ "src/styles.scss", "node_modules/ngx-sharebuttons/themes/modern.scss", "node_modules/ngx-sharebuttons/themes/material.scss" ]
> 
> Just add the theme required by your project

Just did it..... problem continues :-(

**Comment by FanniTakax** [comment]
> 

It works for me when I remove the `@import '~ngx-sharebuttons/themes/circles/circles-dark-theme';` from `global.scss`, only adding it to angular.json styles

**Comment by MurhafSousli** [comment]
@FanniTakax  In the new version, the themes directory has changed, see [changelog](https://github.com/MurhafSousli/ngx-sharebuttons/blob/master/CHANGELOG.MD#breaking-changes).  it should be just `@import '~ngx-sharebuttons/themes/circles';`

The stackblitz has different environment unlike the one you get with the Angular CLI, in the stackblitz you cannot access `node_modules` directory from the stylesheet, so we fallback to import it in `angular.json`, it's not bad option in the end!
