### ISSUE TITLE
Copy link button not working

### ISSUE THREAD

**Issue by kevinshah22** [MurhafSousli/ngx-sharebuttons#606]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/ngx-sharebuttons

Steps to reproduce:
1. I have configure the ngx-sharebuttons 
2. set all required properties 
3. still copy button does not work.
4. all other option works properly but copy button is not working.

I am using "11.0.0" version.

#### Expected Behavior

What behavior were you expecting to see?
Copy button should work and link should be copy to clipboard.

#### Actual Behavior

What behavior did you actually see?
Copy to clipboard button do nothing. all other button works as expected.

#### Environment

- Angular: 14
- ngx-sharebuttons: v11
- Browser(s): Any
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by MurhafSousli** [comment]
Please add a reproduction, the live stackblitz works properly!

**Comment by duxor** [comment]
For me working as expected, but there is no indication - it will be great from the UX perspective to notify users when action is completed. @MurhafSousli is there any way to enable it?

**Comment by MurhafSousli** [comment]
@duxor  You can subscribe to the `opened` output when a share button is clicked, then display the notification you like!

**Comment by duxor** [comment]
@MurhafSousli great, thanks, I will check it in the next few days :)

**Comment by duxor** [comment]
@MurhafSousli , Unfortunately, the opened emitter doesn't work as expected for copy share type - I tested it using the share directive.

The `copyToClipboard` util function will be called from [[here](https://github.com/MurhafSousli/ngx-sharebuttons/blob/master/projects/ngx-sharebuttons/src/lib/share-button.directive.ts#L108)] and there is no emitter, you can check the config [[here](https://github.com/MurhafSousli/ngx-sharebuttons/blob/master/projects/ngx-sharebuttons/src/lib/share.defaults.ts#L262)] and util function [[here](https://github.com/MurhafSousli/ngx-sharebuttons/blob/master/projects/ngx-sharebuttons/src/lib/utils.ts#L53)].

So, what do you suggest? :)

**Comment by MurhafSousli** [comment]
@duxor I will look into this, but for now, you can use the following:

```html
<button shareButton="copy" #copy="shareButton" url="http://abc.com">
  {{ copy.text }}
</button>
```

`copy.text` will change when the copy button is clicked

You can also access the icon `copy.icon`

If you need an event, use the click event of the button

```html
<button shareButton="copy" #copy="shareButton" url="http://abc.com" (click)="onCopyClick()">
  {{ copy.text }}
</button>
```

Here is a [working stackblitz](https://stackblitz.com/edit/ngx-sharebuttons-grhm8e?file=src%2Fapp%2Fhome%2Fhome.component.html,src%2Fapp%2Fhome%2Fhome.component.ts,src%2Fapp%2Fapp.component.html)

Here are the default properties of the copy button:

https://github.com/MurhafSousli/ngx-sharebuttons/blob/ac059e97774feeef3bec5d2facb73e2fc1f23192/projects/ngx-sharebuttons/src/lib/share.defaults.ts#L249-L262

**Comment by Mersal-Mohamed2** [comment]
@MurhafSousli  
thanks for your reply but i use the same code as you copy text changes and working good but i don't get any value it still empty value nothing copied to clipboard

this is my code

<ng-template #shareButtons>
  <share-buttons [theme]="'circles-dark'" [include]="include" [title]="title" [description]="title"
    [image]="image" [tags]="tags" [url]="url">
  </share-buttons>

  <button shareButton="copy" #copy="shareButton" [url]="url">
    {{ copy.text }}
  </button>
</ng-template>
