### ISSUE TITLE
bug(messenger): impossible to share in Facebook Messenger on desktop

### ISSUE THREAD

**Issue by pYassine** [MurhafSousli/ngx-sharebuttons#607]
#### Reproduction

While testing the project, I realized that sharing via Facebook Messenger does not work on desktop.
Bug tested on Google 104, and Firefox 103.

I did not make a reproduction because on the documentation you can see the bug live
https://ngx-sharebuttons.netlify.app/#/share-buttons-component

#### Expected Behavior

Share link on facebook Messenger

#### Actual Behavior

When you click, nothing happen

#### Environment

- Angular: 14
- ngx-sharebuttons: 11
- Browser(s): Chrome & Firefox 
- Operating System (e.g. Windows, macOS, Ubuntu): MacOS

**Comment by MurhafSousli** [comment]
This isn't a bug because it was mentioned that **Messenger** button only works on mobile but in v13.0.0 we added support for **Messenger** on desktop

**Comment by MurhafSousli** [comment]
Here is how to get it to work on desktop https://github.com/MurhafSousli/ngx-sharebuttons/wiki/Using-Messenger-on-Desktop
