### ISSUE TITLE
perf: ⚡ Load only the icons you need from FontAwesome within IconsModule

### ISSUE THREAD

**Issue by bjornharvold** [MurhafSousli/ngx-sharebuttons#609]
#### Feature Description

We had this issue that would manifest in a lazy loaded module would take a really long time to load. The page for this module would have a way to share the page at the bottom. When we looked inside the modal, we found that 40% of the module was made up of the entire free FontAwesome icon library.

The feature request here is to include only the FontAwesome icons that Sharebuttons uses in IconsModule.

This is not a breaking issue. We are using the directive instead with full control.

🦸‍♂️

**Comment by MurhafSousli** [comment]
You can already load only the icons you want described here https://ngx-sharebuttons.netlify.app/#/icons

**Comment by bjornharvold** [comment]
Hi @MurhafSousli 

Yes, certainly. Just pointing out that IconsModule includes the entirety of font awesome; not just the icons you use. Why include a 1000 icons when you don't have to was my point. This is a perf ticket and not a bug ticket.

**Comment by MurhafSousli** [comment]
No it doesn't include all the icons! only the one used by library! can you show me how it include all the icons?

**Comment by MurhafSousli** [comment]
Accidently closed it, reopening..

**Comment by bjornharvold** [comment]
Hi @MurhafSousli 

As I was trying show how to replicate, I noticed that all the icons were not there in production bundle but in dev only. I do believe the tree shaking is what removes it in prod. All icons are clearly visible in the dev bundle... but that's not something to worry about.

I think we can safely close this issue.
