### ISSUE TITLE
SMS button opens Messages on Mac but without the URL

### ISSUE THREAD

**Issue by bjornharvold** [MurhafSousli/ngx-sharebuttons#610]
#### Reproduction

Steps to reproduce:
1. Go: https://ngx-sharebuttons.netlify.app/#/share-buttons-component on Mac OS
2. Click SMS button

**Comment by mm-kevinhara** [comment]
I can reproduce this locally, and add that SMS sharing does not include the URL when sharing on an Android device using `ngx-sharebuttons@11.0.0`.

**Comment by MurhafSousli** [comment]
This can be a new policy from Mac OS to prevent spamming. read this https://discussions.apple.com/thread/253094875

What we do here is that we attach the the URL to the body parameter.

Does the normal text appear in the message body?

**Comment by mm-kevinhara** [comment]
> Does the normal text appear in the message body?

No content appears in Messages at all.
