### ISSUE TITLE
Instagram & Share launch Button

### ISSUE THREAD

**Issue by HareshPoriya** [MurhafSousli/ngx-sharebuttons#611]
Hi Murhaf Sousli

I hope you are doing well. I recently came accross to using your "ngx-sharebutton" for the popup button. It's easy to use and works fine on my side. Appreciate it! I love this plugin.

Most of the social media icons are covered in it, but I am facing challenges finding an Instagram icon. Could you please let me know how I can use your plugin's Instagram icon? It would be helpful if you could show me how to find and use the Instagram icon.

I need one more help from your side. Can I change the share button icon color, or is there any way to apply custom CSS to it?

Regards,

**Comment by MurhafSousli** [comment]
Hi, thanks!

For Instagram, this issue has been opened like 10 times, Instagram has no share button, we cannot add something that does not exist!

For changing the color color, please check the docs on how to change a share button options here https://github.com/MurhafSousli/ngx-sharebuttons/wiki/Config-API#button-configuration, you can use the property `color` to change any button's color.

Here is the options source if you're interested to see all options https://github.com/MurhafSousli/ngx-sharebuttons/blob/master/projects/ngx-sharebuttons/src/lib/share.defaults.ts

**Comment by HareshPoriya** [comment]
Thank you so much Murhaf Sousli for update
