### ISSUE TITLE
When click on Messenger and Viber nothing happens, link doesn't open

### ISSUE THREAD

**Issue by abaiova** [MurhafSousli/ngx-sharebuttons#624]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/ngx-sharebuttons

Steps to reproduce:
1. Click on Messenger or Viber button
2.

#### Expected Behavior

What behavior were you expecting to see?

#### Actual Behavior

What behavior did you actually see?
Window of socila network opens like for other social media

#### Environment

- Angular:
- ngx-sharebuttons:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows 10 (Chrome)

**Comment by MurhafSousli** [comment]
It is expected, see the compatibility here https://github.com/MurhafSousli/ngx-sharebuttons/wiki/Native-Apps-Compatibility
