### ISSUE TITLE
setting meta tags doesn't seem to matter?

### ISSUE THREAD

**Issue by lcpichette** [MurhafSousli/ngx-sharebuttons#625]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/ngx-sharebuttons

https://stackblitz.com/edit/ngx-sharebuttons-1cstbc?file=src/app/home/home.component.html
![2022-12-16 14 34 48](https://user-images.githubusercontent.com/54318714/208200067-c41a6370-5b54-467a-a9d8-dc75122558f4.gif)

Steps to reproduce:
1. Set [title] directive (say to 'foo')
2. Set [url] directive (say to 'https://twitter.com)
3. Click share button, I tested linkedin
4. See that title does not override site's title. 

#### Expected Behavior

What behavior were you expecting to see?

[title] (and all other meta directives) should override SEO title/meta-attributes

#### Actual Behavior

What behavior did you actually see?

![2022-12-16 14 29 49](https://user-images.githubusercontent.com/54318714/208199523-621c50bd-c5cc-42dc-9810-77c3610564e5.gif)

#### Environment

Can be seen on the project's site.

- Angular: 
- ngx-sharebuttons: 
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): MacOS

**Comment by MurhafSousli** [comment]
That's expected, see here https://ngx-sharebuttons.netlify.app/#/faq

**Comment by lcpichette** [comment]
Out of curiosity, why have the metadata directives if it's just going to take it from the site regardless? 

Being able to have these directives (e.g. [title]) take priority over any site-metadata would be extremely useful.

**Comment by MurhafSousli** [comment]
It's up to the social network, some gets the meta tag value from the URL like pinterest preview so it works using the inputs, other's require the static meta tags like facebook

**Comment by lcpichette** [comment]
I see, that's a shame! Thank you for your swift and helpful responses!
