### ISSUE TITLE
Share via Mastodon

### ISSUE THREAD

**Issue by d-koppenhagen** [MurhafSousli/ngx-sharebuttons#626]
#### Feature Description

It would be great to support sharing via Mastodon as a default target.

```
https://<INSTANCE>/share?text=<TEXT>
```

e.g. 

```
https://techhub.social/share?text=Whoop!
```

Before redirecting to the URL for creating the post with predefined text, there should be a promt requesting for the instance URL as input

**Comment by MurhafSousli** [comment]
You can add your own share button if you have the right configuration for it

See here:
https://github.com/MurhafSousli/ngx-sharebuttons/blob/master/projects/ngx-sharebuttons/src/lib/share.defaults.ts
https://github.com/MurhafSousli/ngx-sharebuttons/wiki/Add-custom-buttons
https://ngx-sharebuttons.netlify.app/#/custom-button
