### ISSUE TITLE
how to add role to given tag 

### ISSUE THREAD

**Issue by Aryan576** [MurhafSousli/ngx-sharebuttons#629]
#### how can i add role to given code for accessibility purpose can any one can help me  

<a aria-label="linkedin" shareButton="linkedin" [url]="getUtmLink('linkedin', 'post')"  ><i
                                            class="fab fa-linkedin fa-2x"></i></a>

**Comment by MurhafSousli** [comment]
I don't think I understood, what is blocking you from adding the role attribute and what tag are you referring to? please fill the issue template properly!

**Comment by Aryan576** [comment]
yes Thanks for your help
