### ISSUE TITLE
Opened output not firing

### ISSUE THREAD

**Issue by MurhafSousli** [MurhafSousli/ngx-sharebuttons#633]
#### Reproduction

https://stackblitz.com/edit/ngx-sharebuttons-clexz4?file=src%2Fapp%2Fhome%2Fhome.component.html,src%2Fapp%2Fhome%2Fhome.component.ts

#### Environment

- Angular: 15
- ngx-sharebuttons: 11.0.0
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by Tweniee** [comment]
hello @MurhafSousli  i am new here can you please guide me to understand. thanks

**Comment by MurhafSousli** [comment]
I don't know, It needs investigation, it could be caused a browser update
