### ISSUE TITLE
Whatsapp redirection to 'api/web .whatsapp.com' controlled manually

### ISSUE THREAD

**Issue by lukaszsz99** [MurhafSousli/ngx-sharebuttons#635]
I want to redirect from Whatsapp ngx-sharebutton to https://api.whatsapp.com/ from desktop browser (ngx-sharebuttons v11.0.0).

**Current Behavior**
When clicking Whatsapp sharebutton using ... it redirects to ... :
using _desktop browser_ - it redirects to - https://web.whatsapp.com/
using _mobile browser_ - it redirects to - https://api.whatsapp.com/

**Expected Behavior**
When clicking Whatsapp sharebutton using ... it redirects to ... :
using _desktop browser_ - it redirects to - https://api.whatsapp.com/
using _mobile browser_ - it redirects to - https://api.whatsapp.com/

**Purpose**
When redirected to https://api.whatsapp.com/ on desktop, the Whatsapp application (desktop version) will open automatically if it is installed.

**Environment**
- Angular:
- ngx-sharebuttons:

**Comment by MurhafSousli** [comment]
Yes, you can override the props

Here is a working stackblitz https://stackblitz.com/edit/ngx-sharebuttons-zc2yo3?file=src%2Fapp%2Fapp.module.ts

```ts
ShareButtonsModule.withConfig({
  prop: {
    whatsapp: {
      share: {
        desktop: 'https://api.whatsapp.com/send?',
        android: 'whatsapp://send?',
        ios: 'https://api.whatsapp.com/send?'
      },
    }
  },
  debug: true,
}),
```
