### ISSUE TITLE
can we open shared details in pop up instead of new tab ? 

### ISSUE THREAD

**Issue by gauraveluminous** [MurhafSousli/ngx-sharebuttons#642]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/ngx-sharebuttons

Steps to reproduce:
1. when we click on any button for sharing purpose for eg on facebook , its opening in new tab
2.

#### Expected Behavior

I am expecting that it should open in a pop-up or in a small-size tab instead of a full new tab.

#### Actual Behavior

Currently, its opens in full tab when clicking on any button for sharing purposes.

#### Environment

- Angular:
- ngx-sharebuttons:
- Browser(s):  chrome , firefox
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by MurhafSousli** [comment]
Yes, you can!

```ts
import { SharerMethod } from 'ngx-sharebuttons';
import { ShareButtonsModule } from 'ngx-sharebuttons/buttons';


ShareButtonsModule.withConfig({
  sharerMethod: SharerMethod.Window
}),
```

Here is a demo https://stackblitz.com/edit/ngx-sharebuttons-pg5mns?file=src%2Fapp%2Fapp.module.ts

**Comment by gauraveluminous** [comment]
Thanks for the quick reply. I have checked and implemented and it's working perfectly.
________________________________
