### ISSUE TITLE
i am geting error with Angualr version 15

### ISSUE THREAD

**Issue by joshigolu08** [MurhafSousli/ngx-sharebuttons#646]
![image](https://github.com/MurhafSousli/ngx-sharebuttons/assets/89006870/acbbab82-6891-4bcb-bf6e-4450c0510079)
I am facing this issue with version 15 of angular 

I try with the older version of ngx-sharebuttons  (13,12, and 11 too) but the issue is the same there is nothing in the description about which version i have to use for angular 15
I set up a fresh project for it but the issue is the same

**Comment by alucardu** [comment]
Same issue here. Just installed the package in my Angular v15 project.

**Comment by MurhafSousli** [comment]
This info is not mentioned in the documentation, but you have to look at the changelog https://github.com/MurhafSousli/ngx-sharebuttons/blob/master/CHANGELOG.MD, If you have already tried v12 with Angular 15 and didn't work, it means the issue is in your project and I cannot help if you cannot reproduce it!

**Comment by joshigolu08** [comment]
> This info is not mentioned in the documentation, but you have to look at the changelog https://github.com/MurhafSousli/ngx-sharebuttons/blob/master/CHANGELOG.MD, If you have already tried v12 with Angular 15 and didn't work, it means the issue is in your project and I cannot help if you cannot reproduce it!

I tried with v12 but the issue is the same. also, you talked about there is a problem with my project so I also set up a fresh project but the issue is the same

**Comment by MurhafSousli** [comment]
Thanks for sharing!

**Comment by HaydenFerries** [comment]
> I got the solution for Angular v15 follow the steps:-
> 
> * install version 12 of  ngx-sharebuttons
> * install @fortawesome/angular-fontawesome": "^0.12.0" **because by default it will install v 0.13.0**
> * if you are using CSS in the angular project so  dont import styles in **Style.css** import them on **Angular.json** under the styles
> 
> problem solved Happy coding

This worked great for me, thanks so much.
