### ISSUE TITLE
add or replace twitter option for X

### ISSUE THREAD

**Issue by colorpicker-blue** [MurhafSousli/ngx-sharebuttons#650]
#### Feature Description

Twitter changed its brand. And the buttons should reflect this. Maybe it is too soon to remove the old one, but the addition of the new one should be a priority.

**Comment by MurhafSousli** [comment]
Yea, meanwhile you can override the icon, color and text from the global options

**Comment by Tweniee** [comment]
@MurhafSousli can this be assigned to me

**Comment by MurhafSousli** [comment]
Feel free to submit a PR

**Comment by Tweniee** [comment]
I understand it's a minor point, but noting it for future reference. We should address the issue at https://github.com/FortAwesome/angular-fontawesome/issues/411 and ensure that we are using the recommended version of the Font Awesome package, which is "6.4.2.
