### ISSUE TITLE
Unable to share image 

### ISSUE THREAD

**Issue by onkarz** [MurhafSousli/ngx-sharebuttons#653]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/ngx-sharebuttons

Steps to reproduce:
1. Run any Angular application. 
2. Declare image tag in ngx sharebuttons module.
3. Put image url.
4. And share.

#### Expected Behavior

What behavior were you expecting to see?

Image should be share. 

#### Actual Behavior

What behavior did you actually see?
Not able to share image. 

#### Environment

- Angular: 16
- ngx-sharebuttons: ^13.0.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows

**Comment by MurhafSousli** [comment]
https://ngx-sharebuttons.netlify.app/faq
