### ISSUE TITLE
Updating to Angular 17

### ISSUE THREAD

**Issue by Kenji94** [MurhafSousli/ngx-sharebuttons#658]
Hi,

We have been using your library for a while now and are really grateful!
We just updated our project to angular 17 but npm install won't work due to mismatch versions dependancies.
Using "npm install --legacy-peer-deps" works but it's not pretty :)
Would it be possible to have an upgrade to angular 17 for ngx-sharebuttons ?

Have a great day!
Best,
Kenji

**Comment by artisanvaultcode** [comment]
SUper cool , but needs to be updated for angular 17

**Comment by MurhafSousli** [comment]
If you are getting an error, try this a quick fix by the time it gets updated

Add the following in your `package.json` 

```
{
  "overrides": {
    "ngx-sharebuttons": {
       "@angular/common": "^17.0.0",
       "@angular/core": "^17.0.0",
       "@angular/cdk": "^17.0.0",
       "rxjs": "^7.0.0"
     }
},
}
```

**Comment by artisanvaultcode** [comment]
you have to fix all !! but thanks ..

**Comment by urtaav** [comment]
Hello, I still used your library in an Angular 15 project and now in Angular 17 it throws the following error:

ERROR:

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @fortawesome/angular-fontawesome@0.12.1
npm ERR! Found: @angular/core@17.2.3
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"^17.1.0" from the root project
npm ERR!   peer @angular/core@"17.2.3" from @angular/animations@17.2.3
npm ERR!   node_modules/@angular/animations
npm ERR!     @angular/animations@"^17.1.0" from the root project
npm ERR!     peerOptional @angular/animations@"17.2.3" from @angular/platform-browser@17.2.3
npm ERR!     node_modules/@angular/platform-browser
npm ERR!       @angular/platform-browser@"^17.1.0" from the root project
npm ERR!       3 more (@angular/forms, @angular/platform-browser-dynamic, @angular/router)
npm ERR!   9 more (@angular/cdk, @angular/common, @angular/compiler, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/core@"^15.0.0" from @fortawesome/angular-fontawesome@0.12.1
npm ERR! node_modules/@fortawesome/angular-fontawesome
npm ERR!   @fortawesome/angular-fontawesome@"^0.12.1" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/core@15.2.10
npm ERR! node_modules/@angular/core
npm ERR!   peer @angular/core@"^15.0.0" from @fortawesome/angular-fontawesome@0.12.1
npm ERR!   node_modules/@fortawesome/angular-fontawesome
npm ERR!     @fortawesome/angular-fontawesome@"^0.12.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.





I tried some solution by adding the override but it didn't work. The version of Angular used is 17.1.0
