### ISSUE TITLE
ngx-sharebuttons for angular 9.1.3 

### ISSUE THREAD

**Issue by lexysalonso** [MurhafSousli/ngx-sharebuttons#660]
#### Reproduction
Hello, I have two questions!
I would like to know what version of ngx-sharebuttons I can use for angular 9.1.3?
I would like to know if Messenger only works for the browser on the phone for the social network?

#### Environment

- Angular: 9.1.3
- ngx-sharebuttons:8.0.5
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by MurhafSousli** [comment]
Try v8.0.4 https://github.com/MurhafSousli/ngx-sharebuttons/blob/master/CHANGELOG.MD#804
https://github.com/MurhafSousli/ngx-sharebuttons/wiki/Native-Apps-Compatibility
https://github.com/MurhafSousli/ngx-sharebuttons/wiki/Using-Messenger-on-Desktop
