### ISSUE TITLE
Issue after upgrading to latest ngx-buttons version

### ISSUE THREAD

**Issue by sameerdighe28** [MurhafSousli/ngx-sharebuttons#675]
Steps to reproduce:
1. Upgrade ngx-buttons lib from 8.0.5
2. do `ng serve` and you will see below errors

#### Expected Behavior

As I read, released versions, no where it is written about changing a code snippet and was expecting backward compatibility 

#### Actual Behavior

But it does not seem to backward compatibility and getting below errors

<img width="1748" alt="Screenshot 2024-06-08 at 9 52 55 PM" src="https://github.com/MurhafSousli/ngx-sharebuttons/assets/9860021/1c53c5fb-5f73-42f3-921a-6325976feb3d">

#### Environment

- Angular: 11.0.9
- ngx-sharebuttons: 
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  macOS

**Comment by MurhafSousli** [comment]
Angular 11 is 7 years old, if you cannot upgrade you'll need to stick with older versions https://github.com/MurhafSousli/ngx-sharebuttons/blob/master/CHANGELOG.MD

**Comment by sameerdighe28** [comment]
okay I will try to upgrade Angular version but will this work or not in latest version on ngx-sharebutton ?

`import { ShareButtonsModule } from "ngx-sharebuttons/buttons";`
`import { ShareIconsModule } from "ngx-sharebuttons/icons";`

**Comment by MurhafSousli** [comment]
For the latest version, follow the new documentation https://github.com/MurhafSousli/ngx-sharebuttons/wiki/Share-Buttons-Component
