### ISSUE TITLE
docs: mention that 14.0.0 needs at least Angular 17.1.0, not only v17

### ISSUE THREAD

**Issue by burnaDLX** [MurhafSousli/ngx-sharebuttons#680]
#### Reproduction

Steps to reproduce:
1. Install Angular 17.0.x
2. Try to use the ShareDirective

#### Expected Behavior

Should work with Angular v17.0.x or state otherwise in the release notes / docs.

#### Actual Behavior

The directive input expects a SignalInput, but SignalInputs were first introduced in 17.1.0.

#### Environment

- Angular: 17.0.X
- ngx-sharebuttons: 14.0.0

**Comment by MurhafSousli** [comment]
I guess you are right, I will correct that in the changelog, for Angular < 17.1.0 should use ngx-scrollbar@16
