### ISSUE TITLE
Wrong import at the wiki fo share button component

### ISSUE THREAD

**Issue by Ronkiro** [MurhafSousli/ngx-sharebuttons#693]
Hello, i just found that the wiki is wrong and didn't find how to edit/contribute to the wiki

In:
https://github.com/MurhafSousli/ngx-sharebuttons/wiki/Share-Button-Component

it says `@import 'ngx-sharebuttons/button/themes/default';`

But "themes" is outside of "button"

![image](https://github.com/user-attachments/assets/4edb2770-150e-458b-8d76-d870ec4f0c66)

Should be `@import 'ngx-sharebuttons/themes/default';`

**Comment by MurhafSousli** [comment]
Thanks for reporting, its fixed!
