### ISSUE TITLE
Share using navigator.share()

### ISSUE THREAD

**Issue by Ronkiro** [MurhafSousli/ngx-sharebuttons#694]
Useful specially for phone-based apps

https://developer.mozilla.org/pt-BR/docs/Web/API/Navigator/share

**Comment by MurhafSousli** [comment]
I don't think this makes sense for this library. whoever wants to use the native sharing on Mobile, won't be using this library!

**Comment by Ronkiro** [comment]
Well, it was my case lol

**Comment by MurhafSousli** [comment]
You can do that by adding a custom button and hook it with a function that opens the button

https://github.com/MurhafSousli/ngx-sharebuttons/wiki/Custom-Share-Button#create-a-new-button
