### ISSUE TITLE
Whatsup share doesn't work

### ISSUE THREAD

**Issue by ngervasi** [MurhafSousli/ngx-sharebuttons#697]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/ngx-sharebuttons

Steps to reproduce:
<share-buttons [title]="lot.lot_title || ''" [include]="['_email', 'whatsapp', 'telegram', '_instagram', 'facebook', 'pinterest', 'x', 'linkedin', 'vk']" />

#### Actual Behavior
it opens: https://api.whatsapp.com/send?link=https://2024-test.goforarts.com/our-auctions/BENETTON-IL-FERRO-E-LANIMA/1-Toni-Benetton

with an error message "This link is incorrect. Close this window and try a different link."

If I manually edit the generated link to:
it opens: https://api.whatsapp.com/send?text=https://2024-test.goforarts.com/our-auctions/BENETTON-IL-FERRO-E-LANIMA/1-Toni-Benetton

it works (I changed "link" with "text")

#### Environment

- Angular: 18.2.8
- ngx-sharebuttons: 15.0.3
- Browser(s): any
- Operating System (e.g. Windows, macOS, Ubuntu):  any

**Comment by MurhafSousli** [comment]
For now it will work when you set a description to the button. I need to investigate why that happens without description!

**Comment by MurhafSousli** [comment]
Need to investigate why it doesn't work without providing a description, but for now you can set a description and it will work

**Comment by MurhafSousli** [comment]
Now it works even if description is not provided
