### ISSUE TITLE
Regression: ShareButtonDirective works in 1 of our 3 apps

### ISSUE THREAD

**Issue by bjornharvold** [MurhafSousli/ngx-sharebuttons#699]
#### Reproduction

https://stackblitz.com/edit/ngx-sharebuttons-jowqrz

Steps to reproduce:
1. Unable to reproduce.

- We are using ngx-sharebuttons in 3 different apps (see Stackblitz URL for our minimal configuration). 
- There is no global configuration. 
- In two of our [Tailwind] apps, we are using the same share component. It works in one and not in the other.
- In the third [Bootstrap] app, it doesn't work.
- In all apps, we can verify that the (opened) event captures the button click.
- In all apps, we can verify that clicking the copy button works.
- In on of the apps [Tailwind] a new window opens and forwards the user to the social network she clicked on.
- In two of the apps [Tailwind and Bootstrap], a new window to the social site (i.e. facebook) does not open. There are no errors in the console. The error is silent.
- This used to work when we tested a few months ago.

#### Environment

- Angular: 18.2.9
- ngx-sharebuttons: 15.03
- Browser(s): Chrome
- Operating System: macOS

Video that shows the apps running:
https://www.dropbox.com/scl/fi/e4m4utb6b9bjhvxzbnv6m/Screen-Recording-2024-10-27-at-14.00.06.mp4?rlkey=wu64se9ujyhtgc47mvtas30nu&dl=0

**Comment by MurhafSousli** [comment]
The information you provided is not helpful, if it works in one and doesn't work in the other it means the issue is on your end.

Turn on the debug option to help debugging your issue, this will log the generated link in the console when you click on the share button, and then you will be able to compare and find out what is the problem.

```ts
import { provideShareButtonsOptions, withConfig } from 'ngx-sharebuttons';

bootstrapApplication(App, {
  providers: [
    provideShareButtonsOptions(
      withConfig({
        debug: true
      })
    )
  ]
});
```

Also it's better list the things the does not work, instead of mentioning what works.

**Comment by bjornharvold** [comment]
Hi @MurhafSousli 

I completely agree that I couldn't provide any helpful information.

This morning I enabled debug mode and updated the code to add ng-bootstrap and a modal to the mix to get a bit closer to one of our app's setup here: https://stackblitz.com/edit/ngx-sharebuttons-jowqrz.

I am still not able to replicate and in our own app, the debug mode shows nothing. What should I expect debug mode to do for us?

🍻

**Comment by MurhafSousli** [comment]
As mentioned earlier the debug option should log the sharer link in the console then you can compare it with the one that app the works

**Comment by bjornharvold** [comment]
Hi @MurhafSousli 

I can confirm that in the app where it works, I can see the log statement. In the apps that don't work, there is no log statement even though I press the button. I know the button works because the Copy to clipboard button works but nothing else works.

Thoughts?
Bjorn

**Comment by bjornharvold** [comment]
Figured it out:

Here's the legacy code that needed to be removed:

```
{
    provide: SHARE_BUTTONS_CONFIG,
    useValue: {
      appId: '966891067125225',
      redirectUrl: 'https://ota.wink.travel',
    },
  },
```
